### PR TITLE
Add the stub of a checkpoint feature for the mash.

### PR DESCRIPTION
**Pull request by ralphbean**

### CODE REVIEW

**Comment by lmacken** [comment]
Yeah, we need this to ensure we're not commenting on updates, bugs, or sending update announcements multiple times when resuming a busted push.

**Comment by ralphbean** [comment]
> we need this to ensure we're not commenting on updates, bugs, or sending update announcements multiple times when resuming a busted push.

OK, I applied it to those four methods in 929adc8.

**Comment by ralphbean** [comment]
This fixes #214.

**Comment by lmacken** [comment]
Excellent :)

**Pull request merged**
