### PR TITLE
Do not expose the Duffy key in CI logs.

### PR DESCRIPTION
**Pull request by bowlofeggs**
Signed-off-by: Randy Barlow <randy@electronsweatshop.com>

### CODE REVIEW

**Comment by bowlofeggs** [comment]
This bug was introduced in 49e664057c09c07350fb002fdcf2ec68d6dc7f70.

**Comment by bowlofeggs** [comment]
The pip test failures are due to https://github.com/fedora-infra/bodhi/issues/2618 - we can safely ignore them.

**Review by puiterwijk — APPROVED** [review]
This is unfortunate, but it happens.
Nice catching it.

**Comment by bowlofeggs** [comment]
Thanks for the review and kind words!

**Pull request merged**
