### PR TITLE
Fix listing the missing requirements in bodhi-client

### PR DESCRIPTION
**Pull request by pypingou**
It seems that greenwave's output differs now compared to when
this code was written.

Signed-off-by: Pierre-Yves Chibon <pingou@pingoured.fr>

### CODE REVIEW

**Review by bowlofeggs — DISMISSED** [review]
I am unable to test this against Greenwave. Bodhi does not seem to work against the Greenwave in staging (or possibly that Greenwave does not work) and the Greenwave in production doesn't have any missing requirements since it is set to pass all builds.

I will assume that you tested this somehow.

**Comment by pypingou** [comment]
I have tested it in my vagrant box using:
`` python3 bodhi/client/__init__.py updates waive  python-arrow-0.8.0-5.fc28 --show --staging``

**Review by bowlofeggs — APPROVED** [review]

**Comment by pypingou** [comment]
jenkies test

**Comment by bowlofeggs** [comment]
These patches are planned to be included in the upcoming 3.10.0 release: #2556.

**Comment by bowlofeggs** [comment]
These patches are available in Copr:

https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release/

**Pull request merged**
