### PR TITLE
Correct the documented default for the greenwave_api_url setting.

### PR DESCRIPTION
**Pull request by bowlofeggs**
Signed-off-by: Randy Barlow <randy@electronsweatshop.com>

### CODE REVIEW

**Comment by matt8754** [comment]
👍

**Comment by pypingou** [comment]
👍 for me as well

**Comment by bowlofeggs** [comment]
The CI test failure is due to https://bugzilla.redhat.com/show_bug.cgi?id=1527666. Theoretically it should be fixed the next time there is a Rawhide compose. Since this PR is approved, I'm going to run the CI tests on each distro except rawhide locally, and if they pass I'll go ahead and merge.

I will also rebase this PR since it has a conflict in the release notes.

**Comment by bowlofeggs** [comment]
These tests pass on all containers except Rawhide locally, so I am going to merge this.

**Pull request merged**
