### PR TITLE
Run CI on Fedora containers as well.

### PR DESCRIPTION
**Pull request by bowlofeggs**
Signed-off-by: Randy Barlow <randy@electronsweatshop.com>

### CODE REVIEW

**Comment by bowlofeggs** [comment]
jenkies test

**Comment by puiterwijk** [comment]
I would strongly suggest to combine the different dockerfile's into a collective part and separate parts where needed, to make sure the list of packages stays in sync.

**Comment by bowlofeggs** [comment]
@puiterwijk Yeah I considered doing that, but there are a few issues - the Dockerfiles are different in subtle ways, and I don't know a great clean way to reuse code in Dockerfiles (afaik, you can't import other Dockerfiles in them) other than maybe using templating. For example, the F25 Dockerfile needs to install a bunch of fedmsg packages that don't exist anymore in F26+, and the Rawhide one uses all python2- names. Since they are almost entirely just a list of packages and since that list of packages is actually pretty specific to each Fedora release, I didn't feel too bad about the repetition.

Given that, do you think I should still try to consolidate the bits that are in common? Do you know a good technique for doing that with a Dockerfile, or is templating the way to go?

**Comment by bowlofeggs** [comment]
jenkies test

**Comment by bowlofeggs** [comment]
jenkies test

**Comment by bowlofeggs** [comment]
I have reworked the PR to share Dockerfile code where possible, and the tests pass now. This PR is ready for review!

**Review by jeremycline — APPROVED** [review]
Very nice.

:shipit:

**Review by puiterwijk — APPROVED** [review]
:golf:

**Pull request merged**
