### PR TITLE
Add a critpath field to packages and allow filtering packages using it

### PR DESCRIPTION
**Pull request by pypingou**

### CODE REVIEW

**Comment by pypingou** [comment]
We'll need to have a way to update this boolean, but I figured we could do this later :)

**Comment by cverna** [comment]
@pypingou, have a look at https://github.com/fedora-infra/bodhi/issues/2433. I don't think that having the boolean on the Packages model will work since a package can be critpath = True for F27 but critpath = Flase for F28.

cc'ing @vismay-golwala since he started to look at this too :)

**Comment by pypingou** [comment]
Hm fair point @cverna and reading that ticket, I'm pondering a little. The many-to-many relation is tempting but both infos (package_id and release_id) are also on the builds table. So I'm wondering if we just want to add a new table or if we should refactor the builds table as well to relate to that new table (tbh, I'm not convinced by this idea)

Anyway, if @vismay-golwala is working on it, I'll back out :)

**Comment by pypingou** [comment]
(waiting for the tests to report, before I close this PR :))

**Comment by ghost** [comment]
@pypingou ```builds``` table has foreign keys (```release_id``` and ```package_id```). What might be the potential issue if we refactor only ```releases``` and ```packages```?

**Comment by pypingou** [comment]
My ponder wasn't about refactorring `releases` and `packages` but potentially refactorring `builds` since it contains foreign_keys to `releases` and `packages` which the new table would also.

**Pull request closed without merging**
