### PR TITLE
Do not allow updates to be pushed if they fail the gating check.

### LINKED ISSUE #2342: Bodhi does not gate updates based on Greenwave when updates have non-truthy requirements
[```Update.check_requirements()```](https://github.com/fedora-infra/bodhi/blob/3.6.1/bodhi/server/models.py#L3165-L3248) returns True if ```Update.requirements``` is non-truthy. In Fedora's production Bodhi, updates do not have requirements by default, which means that the [greenwave decision check](https://github.com/fedora-infra/bodhi/blob/3.6.1/bodhi/server/models.py#L3243-L3244) is never reached unless developers type something into the update's requirements field. Since most developers do not do this, Fedora's Bodhi instance is effectively not gating any updates based on test results.

### PR DESCRIPTION
**Pull request by bowlofeggs**
fixes #2342

Signed-off-by: Randy Barlow <randy@electronsweatshop.com>

### CODE REVIEW

**Review by puiterwijk — APPROVED** [review]
This must be among the most humorous code vs test proportions I've seen for a bugfix :) :+1:

**Comment by puiterwijk** [comment]
The failed tests are only in py3, and at least two of them are in a file which has most other functions skip on py3.

**Comment by bowlofeggs** [comment]
Yeah, strangely the py3 tests passed in the Vagrant box. @frenzymadness noted that some Python 3 tests pass and fail seemingly randomly when the requester did not explicitly ask for JSON, because the response is randomly chosen between html and JSON when no request header is present. He's been fixing such tests by having them explicitly request JSON.

**Comment by bowlofeggs** [comment]
I believe https://github.com/fedora-infra/bodhi/pull/2284 might help some of these tests to pass.

**Review by pypingou — APPROVED** [review]
lgtm, thanks for looking into this! :)

**Comment by bowlofeggs** [comment]
I discovered that this patch is unstable in Python 3 as is, as two of the new tests will randomly fail/pass. @frenzymadness fixed this problem in the base class's ```get_csrf_token()``` so I'll just adjust the tests to use that instead:

```
diff --git a/bodhi/tests/server/services/test_updates.py b/bodhi/tests/server/services/test_updates.py
index 7f425928..5c60c4c7 100644
--- a/bodhi/tests/server/services/test_updates.py
+++ b/bodhi/tests/server/services/test_updates.py
@@ -708,8 +708,7 @@ class TestSetRequest(base.BaseTestCase):
         up.test_gating_status = TestGatingStatus.failed
         up.date_testing = datetime.utcnow() - timedelta(days=8)
         up.request = None
-        post_data = dict(update=nvr, request='stable',
-                         csrf_token=self.app.get('/csrf').json_body['csrf_token'])
+        post_data = dict(update=nvr, request='stable', csrf_token=self.get_csrf_token())

         res = self.app.post_json('/updates/%s/request' % str(nvr), post_data, status=400)

@@ -728,8 +727,7 @@ class TestSetRequest(base.BaseTestCase):
         up.requirements = ''
         up.test_gating_status = TestGatingStatus.passed
         up.date_testing = datetime.utcnow() - timedelta(days=8)
-        post_data = dict(update=nvr, request='stable',
-                         csrf_token=self.app.get('/csrf').json_body['csrf_token'])
+        post_data = dict(update=nvr, request='stable', csrf_token=self.get_csrf_token())

         res = self.app.post_json('/updates/%s/request' % str(nvr), post_data, status=200)
```

**Comment by pypingou** [comment]
:+1: for that patch

**Pull request merged**
