### PR TITLE
Drop the requirements feature

### LINKED ISSUE #1783: There seems to be two functions to turn a space/comma separated string into a list
Both ```[splitter()](https://github.com/fedora-infra/bodhi/blob/2.10.1/bodhi/server/util.py#L263-L277)``` and ```[tokenize()](https://github.com/fedora-infra/bodhi/blob/2.10.1/bodhi/server/util.py#L656-L665)``` seem to exist to turn strings of space or comma separated values into lists. We should ensure that they work the same, remove one of them, and convert code that uses the removed one to use the other.

### LINKED ISSUE #2340: Drop the requirements feature
Bodhi has code to ensure that updates pass certain test requirements that predates the Greenwave integration. Now that we have Greenwave integration, we don't need the requirements feature anymore. We can drop the ```Update.requirements``` column and remove it from the ```check_requirements()``` method.

### PR DESCRIPTION
**Pull request by sebwoj**
Fixes #2340
Fixes #1783

Signed-off-by: Sebastian Wojciechowski <s.wojciechowski89@gmail.com>

### CODE REVIEW

**Comment by ryanlerch** [comment]
gah, just jumped in on this one, and all the recent changes seem to make this conflict pretty bad. :(

 @sebwoj still interested in this one?

**Comment by sebwoj** [comment]
@bowlofeggs said that he is not sure about GW future, so he don't want to remove code responsible to communicate with RDB.

**Comment by ryanlerch** [comment]
@sebwoj thanks!

going to close this one off for now, feel free to reopen if i got this wrong.

**Comment by sebwoj** [comment]
@ryanlerch If you agree to remove "requirements", I can proceed with this PR.

**Pull request closed without merging**
