### PR TITLE
Give the waive dialog more context.

### PR DESCRIPTION
**Pull request by ralphbean**
This should fix the UI for #2363.

There, it claims that only one failing result is waived, but a read through the
method in `models.py` suggests that *all* unsatisfied requirements are
currently waived.

### CODE REVIEW

**Comment by pypingou** [comment]
Screenshot?

**Comment by pypingou** [comment]
Jenkies test

**Comment by pypingou** [comment]
Jenkins trips over: ````rawhide	pkg_resources.DistributionNotFound: The 'pyflakes<1.7.0,>=1.5.0' distribution was not found and is required by flake8```` but the tests are passing otherwise

**Comment by pypingou** [comment]
Idea: 
screenshot from 2018-05-30 16-03-16

I got it via: 
````
diff --git a/ bodhi/server/templates/update.html b/ bodhi/server/templates/update.html
index 47dad7f6..7e17258b 100644
--- a/ bodhi/server/templates/update.html       
+++ b/ bodhi/server/templates/update.html       
@@ -73,6 +73,7 @@ ${update.type} update for ${update.beautify_title(amp=True) | n}
                 if (missing_tests[req.item] === undefined)
                     missing_tests[req.item]= [];
                 missing_tests[req.item].push(req);
+                $('#failed_requirements').append('<li class="list-group-item">' + req.item + '</li>');
             }
             // the user may have already specified this in the required taskotron tests
             if ($.inArray(req.testcase, requirements) == -1) {
@@ -1132,9 +1133,17 @@ $(document).ready(function(){
         </button>
       </div>
       <div class="modal-body">
-          <div class="form-group">
-            <textarea class="form-control" id="waive_comment" name="waive_comment"></textarea>
+        <div class="row">
+          <div class="col-sm-offset-2 col-sm-10">
+            <p>Submitting this will waive all the following test results blocking this update:</p>
+            <ul id="failed_requirements" class="list-group list-group-flush"></ul>
+        </div>
+        <div class="form-group row">
+          <label for="waive_comment" class="col-sm-2 col-form-label">Comment</label>
+          <div class="col-sm-10">
+            <textarea class="form-control" id="waive_comment" name="waive_comment" placeholder="A reason for the waiver..." required></textarea>
           </div>
+        </div>
       </div>
       <div class="modal-footer">
         <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
````

What do you think?

**Comment by pypingou** [comment]
Actually, maybe we want to move ``$('#failed_requirements').append(...)`` outside of the if, I don't think we need to restrict the list to missing results.

**Comment by ralphbean** [comment]
I like the gist!  I'll try to incorporate it in the next few days but maybe tweak the layout a bit.

**Comment by pypingou** [comment]
> maybe tweak the layout a bit.

Big :+1: to that :D

**Comment by bowlofeggs** [comment]
jenkies test

**Comment by ralphbean** [comment]
@pypingou, I pulled in your change, but didn't alter it much.  :)

**Comment by ralphbean** [comment]
@pypingou, good to go now?

**Comment by pypingou** [comment]
@ralphbean looks good to me :)

**Comment by pypingou** [comment]
@bowlofeggs this is the diff I have locally to make the pop-up render w/ some data:

````
diff --git a/ bodhi/server/templates/update.html b/ bodhi/server/templates/update.html
index 7f6d16e6..21890da2 100644
--- a/ bodhi/server/templates/update.html       
+++ b/ bodhi/server/templates/update.html       
@@ -54,6 +54,11 @@ ${update.type} update for ${update.beautify_title(amp=True) | n}
 
     // handle Greenwave decision
     var handle_unsatisfied_reqs = function(data){
+        data['unsatisfied_requirements'].push(
+            {'item': 'rpmdeplint', 'testcase': 'bar', 'type': 'test-result-missing'});
+        data['unsatisfied_requirements'].push(
+            {'item': 'ci.centos.org.AtomicCI', 'testcase': 'bar', 'type': 'test-result-missing'});
+        console.log(data);
         $.each(data['unsatisfied_requirements'], function(i, req) {
             if (req.type == 'test-result-missing') {
                 if (missing_tests[req.item] === undefined)
@@ -416,7 +421,7 @@ $(document).ready(function() {
       });
     });
 
-% if self.util.can_waive_test_results(update):
+//% if self.util.can_waive_test_results(update):
     // handle for waiving test restuls.
     // set focus on the comment textarea when opening the modal.
     $("#waive_test_results").on('shown.bs.modal', function () {
@@ -452,7 +457,7 @@ $(document).ready(function() {
           },
       });
     })
-% endif
+//% endif
 });
 </script>
 
@@ -576,9 +581,9 @@ $(document).ready(function(){
             % endif
             <a id='unpush' class="btn btn-sm btn-danger"><span class="fa fa-fw fa-arrow-circle-left"></span> Unpush</a>
           % endif
-          % if self.util.can_waive_test_results(update):
+
             <a id='waive' class="btn btn-sm btn-primary" data-toggle="modal" data-target="#waive_test_results">Waive Test Results</a>
-          % endif
+
           </div>
         % else:
           <div id='updatebuttons' class="btn-group pull-right" role="group" aria-label="...">
@@ -1108,7 +1113,6 @@ $(document).ready(function(){
 
 </div>
 
-% if self.util.can_waive_test_results(update):
 <div class="modal fade" id="waive_test_results" tabindex="-1" role="dialog" aria-labelledby="waiveModalLabel" aria-hidden="true">
   <form>
   <div class="modal-dialog" role="document">
@@ -1140,6 +1144,5 @@ $(document).ready(function(){
     </form>
   </div>
 </div>
-% endif
 
 </div> <!-- end container -->
````

**Comment by bowlofeggs** [comment]
jenkies test

**Comment by bowlofeggs** [comment]
Hmm, with @pypingou's patch to simulate a failure, I see this:

screenshot from 2018-06-05 14-00-39

The code looks fine to me (I'm no JS person). @ralphbean have you been able to test this against a live WaiverDB/Greenwave?

**Comment by pypingou** [comment]
@bowlofeggs did you wait for greenwave's call to finish? I think I had something like this when I clicked too quickly on the button w/o waiting for greenwave's answer (and thus the pop-up isn't populated with info).

**Comment by ralphbean** [comment]
Ugh, I'm having trouble testing this again due to the stg resultsdb performance problems:

- https://pagure.io/fedora-infrastructure/issue/7021
- https://pagure.io/greenwave/pull-request/214

**Comment by ralphbean** [comment]
OK, resultsdb is happy again.  Let's focus on merging #2393 first, and then refactor this one on top of that.

**Comment by bowlofeggs** [comment]
I think we can also mark this as fixing https://github.com/fedora-infra/bodhi/issues/2270

**Comment by ralphbean** [comment]
Rebased on `develop` and included a note for #2270.

**Comment by bowlofeggs** [comment]
#2393 is merged now if you want to refactor this one on top.

**Comment by ralphbean** [comment]
OK - rebased on `develop`.  :)

**Comment by pypingou** [comment]
jenkies test

**Comment by ralphbean** [comment]
Rebased on `develop` again.

**Comment by ralphbean** [comment]
Rebased again.  @pypingou, should I keep rebasing - or wait to some point in the future when we circle back on this?

**Comment by bowlofeggs** [comment]
On 06/20/2018 09:00 AM, Ralph Bean wrote:
> should I keep rebasing - or wait to some point in the future when we
> circle back on this?

I don't mind if you don't want to rebase. I usually merge with GitHub's
"rebase and merge" button anyway, so I say the only time a rebase is
needed is if there are conflicts to resolve. Also, I've been AFK for
like a month ☺

**Review by bowlofeggs — APPROVED** [review]
It's difficult to test this since staging Greenwave returns 502's due to not knowing test results for all the updates I've spot checked, and production has CORS settings that disallow me to check against updates there.

However, the code looks OK to me and you said you tested it, so I will accept your testing.

Thanks for the patch!

**Comment by pypingou** [comment]
jenkies test

**Comment by pypingou** [comment]
It looks like the test is failing in jenkins with: ``rawhide	error: Could not find suitable distribution for Requirement.parse('backports.functools_lru_cache>=1.2.1')`` :(

**Comment by bowlofeggs** [comment]
The CI failure is due to https://bugzilla.redhat.com/show_bug.cgi?id=1607916

**Comment by bowlofeggs** [comment]
jenkies test

**Review by bowlofeggs — APPROVED** [review]

**Pull request merged**
