### PR TITLE
Allow the devbuildsys to work with el6 and el7 builds.

### PR DESCRIPTION
**Pull request by bowlofeggs**
Signed-off-by: Randy Barlow <randy@electronsweatshop.com>

### CODE REVIEW

**Comment by pypingou** [comment]
Looks fine to me

**Comment by pypingou** [comment]
tests seem to fail, but change lgtm

**Comment by bowlofeggs** [comment]
Yeah the test failures were due to the infra move (the container registry was down). Let's see if they work now.

**Comment by bowlofeggs** [comment]
jenkies test

**Pull request merged**
