### PR TITLE
Make CI tests more reliable

### PR DESCRIPTION
**Pull request by mattiaverga**
This should avoid some (not all) of the errors pointed out in #3946 
I have revised the logic behind those two tests, please check if it makes sense to you.

Signed-off-by: Mattia Verga <mattia.verga@tiscali.it>

### CODE REVIEW

**Comment by cverna** [comment]
Thanks for working on this, changes looks good to me :+1: 

Do you want to push another commit to fix the flake8 error ?

**Review by cverna — APPROVED** [review]

**Comment by mattiaverga** [comment]
Now it randomly fails because of:
```
06:08:25.629 container.py      INFO   running command ['bodhi', 'updates', 'request', '--url', 'http://localhost:8080', '--openid-api', 'http://id.dev.fedoraproject.org/api/v1/', '--user', 'guest', '--password', 'ipsilon', 'FEDORA-2020-8e09d34dc3', 'stable']
06:08:36.623 container.py      INFO   ACL validation mechanism was unable to determine ACLs.
06:08:36.758 container.py      ERROR  command failed
```
It seems `http://id.dev.fedoraproject.org/api/v1/` address isn't reachable from by browser also. Shouldn't be `https://id.stg.fedoraproject.org/api/v1/`?

**Comment by cverna** [comment]
> Now it randomly fails because of:
> 
> ```
> 06:08:25.629 container.py      INFO   running command ['bodhi', 'updates', 'request', '--url', 'http://localhost:8080', '--openid-api', 'http://id.dev.fedoraproject.org/api/v1/', '--user', 'guest', '--password', 'ipsilon', 'FEDORA-2020-8e09d34dc3', 'stable']
> 06:08:36.623 container.py      INFO   ACL validation mechanism was unable to determine ACLs.
> 06:08:36.758 container.py      ERROR  command failed
> ```
> 
> It seems `http://id.dev.fedoraproject.org/api/v1/` address isn't reachable from by browser also. Shouldn't be `https://id.stg.fedoraproject.org/api/v1/`?

So id.dev.fp.o in the integration test is just an ipsilon container that is run locally so if the container is up and running the test should be able to access it.

See https://github.com/fedora-infra/bodhi/blob/develop/devel/ci/integration/tests/fixtures/ipsilon.py

**Comment by cverna** [comment]
> > Now it randomly fails because of:
> > ```
> > 06:08:25.629 container.py      INFO   running command ['bodhi', 'updates', 'request', '--url', 'http://localhost:8080', '--openid-api', 'http://id.dev.fedoraproject.org/api/v1/', '--user', 'guest', '--password', 'ipsilon', 'FEDORA-2020-8e09d34dc3', 'stable']
> > 06:08:36.623 container.py      INFO   ACL validation mechanism was unable to determine ACLs.
> > 06:08:36.758 container.py      ERROR  command failed
> > ```
> > 
> > 
> > It seems `http://id.dev.fedoraproject.org/api/v1/` address isn't reachable from by browser also. Shouldn't be `https://id.stg.fedoraproject.org/api/v1/`?
> 
> So id.dev.fp.o in the integration test is just an ipsilon container that is run locally so if the container is up and running the test should be able to access it.
> 
> See https://github.com/fedora-infra/bodhi/blob/develop/devel/ci/integration/tests/fixtures/ipsilon.py

Ok so the `test_updates_request` fails because it is using an update that does not have a build associated with it --> FEDORA-2020-8e09d34dc3.
We could try to make sure that we have builds in the update used in the test.

The second test `test_updates_query_details` seems to fail for another reason, looking into it

**Comment by mattiaverga** [comment]
I've tweaked `test_updates_request` to only search for updates in testing, so that we'll not retrieve weird updates in strange statuses like that one.

I've also changed `test_updates_query_details`so that if there are no comments to the update, karma will be forced to 0.

**Comment by cverna** [comment]
Ha forgot I approved that before, anyhow the tests are passing now :)

**Comment by mattiaverga** [comment]
Yeah, but I don't think this is definitively fixed... at least the `fix_composes_list` didn't fix the error yesterday.
However I have identified that specific problem and I'll try to reproduce and fix it locally.

**Pull request merged**
