### PR TITLE
Have the authentication policy honor config settings

### PR DESCRIPTION
**Pull request by mattiaverga**

### CODE REVIEW

**Comment by AdamWill** [comment]
Ideally this should also include a test, right? I believe there was a test before #5288 , which 5288 removed.

**Comment by mattiaverga** [comment]
Re added tests

**Comment by AdamWill** [comment]
LGTM.

**Comment by mattiaverga** [comment]
Cool, I'll merge this in the 8.0 and push a 8.0.1 out since this is really an urgent bug.

**Comment by AdamWill** [comment]
I guess it's a good thing I got completely lost in the auth flow trying to get logout / login to work in the dev env! In the end I couldn't even get that to work so I had to hack in a workaround, but at least I found this, heh.

**Pull request merged**
