### PR TITLE
Only use one space between sentences in a production.ini comment.

### PR DESCRIPTION
**Pull request by bowlofeggs**
Signed-off-by: Randy Barlow <randy@electronsweatshop.com>

### CODE REVIEW

**Comment by bowlofeggs** [comment]
jenkies test

**Comment by bowlofeggs** [comment]
jenkies test

**Comment by bowlofeggs** [comment]
jenkies test

**Comment by bowlofeggs** [comment]
jenkies test

**Comment by bowlofeggs** [comment]
jenkies test

**Review by cverna — APPROVED** [review]
+1

**Comment by bowlofeggs** [comment]
Strange, there were a gazillion flake8 errors for code that isn't part of Bodhi. It's as if I had an unclean CI runner and got someone else's code or something. Maybe re-running will get it to pass?

**Comment by bowlofeggs** [comment]
jenkies test

**Pull request merged**
