### PR TITLE
Use podman instead of docker for running CI jobs.

### PR DESCRIPTION
**Pull request by bowlofeggs**
Signed-off-by: Randy Barlow <randy@electronsweatshop.com>

### CODE REVIEW

**Comment by bowlofeggs** [comment]
Hmm, it seems there is some sort of networking issue with this patch:

```
f28	STEP 3: RUN dnf upgrade -y libsolv || echo "We are not trying to test dnf upgrade, so ignoring dnf failure."
f28	error running container: error configuring network list if0 for [/bin/sh -c dnf upgrade -y libsolv || echo "We are not trying to test dnf upgrade, so ignoring dnf failure."]: failed to set bridge addr: could not add IP address to "cni0": file exists
f28	error building at step {Env:[DISTTAG=f28container FGC=f28  PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] Command:run Args:[dnf upgrade -y libsolv || echo "We are not trying to test dnf upgrade, so ignoring dnf failure."] Flags:[] Attrs:map[] Message:RUN dnf upgrade -y libsolv || echo "We are not trying to test dnf upgrade, so ignoring dnf failure." Original:RUN dnf upgrade -y libsolv || echo "We are not trying to test dnf upgrade, so ignoring dnf failure."}: exit status 1
```

**Comment by pypingou** [comment]
Change in itself looks fine to me, but I'm curious if there is a specific reason to switch? Is one faster than the other?

**Comment by bowlofeggs** [comment]
On 07/30/2018 03:10 AM, Pierre-Yves Chibon wrote:
> I'm curious if there is a specific reason to switch? Is one faster than
> the other?

There was a call to test out podman as a drop-in replacement for docker.
Since docker is a hostile upstream, I'm inclined to aid the effort to
replace it.

Clearly, it's not quite a drop-in replacement on CentOS 7 (though it
does work on Fedora).

**Comment by bowlofeggs** [comment]
Eh, I now feel unmotivated to pursue this at this time.

**Pull request closed without merging**
