### PR TITLE
Always show search box.

### LINKED ISSUE #1455: new theme requires locating tiny magnifying glass to show search box
the primary thing I do on bodhi is search for a package, but this is made considerably more clumsy since I have to locate and click a tiny magnifying glass in order to get to the search box. is search a secondary feature for your typical users?? can't it always be displayed? if not, could you provide a cookie to remember whether the user has opened the search box?

### PR DESCRIPTION
**Pull request by QuLogic**
Fixes #1455.

Signed-off-by: Elliott Sales de Andrade <quantum.analyst@gmail.com>

### CODE REVIEW

**Comment by cverna** [comment]
@ryanlerch could you take a look at this PR ? thanks

**Comment by mattiaverga** [comment]
Just my personal opinion here: the searchbar seems a little too prominent.
What about moving it in a row below the first masthead, reducing its width and height, like in the following mockup? The free space left in the bar could be used in future for a newsticker (for example for announcing Bodhi's outages for maintenance or releases in freeze state).
immagine

**Comment by QuLogic** [comment]
I disagree on its prominence; as noted in #1455, this is a primary method of interaction so it should be prominent.

Also, if I shrank the search bar to the size in your mockup, the results popup is also that width, which is too small to be useful. And unfortunately I do not know the right CSS incantations to make it work right.

**Comment by cverna** [comment]
Closing in favour of #3963

**Pull request closed without merging**
