### PR TITLE
Rollback a crashed database transaction

### PR DESCRIPTION
**Pull request by puiterwijk**
Signed-off-by: Patrick Uiterwijk <puiterwijk@redhat.com>

### CODE REVIEW

**Comment by pypingou** [comment]
Code change looks good to me, but jenkins fails because the code coverage is going down :(

**Comment by bowlofeggs** [comment]
@puiterwijk and I talked about this patch yesterday. We are going to try a few other things to address the issue this patch is intended to fix, which was that there were some entangled DB queries, likely due to Bodhi's strange Release caching. We're going to try to warm up caches in ```bodhi.server.main()``` so that they don't require a request to get warmed up. I believe the error happens due to a request warming the cache in the middle of another query.

I'll keep this PR open until we see how our other attempts to fix things work out.

**Comment by bowlofeggs** [comment]
Ugh, I accidentally deleted @pypingou's comment - I had the page loaded from a week ago in a tab and clicked refresh, and as my browser rendered the page I clicked to delete the @centos-ci comment that I must have deleted in another tab a week ago and it swapped out for @pypingou's comment under my mouse. Sorry!

**Comment by pypingou** [comment]
No biggy, iirc I was saying that the code looks fine to me and CI is unhappy because coverage lowers.
But your reasoning in your first comment makes sense and may moot this PR all together.

**Comment by bowlofeggs** [comment]
I think we can safely say that Bodhi is now working in OpenShift without this patch, so I am going to close this PR.

**Pull request closed without merging**
