### PR TITLE
#3065 removed unused settings

### PR DESCRIPTION
**Pull request by subhamkrai**
Signed-off-by: subhamkrai <subhamkumarrai03@gmail.com>

### CODE REVIEW

**Comment by pypingou** [comment]
The commit https://github.com/fedora-infra/bodhi/pull/3546/commits/62b1f17ce553801abae81ae534bcccbb8b08d9ac looks odd, did you rebase your branch before pushing it?

**Comment by subhamkrai** [comment]
> The commit [62b1f17](https://github.com/fedora-infra/bodhi/commit/62b1f17ce553801abae81ae534bcccbb8b08d9ac) looks odd, did you rebase your branch before pushing it?

Actually when I created PR number of file changed was more than the changes I did. So I pushed again with updated upstream.

**Comment by subhamkrai** [comment]
> > The commit [62b1f17](https://github.com/fedora-infra/bodhi/commit/62b1f17ce553801abae81ae534bcccbb8b08d9ac) looks odd, did you rebase your branch before pushing it?
> 
> Actually when I created PR number of file changed was more than the changes I did. So I pushed again with updated upstream.
 
@pypingou  is it okay ?

**Review by pypingou — APPROVED** [review]
git grep doesn't show this variable being used in the code so this looks good to me.

Thanks!

**Comment by subhamkrai** [comment]
> git grep doesn't show this variable being used in the code so this looks good to me.
> 
> Thanks!
thanks to you

**Pull request merged**
