### PR TITLE
Test updates rss path in CI

### PR DESCRIPTION
**Pull request by sebwoj**
Signed-off-by: Sebastian Wojciechowski <s.wojciechowski89@gmail.com>

### CODE REVIEW

**Comment by mattiaverga** [comment]
@Mergifyio rebase

**Review by mattiaverga — CHANGES_REQUESTED** [review]
Tests are failing:
```
Traceback:
devel/ci/integration/tests/test_bodhi.py:24: in <module>
    import bleach
E   ModuleNotFoundError: No module named 'bleach'
```

**Comment by sebwoj** [comment]
Tests are failing because `python3-bleach` is not installed in CI VM by default. This PR contains bleach install instruction [here](https://github.com/fedora-infra/bodhi/pull/3876/commits/ebf0e76755be33bd7c669f405102c22585d8cc94#diff-648f6cf8161a5268e88a106df6cc280a), but PR does not overrides file `cico.pipeline` in VM. The same situation is [here](https://github.com/fedora-infra/bodhi/pull/3363#issuecomment-549918405).

**Comment by cverna** [comment]
Closing since there no activity on this PR

**Pull request closed without merging**
