### PR TITLE
Let's use a f28 vagrant box for the development environment

### PR DESCRIPTION
**Pull request by cverna**
Signed-off-by: Clement Verna <cverna@tutanota.com>

### CODE REVIEW

**Comment by puiterwijk** [comment]
@centos-ci add to whitelist

**Comment by bowlofeggs** [comment]
jenkies test

**Review by bowlofeggs — CHANGES_REQUESTED** [review]
It seems that ```make``` no longer gets installed with F28 as it did with F27, which causes the ```btest``` alias not to work anymore:

```
[vagrant@bodhi-dev bodhi]$ btest
-bash: make: command not found
```

You can edit the packages that get installed in ```devel/ansible/roles/dev/tasks/main.yml```, so we can just have it install ```make``` there.

**Comment by bowlofeggs** [comment]
I did verify that ```d60f52c9cb04bfd4c5e950410611c746641f0b5f76830a53d44a0f1a43ab3fac``` is the correct hash, via F28 GPG signature.

**Comment by bowlofeggs** [comment]
jenkies test

**Review by bowlofeggs — APPROVED** [review]
Excellent, everything seems to work. Thanks!

**Pull request merged**
