### PR TITLE
Use autosummary to generate model and bindings docs.

### PR DESCRIPTION
**Pull request by bowlofeggs**
This pull request will combine nicely with #2000.

Signed-off-by: Randy Barlow <randy@electronsweatshop.com>

### CODE REVIEW

**Comment by bowlofeggs** [comment]
Apparently this is a real failure, as it seems that on rawhide a warning is now treated as an error. This is OK though, as #2000 actually fixes that warning anyway, so I should be able to rebase this pull request once #2000 is merged and things should pass.

**Comment by bowlofeggs** [comment]
jenkies test

**Comment by bowlofeggs** [comment]
jenkies test

**Review by puiterwijk — APPROVED** [review]
Looks good to me

**Comment by bowlofeggs** [comment]
The patch for this will be included in the upcoming 3.2.0 release:

https://github.com/fedora-infra/bodhi/pull/2092

**Pull request merged**
