### PR TITLE
Install cornice from RPMs on Rawhide.

### PR DESCRIPTION
**Pull request by bowlofeggs**
Signed-off-by: Randy Barlow <randy@electronsweatshop.com>

### CODE REVIEW

**Comment by bowlofeggs** [comment]
This won't pass CI until the next Rawhide compose.

**Comment by bowlofeggs** [comment]
jenkies test

**Comment by bowlofeggs** [comment]
jenkies test

**Comment by bowlofeggs** [comment]
jenkies test

**Review by pypingou — APPROVED** [review]
Looks fine to me

**Comment by bowlofeggs** [comment]
jenkies test

**Pull request merged**
