### PR TITLE
Reorganize the developer docs, splitting the two dev environments.

### PR DESCRIPTION
**Pull request by bowlofeggs**
With this commit, the developer docs are easier to read because the
two styles of development environment each get their own page. This
makes the developer landing page cleaner, and also makes it clearer
which docs are relevant to which environment style.

Signed-off-by: Randy Barlow <randy@electronsweatshop.com>

### CODE REVIEW

**Comment by bowlofeggs** [comment]
jenkies test

**Comment by bowlofeggs** [comment]
jenkies test

**Comment by bowlofeggs** [comment]
jenkies test

**Comment by bowlofeggs** [comment]
jenkies test

**Comment by bowlofeggs** [comment]
jenkies test

**Comment by abompard** [comment]
LGTM! 👍

**Review by abompard — APPROVED** [review]

**Comment by bowlofeggs** [comment]
The patch for this will be included in the upcoming 3.2.0 release:

https://github.com/fedora-infra/bodhi/pull/2092

**Pull request merged**
