### PR TITLE
Move the --user and --password arguments in a group with --openid-api

### PR DESCRIPTION
**Pull request by pypingou**
This way action which allow to set the --openid-api arguments will not
forget to add the --user and --password ones (as did the waive and
request-tests).
This commit also fixes the waive and request-tests action so they allow
logging in from the CLI via the --user and --password arguments as do
other actions requiring to be logged in.

Signed-off-by: Pierre-Yves Chibon <pingou@pingoured.fr>

### CODE REVIEW

**Review by nphilipp — COMMENTED** [review]
Would it make sense to add `openid_options` to `new_edit_options`, `save_edit_options` and `release_options` instead of adding the `@add_options(openid_options)` decorator to every function that uses these three?

**Comment by pypingou** [comment]
> Would it make sense to add `openid_options` to `new_edit_options`, `save_edit_options` and `release_options` instead of adding the `@add_options(openid_options)` decorator to every function that uses these three?

`new_edit_options`, `save_edit_options` and `release_options` are all lists, so we could expend the lists where they are defined but then we end up with some method which are explicit about including the `openid_options` and some which aren't because they bundle these options in others (new_edit_options...).

**Review by Zlopez — APPROVED** [review]
This looks much better

**Comment by nphilipp** [comment]
> > Would it make sense to add `openid_options` to `new_edit_options`, `save_edit_options` and `release_options` instead of adding the `@add_options(openid_options)` decorator to every function that uses these three?
> 
> `new_edit_options`, `save_edit_options` and `release_options` are all lists, so we could expend the lists where they are defined but then we end up with some method which are explicit about including the `openid_options` and some which aren't because they bundle these options in others (new_edit_options...).

Yeah, this could be more confusing than helpful.

**Comment by nphilipp** [comment]
@pypingou I'm not sure why the integration tests fail on f31 and Rawhide, they succeed in my Vagrant box. I'll force-push the branch without changes to retrigger the tests.

**Review by abompard — COMMENTED** [review]
Do you think that this change should be listed in the next release notes? If so, please add a file in the `news` directory as explained in [this documentation](https://github.com/fedora-infra/bodhi/blob/develop/docs/developer/index.rst#release-notes). Thanks!

**Review by abompard — DISMISSED** [review]
I think this is worthy of an entry in the release notes because new options have been added to the CLI.

**Pull request merged**
