### PR TITLE
Display the content type of updates in the UI.

### LINKED ISSUE #1329: Modify the Web UI to handle multiple content types
We will need to alter the web interface to handle multiple content types.

### PR DESCRIPTION
**Pull request by bowlofeggs**
This pull request depends on #1543, which isn't merged yet. Once that is merged, this can be rebased and tests can be written.

fixes #1329

Signed-off-by: Randy Barlow <randy@electronsweatshop.com>

### CODE REVIEW

**Comment by ralphbean** [comment]
:dog:

**Comment by pypingou** [comment]
👍 for me!

**Review by ralphbean — APPROVED** [review]
Yes.

**Pull request merged**
