### PR TITLE
Result != results

### PR DESCRIPTION
**Pull request by puiterwijk**
Signed-off-by: Patrick Uiterwijk puiterwijk@redhat.com

### CODE REVIEW

**Review by bowlofeggs — APPROVED** [review]
I wish we had test coverage for this ☹

**Comment by pypingou** [comment]
:+1: as well, but indeed no tests :(

**Comment by bowlofeggs** [comment]
@pypingou I'm going to allow this one in without tests because we are checking it live on production (really, ooof!). However, I do have a task warrior recurring task to increase bodhi's test coverage slowly to 100% over time, and I plan to require new code to be tested from now on.

Today is a bit of a special case because I want to make a bodh-2.3.2 quickly since production is broken. We are making sure this works by hotfixing production and then committing those changes here. Definitely not best practice, but I don't have much time to get production fixed before the weekend so I think it's allowable in this circumstance.

Also, technically I haven't merged the PR that requires test coverage yet ☺

**Comment by bowlofeggs** [comment]
I have cherry picked this one to the 2.3 branch.

**Pull request merged**
