### PR TITLE
Mv generic tests

### PR DESCRIPTION
**Pull request by bowlofeggs**

### CODE REVIEW

**Comment by bowlofeggs** [comment]
jenkies test

**Comment by bowlofeggs** [comment]
jenkies test

**Comment by bowlofeggs** [comment]
jenkies test

**Comment by bowlofeggs** [comment]
jenkies test

**Comment by pypingou** [comment]
Geez, another hard one to review :)

👍

**Review by ryanlerch — APPROVED** [review]

**Pull request merged**
