### PR TITLE
Drop F34 as a supported OS

### PR DESCRIPTION
**Pull request by abompard**
Also move the Vagrant VM to 35, which caused a couple issues with RabbitMQ.

### CODE REVIEW

**Comment by Zlopez** [comment]
@abompard So it's possible to run rabbitmq-server on F35?

**Comment by abompard** [comment]
@Zlopez Yeah but it's a bit tricky: https://bugzilla.redhat.com/show_bug.cgi?id=2020278#c6

**Comment by Zlopez** [comment]
@abompard Hm, so it just needs update for SELinux policy. I would prefer this to be done in [Fedora package](https://src.fedoraproject.org/rpms/rabbitmq-server) directly instead of adding the policy by provision script.

**Comment by abompard** [comment]
Yeah me too!

**Comment by abompard** [comment]
The integration test failure on rawhide seems unrelated.

**Pull request merged**
