### PR TITLE
Do not check source repos for comps or prestodelta.

### LINKED ISSUE #2572: RepodataException: Required part not in repomd.xml
While testing a compose in staging, the new repo sanity check code was not satisfied with the repository that was generated by Pungi. At this time I am not sure what exactly was unsatisfactory, but this is the traceback I saw:

```
[2018-09-04 21:41:38][fedmsg.consumers   ERROR]f28-updates-testing ComposerThread failed. Transaction rolled back. 
Traceback (most recent call last): 
  File "/usr/lib/python2.7/site-packages/bodhi/server/consumers/masher.py", line 339, in run 
    self.work() 
  File "/usr/lib/python2.7/site-packages/bodhi/server/consumers/masher.py", line 410, in work 
    self._compose_updates() 
  File "/usr/lib/python2.7/site-packages/bodhi/server/consumers/masher.py", line 950, in _compose_updates 
    self._sanity_check_repo() 
  File "/usr/lib/python2.7/site-packages/bodhi/server/consumers/masher.py", line 1154, in _sanity_check_repo 
    sanity_check_repodata(repodata) 
  File "/usr/lib/python2.7/site-packages/bodhi/server/util.py", line 287, in sanity_check_repodata 
    raise RepodataException('Required part not in repomd.xml') 
RepodataException: Required part not in repomd.xml
```

### PR DESCRIPTION
**Pull request by bowlofeggs**
fixes #2572

Signed-off-by: Randy Barlow <randy@electronsweatshop.com>

### CODE REVIEW

**Comment by bowlofeggs** [comment]
This still needs a test, but I hand tested a similar patch today in staging. I'll write a test for it next week.

**Comment by bowlofeggs** [comment]
This is now ready for review.

**Review by puiterwijk — DISMISSED** [review]
+1 thanks, and sorry for the initial omission :)

**Review by puiterwijk — APPROVED** [review]
Errr, looks like I forgot to approve it

**Comment by bowlofeggs** [comment]
jenkies test

**Comment by bowlofeggs** [comment]
I'm going to manually rebase and merge this since mergify seems stuck.

**Pull request merged**
