### PR TITLE
Let the user filter the list of updates by their status

### PR DESCRIPTION
**Pull request by pypingou**
This commit adds a drop-down list in which the user can select which
updates they want to see based on their status (stable, pending or both).

Fixes https://github.com/fedora-infra/bodhi/issues/590

### CODE REVIEW

**Comment by ralphbean** [comment]
Can we see a screenshot?

**Comment by ralphbean** [comment]
Also, why not go with adding multiple links next to each other, instead of a ``<select>`` block with javascript?  (I haven't seen it yet, but I imagine the white background of the select box will be visually jarring when placed inside the panel header).

**Comment by pypingou** [comment]
bodhi2_view_all

Here is the screenshot. It does look a little odd but I thought less odd then a collection of 3 links

**Comment by ralphbean** [comment]
Compare that with a diff like this:

```diff
diff --git a/bodhi/templates/user.html b/bodhi/templates/user.html
index 05859ea..8ca6d58 100644
--- a/bodhi/templates/user.html
+++ b/bodhi/templates/user.html
@@ -90,8 +90,16 @@
         <a href="${urls['recent_updates_rss']}">
           RSS <span class="fa fa-rss"></span>
         </a>
+        <a href="${urls['recent_updates']}&status=testing">
+          Testing <span class="count"></span>
+          <span class="glyphicon glyphicon-chevron-right"></span>
+        </a>
+        <a href="${urls['recent_updates']}&status=stable">
+          Stable <span class="count"></span>
+          <span class="glyphicon glyphicon-chevron-right"></span>
+        </a>
         <a href="${urls['recent_updates']}">
-          View all <span class="count"></span>
+          All <span class="count"></span>
           <span class="glyphicon glyphicon-chevron-right"></span>
         </a>
       </div>
```

That gives a screenshot that looks something like this:

multi-links

**Comment by pypingou** [comment]
Simpler and looks nice :+1: for me

**Comment by ralphbean** [comment]
Heh, however.. I don't know what those ``count`` span tags were for.  Removing them makes it a little simpler:

```diff
diff --git a/bodhi/templates/user.html b/bodhi/templates/user.html
index 05859ea..334abdd 100644
--- a/bodhi/templates/user.html
+++ b/bodhi/templates/user.html
@@ -90,9 +90,14 @@
         <a href="${urls['recent_updates_rss']}">
           RSS <span class="fa fa-rss"></span>
         </a>
+        <a href="${urls['recent_updates']}&status=testing">
+          Testing<span class="glyphicon glyphicon-chevron-right"></span>
+        </a>
+        <a href="${urls['recent_updates']}&status=stable">
+          Stable<span class="glyphicon glyphicon-chevron-right"></span>
+        </a>
         <a href="${urls['recent_updates']}">
-          View all <span class="count"></span>
-          <span class="glyphicon glyphicon-chevron-right"></span>
+          All<span class="glyphicon glyphicon-chevron-right"></span>
         </a>
       </div>
     </div>
```

**Pull request closed without merging**
