### PR TITLE
Do not comment on broken pull requests anymore.

### PR DESCRIPTION
**Pull request by bowlofeggs**
With the recent explosion in the number of jobs, it can be pretty
obnoxious for the CI system to add 10-20 comments on a PR for every
failed test.

Signed-off-by: Randy Barlow <randy@electronsweatshop.com>

### CODE REVIEW

**Review by cverna — DISMISSED** [review]
:+1:

**Comment by bowlofeggs** [comment]
I'm going to manually rebase and merge this, to solve the conflict.

**Comment by bowlofeggs** [comment]
The f28 pydocstyle test was a failure to clone the repo.

**Comment by bowlofeggs** [comment]
I ran the CI tests locally and they pass, so I am going to merge this.

**Pull request merged**
