### PR TITLE
Update README to include some of documentation

### PR DESCRIPTION
**Pull request by samrobbins85**
Makes it easier for people to understand what bodhi is

### CODE REVIEW

**Comment by pypingou** [comment]
It looks like your commit message is missing the `Signed-of-by` line. 
https://bodhi.fedoraproject.org/docs/developer/index.html has more information about it

**Review by Zlopez — APPROVED** [review]
LGTM

**Comment by pypingou** [comment]
Looks like it needs a rebase

**Comment by ryanlerch** [comment]
Looks like the original fork was removed. Created a new PR with this commit at #3683

**Pull request closed without merging**
