### PR TITLE
Raise line coverage to 100%.

### PR DESCRIPTION
**Pull request by bowlofeggs**
Signed-off-by: Randy Barlow <randy@electronsweatshop.com>

### CODE REVIEW

**Review by pypingou — APPROVED** [review]
:fireworks:

**Review by cverna — APPROVED** [review]
:tada:

**Comment by pypingou** [comment]
jenkies test

**Comment by pypingou** [comment]
Same error as in the other PR: ``rawhide	No local packages or working download links found for backports.functools_lru_cache>=1.2.1``

**Comment by bowlofeggs** [comment]
Cool, we'll just wait until Rawhide composes and try again then.

**Comment by bowlofeggs** [comment]
jenkies test

**Comment by bowlofeggs** [comment]
This patch is planned to be included in the upcoming 3.10.0 release: #2556.

**Pull request merged**
