### PR TITLE
Give more log detail when things are missing in repomd.xml.

### PR DESCRIPTION
**Pull request by bowlofeggs**
Signed-off-by: Randy Barlow <randy@electronsweatshop.com>

### CODE REVIEW

**Review by cverna — DISMISSED** [review]
+1

**Comment by bowlofeggs** [comment]
I'm going to rebase and merge this manually since Mergify seems stuck.

**Comment by bowlofeggs** [comment]
This feature is planned for inclusion in the upcoming 3.11.0 release: https://github.com/fedora-infra/bodhi/pull/2709

**Comment by bowlofeggs** [comment]
This patch has been deployed to Bodhi's staging environment:

https://bodhi.stg.fedoraproject.org

Please test and let us know if you find issues!

**Comment by bowlofeggs** [comment]
This feature is now deployed to Fedora's production instance.

**Pull request merged**
