### PR TITLE
Install bzip2 in all CI containers as it is needed to tar results.

### PR DESCRIPTION
**Pull request by bowlofeggs**
Signed-off-by: Randy Barlow <randy@electronsweatshop.com>

### CODE REVIEW

**Review by jeremycline — APPROVED** [review]
:shipit:

**Review by puiterwijk — CHANGES_REQUESTED** [review]
The host also wants something! :)

**Review by puiterwijk — APPROVED** [review]

**Comment by bowlofeggs** [comment]
Now that https://github.com/fedora-infra/bodhi/pull/1904 is merged, we can try to run these tests again.

**Comment by bowlofeggs** [comment]
jenkies test

**Review by igor-raits — APPROVED** [review]

**Pull request merged**
