### PR TITLE
Add the EPEL stats to the metrics page

### PR DESCRIPTION
**Pull request by pypingou**

### CODE REVIEW

**Comment by pypingou** [comment]
Fixes https://github.com/fedora-infra/bodhi/issues/263

**Comment by ralphbean** [comment]
Tight!  :+1:

**Comment by pypingou** [comment]
one thing about this one, locally, for me, the graph doesn't show anything (despite the fact that I use the DB dump from a couple of days ago).
So while I could test that it doesn't fail, I can't certify it does work as desired :)

**Comment by ralphbean** [comment]
Oh.  Hm.  Lemme try it here.

**Comment by ralphbean** [comment]
Looks like this now on my old old dataset:

old-dev-data

**Comment by ralphbean** [comment]
And... here's what it looks like with a snapshot of the prod data:

new-data

**Comment by ralphbean** [comment]
:+1: to merge here.

**Comment by pypingou** [comment]
:+1: as well, I could get it working as well, thanks @ralphbean

**Comment by lmacken** [comment]
Looks good, thanks!

**Pull request merged**
