### PR TITLE
Added direct webchat link of freenode

### PR DESCRIPTION
**Pull request by amanharitsh123**

### CODE REVIEW

**Comment by bowlofeggs** [comment]
jenkies test

**Review by bowlofeggs — APPROVED** [review]
LGTM. There's also mention of Freenode here in case you want to linkify it too :)

https://github.com/fedora-infra/bodhi/blob/develop/docs/index.rst

No big deal if you don't feel like it.

**Comment by amanharitsh123** [comment]
What is CI testing?..why this failed?...Can you please explain? 
Thanks :-)

**Comment by amanharitsh123** [comment]
jenkies test

**Comment by bowlofeggs** [comment]
Hi @amanharitsh123,

CI (Continuous Integration) is a [Jenkins job](https://ci.centos.org/job/bodhi-bodhi/) that runs the test suite on all pull requests, and there is a GitHub branch policy that requires CI to pass before pull requests can be merged.

In this case, it seems that there was some resource problem in the CentOS CI system. I'll ask it to re-run the tests.

**Comment by bowlofeggs** [comment]
jenkies test

**Review by bowlofeggs — APPROVED** [review]
Thanks!

**Pull request merged**
