### PR TITLE
Require setuptools, bodhi/server/__init__.py imports from pkg_resources

### PR DESCRIPTION
**Pull request by hroncok**

### CODE REVIEW

**Comment by ryanlerch** [comment]
@hroncok this one is passing all checks now other than DCO.

**Review by ryanlerch — APPROVED** [review]

**Comment by hroncok** [comment]
I've done the change via web UI and there is no way to edit the commit message to include the incantation. Feel free to do that when merging via the squash option. (I consider the requirement unnecessary, but if that is the only way to merge my PR, do it.)

**Comment by ryanlerch** [comment]
Yeah, i'm not comfortable doing it this way. Probably the easiest way around here is to close this PR, and open another PR via the edit file github functionality, and add "Signed-off-by: YOUR NAME \<YOURNAME@EXAMPLE.COM\>" as the first line of the commit body.

**Comment by hroncok** [comment]
https://github.com/fedora-infra/bodhi/pull/4205

**Pull request closed without merging**
