### PR TITLE
Add documentation for buildroot overrides.

### PR DESCRIPTION
**Pull request by bowlofeggs**
Signed-off-by: Randy Barlow <randy@electronsweatshop.com>

### CODE REVIEW

**Comment by bowlofeggs** [comment]
The CI failure is due to https://pagure.io/releng/issue/7377.

**Review by cverna — APPROVED** [review]

**Comment by bowlofeggs** [comment]
jenkies test

**Comment by bowlofeggs** [comment]
The CI tests fail due to https://pagure.io/releng/issue/7379.

**Comment by bowlofeggs** [comment]
jenkies test

**Pull request merged**
