### PR TITLE
Do not overwrite flags on update edits

### LINKED ISSUE #4563: `bodhi updates edit UPDATE` disables autokarma and autotime
I have been using `bodhi updates edit UPDATE` _with no options_ as workaround for unlocking submitted sidetag updates.
(Yes that is probably a hack but apart from some timing issues, it seems to work.)

However I noticed anyway that this command seems to disable autokarma and autotime?
which does not seem to desireable?

Admittedly running edit with no options is probably not that common (except for this workaround perhaps),
but I would not expect it to change the state of the update.

### PR DESCRIPTION
**Pull request by mattiaverga**
Fixes #4563 and also add the capability to unset flags when editing an update by CLI.

### CODE REVIEW

**Review by abompard — APPROVED** [review]

**Comment by abompard** [comment]
@mergifyio rebase

**Comment by abompard** [comment]
I confirm that the diff-cover check passes.

**Comment by mattiaverga** [comment]
@Mergifyio refresh

**Comment by mattiaverga** [comment]
@Mergifyio unqueue

**Pull request merged**
