### PR TITLE
Add a redirect from /updates/alias/title to /updates/alias

### PR DESCRIPTION
**Pull request by pypingou**
This provides some backward compatibility layer with bodhi1

Fixes https://github.com/fedora-infra/bodhi/issues/488

### CODE REVIEW

**Comment by lmacken** [comment]
This breaks the test suite:
```
======================================================================
ERROR: Test submitting an invalid request
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lmacken/.virtualenvs/bodhi-python2.7/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/lmacken/code/github.com/bodhi/bodhi/tests/functional/test_updates.py", line 1517, in test_invalid_request
    {'request': 'foo','csrf_token': self.get_csrf_token()}, status=400)
  File "/home/lmacken/.virtualenvs/bodhi-python2.7/lib/python2.7/site-packages/webtest/utils.py", line 37, in wrapper
    return self._gen_request(method, url, **kw)
  File "/home/lmacken/.virtualenvs/bodhi-python2.7/lib/python2.7/site-packages/webtest/app.py", line 735, in _gen_request
    expect_errors=expect_errors)
  File "/home/lmacken/.virtualenvs/bodhi-python2.7/lib/python2.7/site-packages/webtest/app.py", line 631, in do_request
    self._check_status(status, res)
  File "/home/lmacken/.virtualenvs/bodhi-python2.7/lib/python2.7/site-packages/webtest/app.py", line 666, in _check_status
    "Bad response: %s (not %s)", res_status, status)
AppError: Bad response: 405 Method Not Allowed (not 400)
```

**Comment by pypingou** [comment]
Ok, I see the error, the new service update_old gets the hand when a ``GET`` request is performed.

I've tried to add:
````
@update_request.get(accept=('application/json', 'text/json'), renderer='json',
                error_handler=bodhi.services.errors.json_handler)
@update_request.get(accept=('application/javascript'), renderer='jsonp',
                error_handler=bodhi.services.errors.jsonp_handler)
@update_request.get(accept="text/html", renderer="update.html",
                error_handler=bodhi.services.errors.html_handler)
def update_request_get(request):
    raise exception_response(405)
````
To keep the behavior consistent, but for some reason it does not seem to work, it looks like update_old always gets the hand.

**Comment by ralphbean** [comment]
This is pretty similar to how we did RSS redirects in 2732147.  We could probably simplify the way this works now:

- Remove the error handlers and validators.
- Boil it down to just redirection.
- Avoid using ``zz_`` as a prefix, and instead use something with "redirect" in the name.

We could also move all of our redirect endpoints to a ``bodhi/services/redirects.py`` file to reduce clutter, maybe?

**Comment by ralphbean** [comment]
OK, I added some reorganization here and a test for the test suite.  How's this look?

**Comment by lmacken** [comment]
Looks good to me! :

**Pull request merged**
