### PR TITLE
Removed ResourceWarning (open socket) in CLI

### LINKED ISSUE #2453: Bodhi's CLI does not seem to close its connection to the Bodhi server when it's done
I noticed that there is a warning in the dev environment when I query for my updates:

```
[vagrant@bodhi-dev bodhi]$ bodhi updates query --mine --rows 1
<snip>
sys:1: ResourceWarning: unclosed <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 57304), raddr=('127.0.0.1', 6543)>
```

We should close that connection before exiting so we are nice and tidy.

I later performed an authentication and saw a similar warning about not closing a connection to Fedora's proxy01 host on port 443, which I suspect was probably Ipsilon:

```
[vagrant@bodhi-dev bodhi]$ bodhi updates comment bodhi-3.8.0-1.fc28 "test"
Username: bowlofeggs
Password: 
The following comment was added to bodhi-3.8.0-1.fc28
test
sys:1: ResourceWarning: unclosed <ssl.SSLSocket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.121.78', 38958), raddr=('209.132.181.16', 443)>
sys:1: ResourceWarning: unclosed <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 38306), raddr=('127.0.0.1', 6543)>
```

### PR DESCRIPTION
**Pull request by ghost**
fixes #2453

Signed-off-by: Vismay Golwala <vgolwala@redhat.com>

### CODE REVIEW

**Comment by cverna** [comment]
@puiterwijk could give a look at this PR since it relates to python-fedora OpenIdBaseClient and how the requests session is handled there

**Comment by pypingou** [comment]
I wonder if we could fix this in python-fedora directly, thus benefiting all clients (dunno if it is doable there though)

**Comment by cverna** [comment]
@vismay-golwala are you looking into moving this to python-fedora ? If so I think we can close this PR.

**Comment by ghost** [comment]
@cverna yes, i am working on it. Still setting up environment for python-fedora. You can close this PR.

**Pull request closed without merging**
