### PR TITLE
Drop support for bleach 1.0 api

### PR DESCRIPTION
**Pull request by sebwoj**
Signed-off-by: Sebastian Wojciechowski <s.wojciechowski89@gmail.com>

### CODE REVIEW

**Comment by mattiaverga** [comment]
@cverna shall we merge this in the next release, or do you prefer to wait for a Bodhi v6 release?
The latest bleach v1 release was made in 2016 and the latest Fedora release before bleach v2 was F27.

**Comment by cverna** [comment]
> @cverna shall we merge this in the next release, or do you prefer to wait for a Bodhi v6 release?
> The latest bleach v1 release was made in 2016 and the latest Fedora release before bleach v2 was F27.

Let's merge it now :-)

**Comment by cverna** [comment]
@mattiaverga did you do the review ? Or do you want to do it ?

**Review by mattiaverga — APPROVED** [review]
Everything seems fine, so let's merge it.

**Pull request merged**
