### PR TITLE
changed models.py to __init__.py

### PR DESCRIPTION
**Pull request by ankit01ojha**
renamed models.py to **init**.py

### CODE REVIEW

**Comment by bowlofeggs** [comment]
Can you update your commit message to have end with this line:

```
fixes #1057
```

This way #1057 will automatically be closed by github when we merge the commit, and it's also easy to tie the commit to the related issue.

**Review by bowlofeggs — CHANGES_REQUESTED** [review]
I'm a little surprised that the tests pass with this change, but they do. However, I believe this is due to poor test coverage/quality, as there are certainly still places in the code that reference the old location:

```
rbarlow@planck ~/d/bodhi> git grep models.\*models
alembic/README.rst:Say you've modified a model in ``bodhi/server/models/models.py``. You now need to
alembic/versions/3b85a0db1a5d_release_states.py:from bodhi.server.models.models import ReleaseState
bodhi/server/views/generic.py:            models.Update.type==models.UpdateType.security)
bodhi/server/views/generic.py:        models.Update.status==models.UpdateStatus.testing)
bodhi/tests/server/models/test_models.py:    @mock.patch('bodhi.server.models.models.bugtracker.close')
bodhi/tests/server/models/test_models.py:    @mock.patch('bodhi.server.models.models.bugtracker.comment')
bodhi/tests/server/models/test_models.py:    @mock.patch('bodhi.server.models.models.bugtracker.close')
bodhi/tests/server/models/test_models.py:    @mock.patch('bodhi.server.models.models.bugtracker.comment')
bodhi/tests/server/scripts/test_approve_testing.py:from bodhi.server.models import models
bodhi/tests/server/scripts/test_approve_testing.py:            for c in self.db.query(models.Comment).order_by(models.Comment.timestamp).all()]
bodhi/tests/server/scripts/test_approve_testing.py:            for c in self.db.query(models.Comment).order_by(models.Comment.timestamp).all()]
bodhi/tests/server/scripts/test_approve_testing.py:            for c in self.db.query(models.Comment).order_by(models.Comment.timestamp).all()]
bodhi/tests/server/scripts/test_approve_testing.py:            for c in self.db.query(models.Comment).order_by(models.Comment.timestamp).all()]
bodhi/tests/test_style.py:        enforced_paths = ['bodhi/server/models/models.py', 'bodhi/server/services/updates.py',
```

That grep statement may not cover everything either, but we will at least need to address these.

**Comment by ankit01ojha** [comment]
ok I'll do it , thanks

**Comment by bowlofeggs** [comment]
@ankit01ojha This is not going to work - all the models are now deleted, and imports are referencing **init** explicitly. Additionally, it sounds like two people prefer the second option (myself and @trishnaguha) so perhaps that is the way we should go. To be honest, it's always a little surprising when `__init__.py` files have lots of code.

I say we drop the `from models import *` from **init**.py and fix any failing imports.

**Comment by trishnaguha** [comment]
We can close this one as @ankit01ojha has opened another PR for the same #1100 .

**Comment by bowlofeggs** [comment]
@ankit01ojha For future pull requests, you can force push your branch instead of opening new pull requests when you want to make changes. I usually make my changes in my branch, then use `git commit --amend` to amend my previous commit (this allows me to only make one commit and keep changing it) and then `git push -f` to force push the amended commit over my branch. This way, the same PR can be updated while maintaining a single commit.

**Comment by ankit01ojha** [comment]
@bowlofeggs, I will keep this in mind for the next time.

**Pull request closed without merging**
