### PR TITLE
docs: Add 'frozen' state to Bodhi documentation

### LINKED ISSUE #3505: Add a banner during Freezes
Just before every release, I see people wondering why their packages are not pushed to stable. If Bodhi showed a message _somewhere_, this would probably be less common.

### PR DESCRIPTION
**Pull request by richardgreg**
Fixes: #3505

Signed-off-by: Richard O. Gregory <richardgrecoson@gmail.com>

### CODE REVIEW

**Comment by richardgreg** [comment]
Reading through #3505 it seems the 'frozen banner' issue is solved by Sebastian. All that's remaining is for `frozen` to be added to docs.

I think it wise for someone with a more intimate knowledge of Bodhi to provide all the details of what's really going on in the frozen state so it can go in the `Frozen` paragraph.

**Comment by richardgreg** [comment]
@cverna what do you think?

**Comment by cverna** [comment]
> @cverna what do you think?
Looks good, Frozen is when we stabilize a release before the release Beta or GA (Generaly Available), in such state all updates are blocked and release engineering will only push the updates that have been given a freeze break exception to fix a bug.

If you can make something from that to add in the Frozen description that would be great :-)

**Review by cverna — APPROVED** [review]
Thanks

**Pull request merged**
