### PR TITLE
Prepare tests of CSRF for Python 3

### PR DESCRIPTION
**Pull request by frenzymadness**
Hello.

I've ported tests of CSRF to Python 3 compatible form. Changes contain:

- Be explicit when requesting JSON
- Compare decoded results

Have a nice day. Lumír

### CODE REVIEW

**Comment by frenzymadness** [comment]
This change also fixes the validator test so it might fix also others where `get_csrf_token()` is called.

**Comment by frenzymadness** [comment]
Hello.

It seems that I found a root of all troubles with Python 3 incompatibilities. Could you please take a look at this PR and PRs #2285  and #2286? After all three will be merged, I can unblock a lot of skipped tests.

Added `test_overrides.py` is another tests file where a lot of tests was blocked by `get_csrf_token()` call.

Thank you.
Lumír

**Comment by bowlofeggs** [comment]
There seems to be one test failure:

```
f27	=================================== FAILURES ===================================
f27	_________________ TestOverridesService.test_unexpire_override __________________
f27	
f27	self = <bodhi.tests.server.services.test_overrides.TestOverridesService testMethod=test_unexpire_override>
f27	publish = <MagicMock name='publish' id='139692847788216'>
f27	
f27	    @mock.patch('bodhi.server.notifications.publish')
f27	    def test_unexpire_override(self, publish):
f27	        # First expire a buildroot override
f27	        old_nvr = u'bodhi-2.0-1.fc17'
f27	        override = RpmBuild.get(old_nvr, self.db).override
f27	        override.expire()
f27	        self.db.add(override)
f27	        self.db.flush()
f27	    
f27	        publish.assert_called_once_with(
f27	            topic='buildroot_override.untag', msg=mock.ANY)
f27	        publish.reset_mock()
f27	    
f27	        # And now push its expiration_date into the future
f27	        res = self.app.get('/overrides/%s' % old_nvr)
f27	>       o = res.json_body['override']
f27	
f27	bodhi/tests/server/services/test_overrides.py:612: 
f27	_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
f27	/usr/lib/python3.6/site-packages/webob/response.py:587: in _json_body__get
f27	    return json.loads(self.body.decode('UTF-8'))
f27	/usr/local/lib/python3.6/site-packages/simplejson/__init__.py:518: in loads
f27	    return _default_decoder.decode(s)
f27	/usr/local/lib/python3.6/site-packages/simplejson/decoder.py:370: in decode
f27	    obj, end = self.raw_decode(s)
f27	/usr/local/lib/python3.6/site-packages/simplejson/decoder.py:400: in raw_decode
f27	    return self.scan_once(s, idx=_w(s, idx).end())
f27	/usr/local/lib/python3.6/site-packages/simplejson/scanner.py:79: in scan_once
f27	    return _scan_once(string, idx)
f27	_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
f27	
f27	string = '\n\n\n\n\n<!DOCTYPE html>\n<html lang="en">\n  <head>\n    <meta charset="utf-8" />\n    <meta http-equiv="X-UA-Compa...           \'user\': \'guest\',\n            \'package\': \'bodhi\',\n      });\n    </script>\n\n  </body>\n</html>\n'
f27	idx = 5
f27	
f27	    def _scan_once(string, idx):
f27	        errmsg = 'Expecting value'
f27	        try:
f27	            nextchar = string[idx]
f27	        except IndexError:
f27	            raise JSONDecodeError(errmsg, string, idx)
f27	    
f27	        if nextchar == '"':
f27	            return parse_string(string, idx + 1, encoding, strict)
f27	        elif nextchar == '{':
f27	            return parse_object((string, idx + 1), encoding, strict,
f27	                _scan_once, object_hook, object_pairs_hook, memo)
f27	        elif nextchar == '[':
f27	            return parse_array((string, idx + 1), _scan_once)
f27	        elif nextchar == 'n' and string[idx:idx + 4] == 'null':
f27	            return None, idx + 4
f27	        elif nextchar == 't' and string[idx:idx + 4] == 'true':
f27	            return True, idx + 4
f27	        elif nextchar == 'f' and string[idx:idx + 5] == 'false':
f27	            return False, idx + 5
f27	    
f27	        m = match_number(string, idx)
f27	        if m is not None:
f27	            integer, frac, exp = m.groups()
f27	            if frac or exp:
f27	                res = parse_float(integer + (frac or '') + (exp or ''))
f27	            else:
f27	                res = parse_int(integer)
f27	            return res, m.end()
f27	        elif nextchar == 'N' and string[idx:idx + 3] == 'NaN':
f27	            return parse_constant('NaN'), idx + 3
f27	        elif nextchar == 'I' and string[idx:idx + 8] == 'Infinity':
f27	            return parse_constant('Infinity'), idx + 8
f27	        elif nextchar == '-' and string[idx:idx + 9] == '-Infinity':
f27	            return parse_constant('-Infinity'), idx + 9
f27	        else:
f27	>           raise JSONDecodeError(errmsg, string, idx)
f27	E           simplejson.errors.JSONDecodeError: Expecting value: line 6 column 1 (char 5)
f27	
f27	/usr/local/lib/python3.6/site-packages/simplejson/scanner.py:70: JSONDecodeError
```

**Comment by frenzymadness** [comment]
Fixed!

The DCO check fails because there is one commit which needs to be squashed during a merge. All regular commits contain DCO as usual.

**Review by bowlofeggs — APPROVED** [review]
Fantastic, and great timing too because I just hit some problems with CSRF in #2346!

Thanks so much!

**Pull request merged**
