### PR TITLE
Reload builds and releases after we commit the transaction

### PR DESCRIPTION
**Pull request by puiterwijk**
Signed-off-by: Patrick Uiterwijk <puiterwijk@redhat.com>

### CODE REVIEW

**Comment by bowlofeggs** [comment]
We need tests for this.

**Comment by puiterwijk** [comment]
Well, I'd say that the fact that it gets through the test is proof that the code doesn't break new things.
Testing for the failure that this fixes is going to be difficult as long as the test system is using a different database abstraction layer that doesn't care about session-locality of objects.

**Comment by bowlofeggs** [comment]
@puiterwijk That's a good point, and I'm not sure why it didn't occur to me before.

I am seeing one test error and one test failure on this pull request:

```
======================================================================
ERROR: Test submitting an update for a package that has an older build within
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/vagrant/bodhi/tests/server/services/test_updates.py", line 2422, in test_update_with_older_build_in_testing_from_diff_user
    up = self.db.query(Update).filter_by(title=title).one()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 2724, in one
    raise orm_exc.NoResultFound("No row was found for one()")
NoResultFound: No row was found for one()

======================================================================
FAIL: https://github.com/fedora-infra/bodhi/issues/219
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/vagrant/bodhi/tests/server/services/test_updates.py", line 2512, in test_submitting_multi_release_updates
    self.assertEquals(len(data['caveats']), 1)
AssertionError: 0 != 1
```

**Comment by bowlofeggs** [comment]
I discovered https://github.com/fedora-infra/bodhi/issues/1186 while trying to figure out why these two tests are failing.

**Comment by jeremycline** [comment]
I fixed a regression this commit introduced and rebased it in #1232 so I'm going to close this.

**Pull request closed without merging**
