### PR TITLE
readme.rst doclinks updated

### PR DESCRIPTION
**Pull request by vignesh7056**
doclinks showing 404 error is rectified, links updated

### CODE REVIEW

**Comment by vignesh7056** [comment]
Signed-off-by: vignesh7056 [vignesh7056@gmail.com](mailto:vignesh7056@gmail.com)

**Comment by mattiaverga** [comment]
Thanks for the PR!
you should signoff the commit with `git commit --amend --signoff` and force push to pass the DCO test.

Also, I think it is best to point to the `develop` directory rather than `7.0`, so that we're sure to point the user to the most updated guidelines.

**Comment by vignesh7056** [comment]
@mattiaverga
1, i think it is already pointing to develop branch.
2, git commit signoff added.
3, dont know how to do dco but already tried a force push.
  can you help me to fix this issue. also one review is pending.

**Comment by mattiaverga** [comment]
> 1, i think it is already pointing to develop branch. 

No, you should not use `7.0` in the link, change it to `develop` instead.

> 2, git commit signoff added. 
> 3, dont know how to do dco but already tried a force push. can you help me to fix this issue. also one review is pending.

Look at the [DCO test results](https://github.com/fedora-infra/bodhi/pull/5123/checks?check_run_id=11810476036) and you'll find instructions how to fix it.

**Comment by vignesh7056** [comment]
@mattiaverga 
doc links updated.
dco failing- tutorial not helping

**Comment by vignesh7056** [comment]
@mattiaverga DCO passed only code review left.

**Comment by mattiaverga** [comment]
Can you squash the change in a single commit and rebase to the latest upstream? You may have to dig in git tutorials how to achieve that.

**Comment by vignesh7056** [comment]
Sure. Will try and update you soon.

**Pull request closed without merging**
