### PR TITLE
Revert "Install python2-backports-functools_lru_cache in Rawhide CI."

### PR DESCRIPTION
**Pull request by bowlofeggs**
This reverts commit e084a42a1330a88529e72ac814c7670630c0a167.

This will not pass CI until the fix for https://bugzilla.redhat.com/show_bug.cgi?id=1607916 propagates to the mirrors.

### CODE REVIEW

**Comment by pypingou** [comment]
looks fine to me but jenkins seems to imply that somewhere else we're asking for this package.

**Comment by bowlofeggs** [comment]
@pypingou no it's just that the python-arrow fix had not propagated to the mirrors yet when Jenkins ran. I'm not sure if there's been a successful compose yet. I'll ask it to run again to find out.

**Comment by bowlofeggs** [comment]
jenkies test

**Comment by bowlofeggs** [comment]
Yeah there still hasn't been a successful rawhide compose, so the fix for python-arrow still hasn't reached mirrors.

**Comment by bowlofeggs** [comment]
jenkies test

**Review by cverna — APPROVED** [review]
+1

**Pull request merged**
