### PR TITLE
Do not ask for_original_spec_nvr results from greenwave.

### PR DESCRIPTION
**Pull request by cverna**
Greenwave already takes care of getting the tests results for original_spec_nvr
in resultsdb, hence bodhi does not need to ask for it.
See greenwave code (https://pagure.io/greenwave/blob/master/f/greenwave/resources.py#_95)

This will have for effect to improve the performance of bodhi's
requests to greenwave.

Signed-off-by: Clement Verna <cverna@tutanota.com>

### CODE REVIEW

**Review by nphilipp — COMMENTED** [review]
The changes look good to me, also considering recent email conversation concerning Bodhi/Greenwave performance.

Two thoughts about the commit message:

- The title contains a typo, I guess `for_original_spec_nvr` should be `for original_spec_nvr`.
- Referencing Greenwave code by branch name isn't stable. Perhaps link the current tip of master by hash instead? E.g.:

```
See the relevant code in Greenwave:

https://pagure.io/greenwave/blob/4e427729f711b73a3018614cf9c889efa3b80ce1/f/greenwave/resources.py#_95
```

**Comment by cverna** [comment]
Update the commit message after @nphilipp comments.

**Review by nphilipp — APPROVED** [review]
Thanks!

Approved, as per discussion between @abompard, @cverna and myself.

**Review by abompard — APPROVED** [review]
After looking at why the need for `original_spec_nvr` arised, it's apparently been partly removed in the JS (`update.html`) so it's safe to finish removing it there.
I don't think we need it anywhere anymore.

**Pull request merged**
