### PR TITLE
Handling status for revoking request on pending update

### LINKED ISSUE #645: revoking the request on a pending update should set the status to revoked
it currently removed the request, but it leaves the status as pending (which is super confusing).

### PR DESCRIPTION
**Pull request by trishnaguha**
Trying to fix #645

### CODE REVIEW

**Comment by ralphbean** [comment]
@trishnaguha, this looks like a good start.  What do you think, @lmacken?

@trishnaguha have you looked at the test suite yet?  It might be a good opportunity to add a new test that tries to exercise this code path.

**Comment by pypingou** [comment]
Looks like you did a merge, maybe you wanted to do a rebase?

**Comment by trishnaguha** [comment]
Yes I did merge :/ .Let me fix this.

**Comment by trishnaguha** [comment]
Since I have messed up with git here, So I'm closing this one.
PR https://github.com/fedora-infra/bodhi/pull/773 replaces this one.

**Pull request closed without merging**
