### PR TITLE
Add support for content_type to the Python bindings.

### LINKED ISSUE #1327: Modify the Python bindings to work with the new multi-type REST API
We need to modify the Python bindings so they work with the new REST API that will results from #1325.

### PR DESCRIPTION
**Pull request by bowlofeggs**
fixes #1327

Signed-off-by: Randy Barlow <randy@electronsweatshop.com>

### CODE REVIEW

**Review by ralphbean — APPROVED** [review]
:+1:  The tests..

.. they give me confidence.

**Comment by ralphbean** [comment]
Am I reading this wrong?

```
❯ diff-cover coverage.xml --compare-branch=origin/develop --fail-under=100                                                  bodhi/git/1327 
Failure. Coverage is below 100.0%.
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged, and unstaged changes
-------------
bodhi/client/bindings.py (75.0%): Missing lines 500,516,519
-------------
Total:   12 lines
Missing: 3 lines
Coverage: 75%
-------------
```

**Comment by ralphbean** [comment]
> Am I reading this wrong?

I was.  I was reading it wrong.

```
❯ diff-cover coverage.xml --compare-branch=origin/develop --fail-under=100                                                  bodhi/git/1327 
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged, and unstaged changes
-------------
bodhi/client/bindings.py (100%)
-------------
Total:   10 lines
Missing: 0 lines
Coverage: 100%
-------------
```

:+1: here.

**Comment by cverna** [comment]
👍 too

**Pull request merged**
