### PR TITLE
Increase the size of an update alias.

### LINKED ISSUE #3779: bodhi update id is too long
While testing epel modules in stg bodhi, we hit a issue with the size of the update id is being larger than 32 char length

```
Builds : Unable to create update.  (raised as a result of Query-invoked autoflush; consider using a _autoflush block if this flush is occurring prematurely)
(psycopg2.DataError) value too long for type character varying(32)

[SQL: INSERT INTO updates (autokarma, autotime, stable_karma, stable_days, unstable_karma, requirements, require_bugs, require_testcases, display_name, notes, type, status, request, severity, suggest, locked, pushed, critpath, close_bugs, date_submitted, date_modified, date_approved, date_pushed, date_testing, date_stable, alias, release_id, user_id, test_gating_status, from_tag) VALUES (%(autokarma)s, %(autotime)s, %(stable_karma)s, %(stable_days)s, %(unstable_karma)s, %(requirements)s, %(require_bugs)s, %(require_testcases)s, %(display_name)s, %(notes)s, %(type)s, %(status)s, %(request)s, %(severity)s, %(suggest)s, %(locked)s, %(pushed)s, %(critpath)s, %(close_bugs)s, %(date_submitted)s, %(date_modified)s, %(date_approved)s, %(date_pushed)s, %(date_testing)s, %(date_stable)s, %(alias)s, %(release_id)s, %(user_id)s, %(test_gating_status)s, %(from_tag)s) RETURNING ]
[parameters: {'autokarma': True, 'autotime': True, 'stable_karma': 3, 'stable_days': 0, 'unstable_karma': -3, 'requirements': '', 'require_bugs': True, 'require_testcases': True, 'display_name': '', 'notes': 'Test', 'type': 'unspecified', 'status': 'pending', 'request': None, 'severity': 'unspecified', 'suggest': 'unspecified', 'locked': False, 'pushed': False, 'critpath': False, 'close_bugs': True, 'date_submitted': datetime.datetime(2019, 11, 18, 18, 48, 47, 928343), 'date_modified': None, 'date_approved': None, 'date_pushed': None, 'date_testing': None, 'date_stable': None, 'alias': 'FEDORA-EPEL-MODULAR-2019-a63119524e', 'release_id': 36, 'user_id': 2990, 'test_gating_status': None, 'from_tag': None}]
(Background on this error at: )
```

We can reduce the update id length by changing the release name but thats something I wont prefer since it will not look good. If its really hard to increase the length, then I guess we dont have an option to rename the release.

From irc chat with @cverna 

```
[13:50:43] <+mboddu> cverna: https://paste.centos.org/view/bf304431 - any idea about this?
[13:51:07] <+mboddu> Oh, background info, I am trying to create an update in stg to test epel8 modules
[13:51:13] <+mboddu> And I got that error
[13:51:52] <+mboddu> I remember there was a limit on the build name or the update name in bodhi, but I thought it got fixed when we introduced modularity
[14:05:44] <cverna> mboddu: looks like FEDORA-EPEL-MODULAR-2019-a63119524e is 35 char while the db accept only a 32 char size
[14:05:56] <cverna> (psycopg2.DataError) value too long for type character varying(32)
[14:06:34] <cverna> but I am not 100% sure could you create a bodhi ticket, so that we can look at it properly
[14:06:38] <+mboddu> cverna: Can we increase the size? I dont think we can reduce the size, unless we rename the release which might not look good
[14:06:46] <+mboddu> Sure
[14:06:54] »» +mboddu creates a ticket
```

Koji build that I am testing is - https://koji.stg.fedoraproject.org/koji/buildinfo?buildID=1230372

### PR DESCRIPTION
**Pull request by cverna**
Fixes #3779

Signed-off-by: Clement Verna <cverna@tutanota.com>

### CODE REVIEW

**Comment by cverna** [comment]
@abompard do you mind look at this I am not 100% sure of what I am doing here :-P

**Comment by abompard** [comment]
Looks correct, did you use the alembic migration autogeneration feature?

**Comment by abompard** [comment]
Please try to use [op.alter_column](https://alembic.sqlalchemy.org/en/latest/ops.html#alembic.operations.Operations.alter_column) instead of custom SQL to keep the migration as portable as possible.

**Comment by cverna** [comment]
> Please try to use [op.alter_column](https://alembic.sqlalchemy.org/en/latest/ops.html#alembic.operations.Operations.alter_column) instead of custom SQL to keep the migration as portable as possible.

Done :-)

**Review by abompard — APPROVED** [review]

**Pull request merged**
