### PR TITLE
Prepare for the upcoming 4.0.0 release.

### PR DESCRIPTION
**Pull request by bowlofeggs**
Signed-off-by: Randy Barlow <randy@electronsweatshop.com>

### CODE REVIEW

**Review by cverna — APPROVED** [review]
lgtm

**Comment by bowlofeggs** [comment]
While self-reviewing this pull request (and commenting on the referenced issues), I found that three of the cited changes were actually already cherry picked into 3.Y releases, so I'm applying this patch to drop those:

```
diff --git a/docs/user/release_notes.rst b/docs/user/release_notes.rst
index 44d95b98..1627cc12 100644
--- a/docs/user/release_notes.rst
+++ b/docs/user/release_notes.rst
@@ -108,7 +108,6 @@ Features
   (:issue:`969`).
 * All updates in a release are set to obsolete status when the release is archived (:issue:`2204`).
 * Bodhi will now comment on updates when their test gating status changes (:issue:`2210`).
-* The CLI can display waived test cases (:issue:`2267`).
 * ``bodhi-push`` now blocks composing retired releases (:issue:`2555`).
 * A new ``bodhi.messages`` Python package has been added as a convenience for Python consumers
   who wish to subscribe to Bodhi's messages (:issue:`2842`).
@@ -134,9 +133,6 @@ Features
 Bug fixes
 ^^^^^^^^^
 
-* ``bodhi-approve-testing`` now commits the transaction on each update in its loop
-  (:issue:`1016`).
-* The waive button is now shown when the update is locked (:issue:`2271`).
 * Since the ``active_releases`` query parameter was dropped, an issue causing strange pagination
   results is no longer present (:issue:`2316`).
 * Waiver details are now displayed in the web UI (:issue:`2365`).
```

I will apply that, rebase, and merge.

**Comment by bowlofeggs** [comment]
All tests pass with bci locally. Since this pull request changes the ```.mergify.yml``` file, Mergify will not merge it, so I will merge manually now.

**Comment by abitrolly** [comment]
Where is the new version? Release notes don't show anything.

https://bodhi.fedoraproject.org/docs/user/release_notes.html

**Comment by bowlofeggs** [comment]
@abitrolly Those are the production release notes - production is still 3.14.0. The 4.0.0 beta release notes are here:

https://bodhi.stg.fedoraproject.org/docs/user/release_notes.html

Bodhi 4.0.0 beta is built and deployed to staging:

https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release
https://bodhi.stg.fedoraproject.org/

**Comment by abitrolly** [comment]
Just what is needed. Thank you,

**Pull request merged**
