### PR TITLE
Test if the file repomd.xml exists rather than just dir repodata

### LINKED ISSUE #908: Work around missing repodata.xml
Sometimes the previous run of the Bodhi masher leaves some directories with missing repodata.xml files (See #887). That issue is about stopping that from happening in the future, but it is a bit mysterious and may take some time to identify its cause.

In the meantime, we can make Bodhi more robust. In subsequent runs of the masher, there is a test for the existence of the folder that should contain a repodata.xml file and if that folder is present Bodhi assumes that the file is present as well. This assumption is false, and it causes Bodhi to blow up later.

We should adjust that test to test for the existence of the file instead of the folder. This will make Bodhi more robust for releng, and should be a pretty easy change as well.

### PR DESCRIPTION
**Pull request by k3rn3l3rr0r**
(fixes #908)
Workaround candidate for #887

### CODE REVIEW

**Comment by sayanchowdhury** [comment]
:+1:  for me

**Comment by bowlofeggs** [comment]
This looks like the correct change to me, but we will want unit tests as well. Can you add a test that asserts that the presence of the file is being tested? Thanks!

**Comment by bowlofeggs** [comment]
@k3rn3l3rr0r Would you like me to write the needed tests for you? If you could rebase your commit to resolve the conflict, I'll take it from there if you want.

**Comment by bowlofeggs** [comment]
Hello @k3rn3l3rr0r, I wanted to give you a heads up that I'm going to fix this soon unless you still want to do it yourself.

**Comment by k3rn3l3rr0r** [comment]
Hi @bowlofeggs, I'm sorry that this is laying around for so long - I had to travel a lot in the last weeks and I was not able to reach my dev box. I will try to get rid of this until the end of this week, if you don't mind to wait for another few days.

**Comment by bowlofeggs** [comment]
@k3rn3l3rr0r No problem at all! I just wanted to make sure it was still on your radar. I'm not in a hurry.

**Comment by bowlofeggs** [comment]
Hello @k3rn3l3rr0r, do you still want to work on this?

**Comment by bowlofeggs** [comment]
I'm going to close this pull request for now since it hasn't had any activity in a while. Feel free to send a new one if you still want to work on this!

**Comment by bowlofeggs** [comment]
Hello @k3rn3l3rr0r! I'm working on writing tests for your patch. I've gone ahead and cherry-picked your commit into my branch and resolved its conflict (it still shows you as the author!):

https://github.com/bowlofeggs/bodhi/commit/92b78e775e6b80b65b1aeb62e36e19632ccc35b3

I will write a commit to test that patch on top of it and then I'll send a PR here. Thanks for your contribution!

**Comment by bowlofeggs** [comment]
This pull request contains your commit with conflict resolved, and my commit with a test:

https://github.com/fedora-infra/bodhi/pull/1147

**Pull request closed without merging**
