### PR TITLE
Don't upgrade packages when building containers for CI

### PR DESCRIPTION
**Pull request by abompard**
There's currently an update that breaks our CI containers, don't upgrade packages when building them.
Also, according to Clément, upgrading packages in containers is a bad practice.

### CODE REVIEW

**Review by cverna — APPROVED** [review]

**Comment by pypingou** [comment]
I propose we merge this one manually as it is supposed to fix the currently failing tests

**Comment by abompard** [comment]
Nah it's not fixing them actually, they still fail with the change. I wonder if it may be a real bug somewhere.

**Comment by ryanlerch** [comment]
is the test_results/ directory supposed to be included here?

**Comment by abompard** [comment]
> is the test_results/ directory supposed to be included here?

No, this PR is just a giant mess a the moment because I can't test locally. Please ignore for now. (also I added files I shouldn't have added)

**Pull request merged**
