### PR TITLE
Use assertRegex() instead of assertRegexpMatches().

### PR DESCRIPTION
**Pull request by bowlofeggs**
This fixes a few DeprecationWarnings.

Signed-off-by: Randy Barlow <randy@electronsweatshop.com>

### CODE REVIEW

**Comment by bowlofeggs** [comment]
Hmmm. It looks like Python 2 does not have ```assertRegex()```. I may just keep this PR around until Bodhi drops Python 2 support since that shouldn't be too long from now.

**Comment by bowlofeggs** [comment]
Eh, I'll just make myself a personal ToDo to come back to this later.

**Review by pypingou — APPROVED** [review]
Simple enough

**Review by Zlopez — APPROVED** [review]
LGTM

**Pull request merged**
