### PR TITLE
Prepare 2.6.0 release notes.

### PR DESCRIPTION
**Pull request by bowlofeggs**
Signed-off-by: Randy Barlow <randy@electronsweatshop.com>

### CODE REVIEW

**Review by jeremycline — APPROVED** [review]
:shipit:

**Comment by bowlofeggs** [comment]
@jeremycline I'd like to sneak one more change into these release notes:

```$ git diff
diff --git a/docs/release_notes.rst b/docs/release_notes.rst
index 3feb5f0..6b31d85 100644
--- a/docs/release_notes.rst
+++ b/docs/release_notes.rst
@@ -7,9 +7,12 @@ Release notes
 Special instructions
 ^^^^^^^^^^^^^^^^^^^^
 
-The database migrations have been trimmed in this release. To upgrade to this version of Bodhi
-from a version prior to 2.3, first upgrade to Bodhi 2.3, 2.4, or 2.5, run the database migrations,
-and then upgrade to this release.
+#. The database migrations have been trimmed in this release. To upgrade to this version of Bodhi
+   from a version prior to 2.3, first upgrade to Bodhi 2.3, 2.4, or 2.5, run the database
+   migrations, and then upgrade to this release.
+#. Bodhi cookies now expire, but cookies created before 2.6.0 will not automatically expire. To
+   expire all existing cookies so that only expiring tickets exist, you will need to change
+   ``authtkt.secret`` to a new value in your settings file.
 
 
 Dependency adjustments
@@ -49,6 +52,8 @@ Features
   (`62330644 <https://github.com/fedora-infra/bodhi/commit/62330644>`_).
 * openQA results are now displayed in the web ui
   (`450dbafe <https://github.com/fedora-infra/bodhi/commit/450dbafe>`_).
+* Bodhi cookies now expire. There is a new ``authtkt.timeout`` setting that sets Bodhi's session
+  lifetime, defaulting to 1 day.
 
 
 Bugs
```

**Comment by bowlofeggs** [comment]
The change is in reference to https://github.com/fedora-infra/bodhi/pull/1456

**Comment by jeremycline** [comment]
👍 so long as the change also sneaks in!

**Pull request merged**
