### PR TITLE
CI: allocate two nodes

### PR DESCRIPTION
**Pull request by abompard**
Spread the load over two Duffy nodes.

### CODE REVIEW

**Comment by abompard** [comment]
@bstinson here's the cico.pipeline file I'm trying to write. Thanks for your help!

**Comment by abompard** [comment]
@bstinsonmhk here's the cico.pipeline file I'm trying to write. Thanks for your help!

**Review by Zlopez — DISMISSED** [review]

**Comment by bowlofeggs** [comment]
@abompard do you still want to work on this? Are we waiting on @bstinsonmhk?

**Comment by abompard** [comment]
I'm still willing to work on it but I need additional permissions from @bstinsonmhk in Jenkins.

**Comment by bowlofeggs** [comment]
@abompard Maybe you can corner @bstinsonmhk this week and see if he can help us with this. Tell him he can't have any beer until this gets merged.

**Review by Zlopez — COMMENTED** [review]
This looks good, but I'm changing my review to comment till @bstinsonmhk will approve this

**Pull request closed without merging**
