### PR TITLE
Display expired_date for an override.

### LINKED ISSUE #2136: Please show BRO expired_date in the UI
It would be very helpful to be able to view the expired_date for a buildroot override in the web UI.

### PR DESCRIPTION
**Pull request by ghost**
fixes #2136

Signed-off-by: Vismay Golwala <vgolwala@redhat.com>

### CODE REVIEW

**Comment by ghost** [comment]
jenkies test

**Comment by ghost** [comment]
jenkies test

**Comment by ghost** [comment]
jenkies test

**Review by bowlofeggs — APPROVED** [review]
Thanks!

**Pull request merged**
