### PR TITLE
Add a bresetdb command to get the db so fresh and so clean.

### PR DESCRIPTION
**Pull request by bowlofeggs**
Signed-off-by: Randy Barlow <randy@electronsweatshop.com>

### CODE REVIEW

**Comment by pypingou** [comment]
Cool :+1:

**Comment by pypingou** [comment]
Cool :+1:

**Review by ralphbean — APPROVED** [review]
Nice.  :)

**Comment by ralphbean** [comment]
Ooop - conflicts here now.  @bowlofeggs can you rebase?

**Review by ralphbean — APPROVED** [review]

**Pull request merged**
