### PR TITLE
Don't comment on or modify Security Response bugs for updates in testing

### PR DESCRIPTION
**Pull request by lmacken**
This resolves part of issue #368

### CODE REVIEW

**Comment by ralphbean** [comment]
Looks reasonable for now, but I like the more explicit logic in the [bodhi1 code](https://github.com/fedora-infra/bodhi/blob/develop/bodhi/models/models.py#L1115-L1146) that checks ``if self.type is UpdateType.security`` first.

**Comment by lmacken** [comment]
Updated to address your concern, as well as thoger's request to not bother ever closing parent bugs.

**Comment by ralphbean** [comment]
LGTM!

**Comment by lmacken** [comment]
A couple more changes to review plz ;)

**Comment by ralphbean** [comment]
Nice, 746f68638 looks good.

**Comment by lmacken** [comment]
Thanks for the reviews!

**Pull request merged**
