### PR TITLE
Switch docker registry to registry.fedoraproject.org

### LINKED ISSUE #4158: Integration tests fail when using pip as the tagrged
When running tests, they fail with message:
```
 FAILED: Path doesn't exist: '/usr/local/lib/python3.9/site-packages/bodhi-5.5-py3.9.egg/bodhi/server/migrations'.  Please use the 'init' command to create a new scripts folder.
```

The path it should be looking for it '/usr/local/lib/python3.9/site-packages/bodhi_server-5.5-py3.9.egg/bodhi/server/migrations'

### PR DESCRIPTION
**Pull request by mattiaverga**
Signed-off-by: Mattia Verga <mattia.verga@tiscali.it>

### CODE REVIEW

**Review by pypingou — APPROVED** [review]

**Comment by mattiaverga** [comment]
@Mergifyio refresh

**Comment by mattiaverga** [comment]
It needs an admin to disable f33-integration test to pass in github branch protection settings

**Comment by pypingou** [comment]
or I go ahead and merge it manually, what do you think?

**Comment by mattiaverga** [comment]
> or I go ahead and merge it manually, what do you think?

It's a good solution for this PR, but future PRs will always fail to be merged if that test fail.
It took some time to me to figure out why mergify won't merge this PR even if its config doesn't list `f33-integration` as required...

**Comment by cverna** [comment]
> > or I go ahead and merge it manually, what do you think?
> 
> It's a good solution for this PR, but future PRs will always fail to be merged if that test fail.
> It took some time to me to figure out why mergify won't merge this PR even if its config doesn't list `f33-integration` as required...

made the change.

**Pull request merged**
