### PR TITLE
Move the type icons to the left of the update titles so they align.

### PR DESCRIPTION
**Pull request by bowlofeggs**
Signed-off-by: Randy Barlow <randy@electronsweatshop.com>

### CODE REVIEW

**Comment by pypingou** [comment]
👍 for me though a screenshot would be nice :)

**Comment by ryanlerch** [comment]
I like this idea, but i noticed that you opened issue #1506 about this.

There is a font-awesome class "fa-fw" to make the icons fixed width, for example:

```
<i class="fa fa-fw fa-shield"></i>
```

**Comment by ryanlerch** [comment]
@pypingou FWIW, issue #1506 has a screenshot of how the icons look on the left...

**Comment by pypingou** [comment]
Still looks fine to me

**Comment by bowlofeggs** [comment]
@ryanlerch Thanks for the tip! I've applied that change in a second commit (since it's a distinct change I decided to keep it atomic).

@pypingou here is a screenshot of what it looks like with both commits applied:

delme1

**Comment by pypingou** [comment]
Cool, looks good to me

**Pull request merged**
