### PR TITLE
Rename development.ini to development.ini.example.

### PR DESCRIPTION
**Pull request by bowlofeggs**
Since developers will regularly make changes to development.ini,
this commit renames the file to have a .example extension. This
allows developers to make any changes they like to the file without
accidentally having it be picked up by git commit -a.

### CODE REVIEW

**Comment by bowlofeggs** [comment]
I also filed this pull request for the Vagrantfile to be able to work with this:

https://pagure.io/fedora-apps-vagrantfiles/pull-request/2

Ideally, we'd merge these relatively close in time.

**Comment by pypingou** [comment]
Big :+1: for me on this

**Comment by lmacken** [comment]
Looks good to me, thanks! Merging this before the other PR, since it shouldn't adversely affect anything here.

**Comment by trishnaguha** [comment]
Awesome @bowlofeggs :+1: Working perfectly!

**Pull request merged**
