### PR TITLE
Correctly handle ConnectionResetError in the Composer.

### LINKED ISSUE #2850: ConnectionResetError in _wait_for_sync()
# Workaround

This exception is raised in the code that checks to see if the compose has been synchronized with the mirrors yet, so it is safe to simply resume the compose if this happens.

# The problem

Today several of the Bodhi composes failed in [```_wait_for_sync()```](https://github.com/fedora-infra/bodhi/blob/3.11.3/bodhi/server/consumers/masher.py#L1290-L1344):

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/bodhi/server/consumers/masher.py", line 344, in run
    self.work()
  File "/usr/lib/python3.7/site-packages/bodhi/server/consumers/masher.py", line 415, in work
    self._compose_updates()
  File "/usr/lib/python3.7/site-packages/bodhi/server/consumers/masher.py", line 964, in _compose_updates
    self._wait_for_sync()
  File "/usr/lib/python3.7/site-packages/bodhi/server/consumers/masher.py", line 1327, in _wait_for_sync
    masterrepomd = urllib2.urlopen(master_repomd_url)
  File "/usr/lib64/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/lib64/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.7/urllib/request.py", line 1345, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib64/python3.7/urllib/request.py", line 1320, in do_open
    r = h.getresponse()
  File "/usr/lib64/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/usr/lib64/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.7/http/client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib64/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
```

This seems like just another new ```Exception``` type that can be raised in Python 3 that wasn't raised in Python 2, similar to https://github.com/fedora-infra/bodhi/issues/2758.

### PR DESCRIPTION
**Pull request by sebwoj**
Fixes #2850

Signed-off-by: Sebastian Wojciechowski <s.wojciechowski89@gmail.com>

### CODE REVIEW

**Comment by bowlofeggs** [comment]
The test failures are due to ```ConnectionResetError``` not existing in Python 2. However, I have #2871 open which drops support for Python 2, so we can just rebase this once that's merged and it'll be fine. Thanks!

**Review by bowlofeggs — APPROVED** [review]

**Comment by sebwoj** [comment]
Yes, I forgot to mention about py2 fails, but if we are about to drop py2 support I leaved this PR without fixing. Im not sure if we can insert this to develop, because tests will be faiiling. My intention was to wait for #2871 :)

**Comment by bowlofeggs** [comment]
On Thu, 2019-01-03 at 12:20 -0800, Sebastian Wojciechowski wrote:
> if we are about to drop py2 support I leaved this PR without fixing.

Yeah, let's wait for #2871. Thanks!

**Comment by bowlofeggs** [comment]
#2871 is merged now, so we should be able to rebase this one and get it to pass tests.

**Comment by bowlofeggs** [comment]
I'm going to re-rebase this one since it looks like CI failed to run.

**Review by bowlofeggs — APPROVED** [review]
Thanks!

**Comment by bowlofeggs** [comment]
This patch is planned for inclusion in the upcoming 4.0.0 release: #3221

**Comment by bowlofeggs** [comment]
Bodhi 4.0.0 beta is built and deployed to staging:

https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release
https://bodhi.stg.fedoraproject.org/

**Pull request merged**
