### PR TITLE
Bugfix:  keep the "type" set when editing an update.

### LINKED ISSUE #349: On update edit the "type" is lost
When "edit" a submitted update, the Type is lost, need to be check again.

Notice: the error message is not really clear: "required"

### PR DESCRIPTION
**Pull request by ralphbean**
Looks like a typo.  This should fix #349.

### CODE REVIEW

**Comment by pypingou** [comment]
Looks safe to me (but I don't know bodhi's sources that well)

**Comment by ralphbean** [comment]
That type is an instance of the [UpdateType](https://github.com/fedora-infra/bodhi/blob/develop/bodhi/models/models.py#L202-L206) object which gets its behavior from [this class](https://github.com/fedora-infra/bodhi/blob/develop/bodhi/models/enum.py#L22-L46).

**Comment by ralphbean** [comment]
On the other hand, now that I look more closely, this may not actually fix the bug:

```
>>> bodhi.models.UpdateType().security.description
'security'
>>> bodhi.models.UpdateType().security.value
'security'
```

**Comment by ralphbean** [comment]
OK, it works locally with this.

**Comment by pypingou** [comment]
Still ok for me (with the same limitation as before)

**Comment by lmacken** [comment]
Hmm, I don't see how this changes anything. `description` and `value` are the same, and we use `description` all over the place still...

**Pull request closed without merging**
