### PR TITLE
Run the CI tests against a container with dependencies from PyPI where possible

### PR DESCRIPTION
**Pull request by bowlofeggs**

### CODE REVIEW

**Comment by bowlofeggs** [comment]
Strange - it seems like the ssh connection to the Jenkins slave was lost. Re-running.

**Comment by bowlofeggs** [comment]
jenkies test

**Comment by bowlofeggs** [comment]
It seems that dnf is unable to get the transaction lock on the rawhide pip container for some reason:

```
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
[91mFailed to obtain the transaction lock (logged in as: root).
[0mThe downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
[91mError: Could not run transaction.
[0mThe command '/bin/sh -c dnf install -y     git     liberation-mono-fonts     packagedb-cli     python2-cornice-sphinx     python2-createrepo_c     python2-koji     python2-librepo     createrepo_c     gcc     graphviz     python2-devel     redhat-rpm-config' returned a non-zero code: 1
```

**Comment by bowlofeggs** [comment]
jenkies test

**Review by jeremycline — APPROVED** [review]
All these cats make my head spin

:shipit:

**Comment by bowlofeggs** [comment]
@jeremycline :cat2:

**Pull request merged**
