### PR TITLE
Include license file in bodhi-client sdist

### PR DESCRIPTION
**Pull request by gotmax23**

### CODE REVIEW

**Comment by gotmax23** [comment]
I can't sign off on anything if you don't define what signing off actually means. You should e.g., include a copy of the DCO in the project root and put in the README or a CONTRIBUTING doc that contributors need to sign off on their commits.

**Review by LenkaSeg — APPROVED** [review]
LGTM, thank you!

**Comment by LenkaSeg** [comment]
> 

If you click on the DCO check, github provides an assistance with how to sign-off the commits. It this case, it would be:
```
Ensure you have a local copy of your branch by [checking out the pull request locally via command line](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally).
    In your local branch, run: git rebase HEAD~1 --signoff
    Force push your changes to overwrite the branch: git push --force-with-lease origin include_licenses
```

**Comment by gotmax23** [comment]
I know *how* to sign off on commits. The problem is, the project hasn't defined that `Signed-off-by:` constitutes agreeing to the DCO. Once that is put in writing, I'll sign off.

**Comment by gotmax23** [comment]
See e.g. https://pagure.io/fedora-infra/rpmautospec/issue/220 and https://pagure.io/fedora-infra/rpmautospec/c/18bd285b28a1d57526d990d609a08beaa2e8012d?branch=main for the fix.

**Comment by gotmax23** [comment]
Hmm, it seems like this is already written in https://fedora-infra.github.io/bodhi/6.0/developer/index.html . It should probably be somewhere more conspicuous, but I'll sign off on the commit when I get back to my laptop.

**Comment by LenkaSeg** [comment]
> Hmm, it seems like this is already written in https://fedora-infra.github.io/bodhi/6.0/developer/index.html . It should probably be somewhere more conspicuous, but I'll sign off on the commit when I get back to my laptop.

Thanks for the links and suggestions. It would sure not hurt to have the DCO document part of the repo, as it is in rpmautospec.

**Pull request merged**
