### PR TITLE
Display waiver details in ui

### LINKED ISSUE #2365: [S/M] The waiver hoverovers in the web UI do not say what the name of the waived test was
If I hover over the cloud icons on an update that has waivers, it tells me the waiver number (not particularly useful) and the comment the person submitted with their waiver (useful). It does not tell me which test was waived and that would be useful to know.

screenshot from 2018-05-08 15-43-07

### PR DESCRIPTION
**Pull request by sebwoj**
fix #2365

Signed-off-by: Sebastian Wojciechowski <s.wojciechowski89@gmail.com>

### CODE REVIEW

**Comment by bowlofeggs** [comment]
Hey @sebwoj - do you know of an update that has waivers to test this with?

**Comment by sebwoj** [comment]
To find update with waived TC, just paste builds 
from:
https://waiverdb-web-waiverdb.app.os.fedoraproject.org/api/v1.0/waivers/
to:
https://bodhi.fedoraproject.org/updates/?builds=qclib-1.3.1-3.fc28

Examples:
https://bodhi.fedoraproject.org/updates/FEDORA-2018-03747e0c21
https://bodhi.fedoraproject.org/updates/FEDORA-2018-200708ae05
https://bodhi.fedoraproject.org/updates/FEDORA-2018-6c548e5917

**Review by bowlofeggs — APPROVED** [review]
Thanks!

**Comment by bowlofeggs** [comment]
This patch is planned for inclusion in the upcoming 4.0.0 release: #3221

**Comment by bowlofeggs** [comment]
Bodhi 4.0.0 beta is built and deployed to staging:

https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release
https://bodhi.stg.fedoraproject.org/

**Pull request merged**
