### PR TITLE
Fixes #1304 calls clean_up after mash is done

### LINKED ISSUE #1304: The masher should clean up old mashes at the end of every run
Bodhi 2.4.0 introduced a new CLI tool called ```bodhi-clean-old-mashes``` that deletes all but the 10 newest mashes. I had intended the script to be used in cron, but after talking with releng today about enabling it they suggested it would be nice if the masher called it automatically after each successful push to the mirrors. It's a good idea, so let's do it!

All we'll need to do is have the masher import and use the [```clean_up```](https://github.com/fedora-infra/bodhi/blob/2.4.0/bodhi/server/scripts/clean_old_mashes.py#L32) function when it completes a successful mash. I believe the print statements will be OK as they should just end up going to journald with the other log messages.

### PR DESCRIPTION
**Pull request by kushaldas**
Also have assert statement to make sure that clean_up is called.

### CODE REVIEW

**Comment by ryanlerch** [comment]
jenkies test

**Comment by kushaldas** [comment]
Broke too many things :( Have to fix my testing environment first.

**Review by bowlofeggs — CHANGES_REQUESTED** [review]
Can you adjust your commit message so that "fixes #1304" is on its own line? That way GitHub will automatically close the issue when this is merged. Something like this would do:

```
Call clean_up() after mash is done.

fixes #1304
```

**Comment by bowlofeggs** [comment]
@kushaldas Do you still wish to work on this?

**Comment by bowlofeggs** [comment]
I'm going to close this for now due to inactivity. Feel free to reopen if you do still want to work on this!

**Pull request closed without merging**
