### PR TITLE
Makes search case-insensitive.

### LINKED ISSUE #997: search should be case-insensitive
searching for "wxgtk3", for example, produces no results. the search should be case-insensitive, in line with user expectations about most search results.

### PR DESCRIPTION
**Pull request by nbianca**
Fixes #997.

Signed-off-by: Bianca Nenciu <nenciu.bianca@gmail.com>

### CODE REVIEW

**Comment by pypingou** [comment]
Looks fine to me, do we want to add some tests for this?

**Review by bowlofeggs — CHANGES_REQUESTED** [review]
This doesn't seem to address the example search given in #997. This URL doesn't return any results:

http://localhost:6543/updates/?packages=wxgtx3

Whereas this one does:

http://localhost:6543/updates/?packages=wxGTK3

Additionally, the search box at the top of the page also searches updates, usernames, and buildroot overrides in addition to packages. It would be good to make those case-insensitive as well.

**Comment by bowlofeggs** [comment]
Do you still wish to work on this pull request?

**Comment by bowlofeggs** [comment]
Closing due to inactivity.

**Pull request closed without merging**
