### PR TITLE
Changed package search to case-insensitive

### PR DESCRIPTION
**Pull request by lalitkr**
@bowlofeggs Please check and review this.

### CODE REVIEW

**Review by bowlofeggs — CHANGES_REQUESTED** [review]
Hello @lalitkr! This seems like the correct approach to me, but we will need at least two changes:

1. Squash your commits so there is only one.
2. Add a "fixes #997" into your commit message, so the ticket and the commit get linked (and the issue will also autoclosed when this gets merged).
3. Write a couple of tests that demonstrate that the search works with varying cases in the search. For example, maybe one test that searches for "bodhi" and another test searches for "BoDHi".

Thanks for the contribution!

**Comment by lalitkr** [comment]
Hi @bowlofeggs,
Thank you for your feedback. Will work on the same and update it once done.

**Comment by bowlofeggs** [comment]
Hello @lalitkr! Do you still intend to work on this pull request?

**Comment by bowlofeggs** [comment]
I'm going to close this for now, but feel free to reopen if you still want to work on it!

**Pull request closed without merging**
