### PR TITLE
Added /monitoring endpoint to be used with prometheus

### PR DESCRIPTION
**Pull request by AdamSaleh**
Added /monitoring endpoint to be used with prometheus, alongside with metrics for responses.

### CODE REVIEW

**Comment by cverna** [comment]
We need to have some test to cover the new code :smile:

**Comment by cverna** [comment]
@AdamSaleh are you still interested to work on this PR ? otherwise I will just close it

**Comment by AdamSaleh** [comment]
I am, was looking at it yesterday, but rebasing seems like pita, so I will just create a new PR once I am back from vacation :)

**Comment by cverna** [comment]
> I am, was looking at it yesterday, but rebasing seems like pita, so I will just create a new PR once I am back from vacation :)

Cool so I ll close this PR and you can open a new one after your vacation. Enjoy :smile:

**Pull request closed without merging**
