### PR TITLE
Measure branch coverage.

### PR DESCRIPTION
**Pull request by bowlofeggs**
Though Bodhi currently has 99% line test coverage, there are some
branch paths that are not currently covered, so this commit also
reduces the required coverage percentage to 98%.

Signed-off-by: Randy Barlow <randy@electronsweatshop.com>

### CODE REVIEW

**Review by cverna — DISMISSED** [review]

**Comment by pypingou** [comment]
The jenkins error is... interesting:
````f28	FAIL Required test coverage of 98% not reached. Total coverage: 98.00%````

**Comment by bowlofeggs** [comment]
Yeah that is a strange error. It seemed to pass locally when I created this patch. I'll have a look later to see if I can figure out what's going on.

**Comment by bowlofeggs** [comment]
I wonder if it's a matter of significant digits or something. When I run the tests locally, I see a slightly different output about it having 98.01% instead of 98.00%, and it passes. I wonder if I just set it to 97% if that'll get it working…

**Comment by bowlofeggs** [comment]
Note that the goal is that I'll slowly work to raise it to 100%, but this PR is just about switching the measurement of branch coverage on, so IMO if it passes with it set to 97% so be it.

**Comment by bowlofeggs** [comment]
Yeah it's happy with 97%, so I bet it's like 97.999% or something and so setting it to 98 fails.

I don't intend to merge this PR until after I submit one more to get 100% line coverage. I probably won't have time to do that for a month or so, so this PR might just sit for a while.

**Comment by bowlofeggs** [comment]
Once https://github.com/fedora-infra/bodhi/pull/2493 is merged I will rebase this one and get it passing.

**Comment by bowlofeggs** [comment]
This PR passes CI now and is ready for review.

**Comment by bowlofeggs** [comment]
I believe @puiterwijk put the no-mergify label on this due to my comment about how I didn't intend to merge it until my other PR is merged. Since that PR is now merged, I will remove the no-mergify label.

**Comment by pypingou** [comment]
Still :+1: for me

**Review by puiterwijk — DISMISSED** [review]

**Review by puiterwijk — APPROVED** [review]

**Pull request merged**
