### PR TITLE
Add cli bodhi releases list subcommand

### PR DESCRIPTION
**Pull request by sebwoj**
Fix for #2536

### CODE REVIEW

**Review by Zlopez — DISMISSED** [review]

**Comment by bowlofeggs** [comment]
jenkies test

**Comment by bowlofeggs** [comment]
jenkies test

**Comment by bowlofeggs** [comment]
@centos-ci add to whitelist

**Review by bowlofeggs — CHANGES_REQUESTED** [review]
There are some [```flake8``` errors](https://ci.centos.org/job/bodhi-bodhi-flake8-f28/93/console) to fix before this can be merged:

```
./bodhi/client/__init__.py:1045:1: E302 expected 2 blank lines, found 1
@releases.command(name='list')
^

./bodhi/client/__init__.py:1064:1: E302 expected 2 blank lines, found 1
def save(client, **kwargs):
^

./bodhi/client/__init__.py:1082:1: E302 expected 2 blank lines, found 1
def print_releases_list(releases, display_archived):
^

./bodhi/client/__init__.py:1107:1: E302 expected 2 blank lines, found 1
def print_release(release):
^

./bodhi/tests/client/__init__.py:898:101: E501 line too long (526 > 100 characters)
    Munch({u'composes': [], u'dist_tag': u'f26', u'name': u'F26', u'testing_tag': u'f26-updates-testing', u'pending_stable_tag': u'f26-updates-pending', u'mail_template': u'fedora_errata_template', u'long_name': u'Fedora 26', u'state': u'archived', u'version': u'26', u'id_prefix': u'FEDORA', u'branch': u'f26', u'pending_signing_tag': u'f26-signing-pending', u'pending_testing_tag': u'f26-updates-testing-pending', u'candidate_tag': u'f26-updates-candidate', u'stable_tag': u'f26-updates', u'override_tag': u'f26-override'}),
                                                                                                    ^

./bodhi/tests/client/__init__.py:899:101: E501 line too long (525 > 100 characters)
    Munch({u'composes': [], u'dist_tag': u'f28', u'name': u'F28', u'testing_tag': u'f28-updates-testing', u'pending_stable_tag': u'f28-updates-pending', u'mail_template': u'fedora_errata_template', u'long_name': u'Fedora 28', u'state': u'current', u'version': u'28', u'id_prefix': u'FEDORA', u'branch': u'f28', u'pending_signing_tag': u'f28-signing-pending', u'pending_testing_tag': u'f28-updates-testing-pending', u'candidate_tag': u'f28-updates-candidate', u'stable_tag': u'f28-updates', u'override_tag': u'f28-override'}),
                                                                                                    ^

./bodhi/tests/client/__init__.py:900:101: E501 line too long (525 > 100 characters)
    Munch({u'composes': [], u'dist_tag': u'f29', u'name': u'F29', u'testing_tag': u'f29-updates-testing', u'pending_stable_tag': u'f29-updates-pending', u'mail_template': u'fedora_errata_template', u'long_name': u'Fedora 29', u'state': u'pending', u'version': u'29', u'id_prefix': u'FEDORA', u'branch': u'f29', u'pending_signing_tag': u'f29-signing-pending', u'pending_testing_tag': u'f29-updates-testing-pending', u'candidate_tag': u'f29-updates-candidate', u'stable_tag': u'f29-updates', u'override_tag': u'f29-override'}),
                                                                                                    ^

./bodhi/tests/client/__init__.py:901:5: E123 closing bracket does not match indentation of opening bracket's line
    ]
    ^

./bodhi/tests/client/test___init__.py:1889:82: E502 the backslash is redundant between brackets
                         client_test_data.EXPECTED_PENDING_RELEASES_LIST_OUTPUT +\
                                                                                 ^

./bodhi/tests/client/test___init__.py:1890:30: E225 missing whitespace around operator
                         '\n'+\
                             ^

./bodhi/tests/client/test___init__.py:1890:31: E502 the backslash is redundant between brackets
                         '\n'+\
                              ^

./bodhi/tests/client/test___init__.py:1892:9: E124 closing bracket does not match visual indentation
        )
        ^

./bodhi/tests/client/test___init__.py:1908:101: E501 line too long (110 > 100 characters)
        result = runner.invoke(client.list_releases, ['--url', 'http://localhost:6543', '--display-archived'])
                                                                                                    ^

./bodhi/tests/client/test___init__.py:1912:82: E502 the backslash is redundant between brackets
                         client_test_data.EXPECTED_PENDING_RELEASES_LIST_OUTPUT +\
                                                                                 ^

./bodhi/tests/client/test___init__.py:1913:30: E225 missing whitespace around operator
                         '\n'+\
                             ^

./bodhi/tests/client/test___init__.py:1913:31: E502 the backslash is redundant between brackets
                         '\n'+\
                              ^

./bodhi/tests/client/test___init__.py:1914:83: E502 the backslash is redundant between brackets
                         client_test_data.EXPECTED_ARCHIVED_RELEASES_LIST_OUTPUT +\
                                                                                  ^

./bodhi/tests/client/test___init__.py:1915:30: E225 missing whitespace around operator
                         '\n'+\
                             ^

./bodhi/tests/client/test___init__.py:1915:31: E502 the backslash is redundant between brackets
                         '\n'+\
                              ^

./bodhi/tests/client/test___init__.py:1917:9: E124 closing bracket does not match visual indentation
        )
        ^

./bodhi/tests/client/test___init__.py:1938:1: W293 blank line contains whitespace
^

./bodhi/tests/client/test___init__.py:1941:1: E303 too many blank lines (3)
class TestHandleErrors(unittest.TestCase):
^
```

**Comment by bowlofeggs** [comment]
Looks good! I'm going to squash these commits and mark for Mergify.

**Review by bowlofeggs — APPROVED** [review]

**Pull request merged**
