### PR TITLE
Document where the service job can be viewed

### PR DESCRIPTION
**Pull request by bowlofeggs**
Signed-off-by: Randy Barlow <randy@electronsweatshop.com>

### CODE REVIEW

**Review by puiterwijk — APPROVED** [review]
Thanks for the documentation :).

**Comment by bowlofeggs** [comment]
jenkies test

**Comment by bowlofeggs** [comment]
jenkies test

**Comment by bowlofeggs** [comment]
jenkies test

**Review by Zlopez — APPROVED** [review]

**Comment by bowlofeggs** [comment]
```devel/ci/githubprb-project.yml``` has been deleted now that we are using the Jenkies Pipeline, so I will close this PR.

**Pull request closed without merging**
