### PR TITLE
add NVRs to email titles

### LINKED ISSUE #1635: Put versions back into e-mail subjects
In https://github.com/fedora-infra/bodhi/pull/1561 we made it so update e-mail subjects use the new beautify title code (which is very nice), but inadvertently we also stopped including version info on the packages and now only list the package names. It has been requested that we bring back the versions into e-mail subjects, so we should modify the new beautify title to have an ```nvr``` flag (defaulting to ```False```) that includes the ```nvr``` of the Build if ```True```, and uses the current behavior if ```False```.

### PR DESCRIPTION
**Pull request by ryanlerch**
Fixes #1635

### CODE REVIEW

**Comment by ryanlerch** [comment]
rebased to include the recent commit fixing the DNF import issue that was causing the CI to fail

**Review by bowlofeggs — APPROVED** [review]
I approve of your patch, but I wanted to add tests to it. Since there wasn't a test module to testing ```mail.py``` yet, I figured I'd help and and get that started too.

If you approve of my test patch, feel free to merge!

**Comment by bowlofeggs** [comment]
Hmm, it seems there was a failure to resolve hostnames in the CI system. jenkies test

**Comment by bowlofeggs** [comment]
jenkies test

**Comment by bowlofeggs** [comment]
jenkies test

**Comment by bowlofeggs** [comment]
@ryanlerch The tests pass now, so if you review my patch and approve of it feel free to merge this PR! (I added a commit on top of yours in your branch, so my commit is in this PR now too.)

**Comment by ryanlerch** [comment]
thanks @bowlofeggs

**Pull request merged**
