### PR TITLE
Do not run the integration tests in parallel.

### PR DESCRIPTION
**Pull request by bowlofeggs**
Signed-off-by: Randy Barlow <randy@electronsweatshop.com>

### CODE REVIEW

**Review by Zlopez — DISMISSED** [review]
:+1:

**Review by cverna — DISMISSED** [review]

**Comment by bowlofeggs** [comment]
I've added two more commits to address some missing dependencies for CI in the pip and f28 containers.

**Comment by cverna** [comment]
+1 to the 2 new commits

**Comment by bowlofeggs** [comment]
I've added three more commits to this, in the hopes that the collection of all of these will get CI working again. Two are modified versions of commits I cherry-picked from other PRs, and the third gets pip installed using an RPM.

**Review by puiterwijk — APPROVED** [review]

**Pull request merged**
