### PR TITLE
Correct grammar on two debug log statements.

### PR DESCRIPTION
**Pull request by bowlofeggs**
Signed-off-by: Randy Barlow <randy@electronsweatshop.com>

### CODE REVIEW

**Review by cverna — APPROVED** [review]
:+1:

**Review by cverna — DISMISSED** [review]
Lol I already approved these, but it seems that the CI is stuck

**Review by Zlopez — DISMISSED** [review]

**Comment by bowlofeggs** [comment]
jenkies test

**Comment by puiterwijk** [comment]
jenkies test

**Comment by bowlofeggs** [comment]
jenkies test

**Review by puiterwijk — APPROVED** [review]
pre-acked

**Pull request merged**
