### PR TITLE
Cornice querystring validator + functional tests

### PR DESCRIPTION
**Pull request by frenzymadness**
There was a bug in previous query string validator which causes that default value for some params was None in Python 3. I tried to fix it but then I found a comment about PR in cornice project with query string validator change so I decided to switch to that version and now it works with both Pythons.

### CODE REVIEW

**Comment by frenzymadness** [comment]
It seems that tests failed but not because of tests itself.

**Comment by bowlofeggs** [comment]
Cool, I've been meaning to do this :)

We should alter ```requirements.txt``` to state ```cornice == 3.1.0```, as that code was introduced in that release. Bodhi has a [problem](https://github.com/fedora-infra/bodhi/issues/2258) with Cornice 3.2.0 so for now we should just require exactly that release.

**Comment by bowlofeggs** [comment]
It seems that the docs fail to build due to a failure to import that validator:

```
f28	Exception occurred:
f28	  File "/bodhi/bodhi/server/services/builds.py", line 23, in <module>
f28	    from cornice.validators import colander_querystring_validator
f28	ImportError: cannot import name colander_querystring_validator
```

**Comment by bowlofeggs** [comment]
Ah I see the problem - Fedora still has Cornice 3.0.0, which doesn't have that validator:

https://apps.fedoraproject.org/packages/python-cornice

We will need to update F28+ to 3.1.0 before we can merge this PR. It is a backwards compatible release, and in fact only has this change:

https://github.com/Cornices/cornice/blob/3.1.0/CHANGES.txt

**Comment by bowlofeggs** [comment]
Here is a BZ about updating Cornice: https://bugzilla.redhat.com/show_bug.cgi?id=1543660

**Comment by bowlofeggs** [comment]
I've updated Rawhide to 3.1.0, and there's an update for F28 in progress:

https://bodhi.fedoraproject.org/updates/FEDORA-2018-c2b59b9114

Once that is stable, this PR should pass CI I think.

**Comment by frenzymadness** [comment]
`python-cornice` 3.1.0 is in stable and available in repos so I'll rerun CI and we'll see.

**Comment by frenzymadness** [comment]
jenkies test

**Comment by frenzymadness** [comment]
It works!

**Comment by frenzymadness** [comment]
Hi. Is there any issue with the PR?

**Comment by frenzymadness** [comment]
Ping ... :)

**Review by bowlofeggs — APPROVED** [review]
I'm going to merge this as-is, but we do want to update the requirements and release notes so they specify that cornice >= 3.1.0 is required. I'll do that in a separate PR.

**Comment by bowlofeggs** [comment]
Sorry for taking so long to respond. Things have been on $FIRE for the past several months :(

**Comment by bowlofeggs** [comment]
These patches are planned to be included in the upcoming 3.9.0 release: #2477.

**Comment by bowlofeggs** [comment]
These patches are planned to be included in the upcoming 3.9.0 release: #2477.

**Comment by bowlofeggs** [comment]
These patches were deployed to Fedora's production Bodhi instance yesterday.

**Pull request merged**
