### PR TITLE
Add support for composing containers.

### LINKED ISSUE #2028: Add support for containers to the masher
We need the masher to be able to promote containers into testing and stable. We will probably use skopeo for this.

Depends on #2027.

### PR DESCRIPTION
**Pull request by bowlofeggs**
fixes #2028

Signed-off-by: Randy Barlow <randy@electronsweatshop.com>

### CODE REVIEW

**Comment by bowlofeggs** [comment]
This is currently blocked on https://github.com/fedora-infra/bodhi/issues/2216

**Comment by bowlofeggs** [comment]
I've now got container composing functioning!

```
# After pushing the update to testing

[vagrant@bodhi-dev bodhi]$ http http://localhost:5000/v2/f27/s2i-core/tags/list
HTTP/1.1 200 OK
Content-Length: 67
Content-Type: application/json; charset=utf-8
Date: Fri, 16 Mar 2018 17:36:37 GMT
Docker-Distribution-Api-Version: registry/2.0
X-Content-Type-Options: nosniff

{
    "name": "f27/s2i-core",
    "tags": [
        "0-13.f27container",
        "0",
        "testing"
    ]
}


# After pushing the update to stable

[vagrant@bodhi-dev bodhi]$ http http://localhost:5000/v2/f27/s2i-core/tags/list
HTTP/1.1 200 OK
Content-Length: 76
Content-Type: application/json; charset=utf-8
Date: Fri, 16 Mar 2018 17:40:25 GMT
Docker-Distribution-Api-Version: registry/2.0
X-Content-Type-Options: nosniff

{
    "name": "f27/s2i-core",
    "tags": [
        "0-13.f27container",
        "0",
        "latest",
        "testing"
    ]
}
```

Now I just need to clean up the patch and write tests. Boom.

**Comment by pypingou** [comment]
Code wise I'm not seeing anything surprising, but I'm not sure I'm the best person to review this.

**Review by cverna — APPROVED** [review]
LGTM

**Pull request merged**
