### PR TITLE
Make 'display_name' optional in template

### PR DESCRIPTION
**Pull request by onosek**
Bodhi version 4.1.0-3 makes this parameter mandatory and it breaks
backward compatibility for fedpkg, which uses older versions of bodhi.

Issue: https://github.com/fedora-infra/bodhi/issues/3470
Fixes: rhbz#1737426

Signed-off-by: Ondrej Nosek <onosek@redhat.com>

### CODE REVIEW

**Comment by onosek** [comment]
@pypingou, @ryanlerch, @cverna, @bowlofeggs 
Guys, who can I ask for help with this? I "randomly" selected some names from recent PRs. I am not familiar with Bodhi code and I tried to suggest the solution for #3470, but so far I have no response.
Thanks.

**Comment by pypingou** [comment]
@onosek a number of us are AFK this week, sorry for the bad timing :(

@abompard @ryanlerch maybe you could review/test this PR?

@onosek could you check the test suite and add a test where the display-name isn't provided if there isn't one already?

**Review by cverna — APPROVED** [review]
LGTM

**Comment by pypingou** [comment]
@cverna no test?

**Comment by cverna** [comment]
> @cverna no test?

The backend is covered by the validator test, that's enough for me.

**Pull request merged**
