### PR TITLE
Few performance fix.

### PR DESCRIPTION
**Pull request by rayandas**
This PR adds few performance fixes.

### CODE REVIEW

**Review by mattiaverga — CHANGES_REQUESTED** [review]
Thank you!
I don't think there should be any performance improvement in using implicit `{}` instead of explicit `set()`, but I do prefer the explicit way because I find it to be better readable and more straightforward.
Not sure what are the preferences of other devs here, but I think it would be better if you can remove the two commits on `server/views/generic.py`.

The other changes look good to me.

**Comment by pypingou** [comment]
> I don't think there should be any performance improvement in using implicit {} instead of explicit set(), but I do prefer the explicit way because I find it to be better readable and more straightforward.

:+1: for me, ``{}`` can easily be mixed up with dict, so I tend to use ``set()`` explicitey as well

**Comment by rayandas** [comment]
@mattiaverga @pypingou I revert the changes in `server/views/generic.py`

**Comment by mattiaverga** [comment]
> @mattiaverga @pypingou I revert the changes in `server/views/generic.py`

Instead of pushing a new commit to revert changes, you should edit/remove the previous commits with `git rebase -i`. Look at the git docs and by searching on the internet how to use that command.

**Comment by rayandas** [comment]
@mattiaverga removed the commits.

**Comment by AdamSaleh** [comment]
While I am not sure about the performance, I *really* like the code changes :-)
It might be useful to enable checks for these, i.e. https://pypi.org/project/flake8-comprehensions/ ?

**Review by mattiaverga — APPROVED** [review]

**Pull request merged**
