### PR TITLE
Add new BuildRequires python3dist(poetry-core) in spec file and Fix wrong python_version in bodhi server httpd conf

### LINKED ISSUE #5678: build with spec false: budild require python3dist(poetry-core) but not in spec BuildRequires
```
#rpmbuild -bb bodhi-server.spec
...........
Handling poetry-core>=1.0.0 from build-system.requires
Requirement not satisfied: poetry-core>=1.0.0
Exiting dependency generation pass: build backend
+ cat /root/rpmbuild/BUILD/bodhi-server-8.0.2-2.fc38.x86_64-pyproject-buildrequires
+ rm -rfv '*.dist-info/'
+ cat
+ RPM_EC=0
++ jobs -p
+ exit 0
错误：构建依赖失败：
        python3dist(poetry-core) >= 1 被 bodhi-server-8.0.2-2.fc38.noarch 需要
已写至：/root/rpmbuild/SRPMS/bodhi-server-8.0.2-2.fc38.buildreqs.nosrc.rpm
```

```
bodhi-develop/bodhi-server/pyproject.toml

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

### LINKED ISSUE #5680: bodhi server web Incorrect static resource path for httpd
```
# yum install bodhi-server
```

there is python3.11 in fedora 38 and static resource path is `/usr/lib/python3.11/site-packages/bodhi/server/static/`
but there is python3.7 in ` /etc/httpd/conf.d/bodhi.conf `
```
[root@fedora rpmbuild]# ll /usr/lib/python3.11/site-packages/bodhi/server/static/
总计 44
-rw-r--r--.  1 root root 10425  1月11日 08:00 bodhi-logo.svg
drwxr-xr-x.  2 root root  4096  6月13日 09:50 css
drwxr-xr-x.  5 root root  4096  6月13日 09:50 fonts
drwxr-xr-x.  2 root root  4096  6月13日 09:50 ico
drwxr-xr-x.  2 root root  4096  6月13日 09:50 img
-rw-r--r--.  1 root root   832  1月11日 08:00 __init__.py
drwxr-xr-x.  2 root root  4096  6月13日 09:50 js
drwxr-xr-x.  2 root root  4096  6月13日 09:50 __pycache__
drwxr-xr-x. 10 root root  4096  6月13日 09:50 vendor

[root@fedora rpmbuild]# cat  /etc/httpd/conf.d/bodhi.conf 
Alias /static/v8.0.2 /usr/lib/python3.7/site-packages/bodhi/server/static/

WSGIDaemonProcess bodhi user=bodhi group=bodhi display-name=bodhi processes=2 threads=2
WSGISocketPrefix run/wsgi
WSGIRestrictStdout On
WSGIRestrictSignal Off
WSGIPythonOptimize 1

WSGIScriptAlias / /usr/share/bodhi/bodhi.wsgi

<Location />
    WSGIProcessGroup bodhi
    <IfModule mod_authz_core.c>
        # Apache 2.4
        Require all granted
    </IfModule>
    <IfModule !mod_authz_core.c>
         # Apache 2.2
        Order deny,allow
        Allow from all
    </IfModule>
</Location>
[root@fedora rpmbuild]# python3 --version
Python 3.11.9
[root@fedora rpmbuild]# cat /etc/system-release
Fedora release 38 (Thirty Eight)
```

### PR DESCRIPTION
**Pull request by kiraskyler**
fix issuse:
# https://github.com/fedora-infra/bodhi/issues/5678
# https://github.com/fedora-infra/bodhi/issues/5680

### CODE REVIEW

**Comment by kiraskyler** [comment]
@giallu @lmacken  @ashcrow  @brandongray 
could help me? thanks

**Comment by mattiaverga** [comment]
Hello @kiraskyler thank you for your contributions, good catch.
There are a couple of things that needs to be adjusted. First, you must sign your commits with DCO, in the workflows table see the Details link in the DCO test row for details how to fix it.

Second, it would be nice to have the fixes announced in release notes as described [here](https://fedora-infra.github.io/bodhi/8.0/developer/index.html#release-notes). You should add two files `5678.bug` and `5680.bug` with appropriate notes under the /news directory (add each file in the same commit with the fix by editing the commit).

**Comment by kiraskyler** [comment]
> Hello @kiraskyler thank you for your contributions, good catch. There are a couple of things that needs to be adjusted. First, you must sign your commits with DCO, in the workflows table see the Details link in the DCO test row for details how to fix it.
> 
> Second, it would be nice to have the fixes announced in release notes as described [here](https://fedora-infra.github.io/bodhi/8.0/developer/index.html#release-notes). You should add two files `5678.bug` and `5680.bug` with appropriate notes under the /news directory (add each file in the same commit with the fix by editing the commit).

Thank you for your guidance. I have signed my commits with DCO,
At the same time, add PR5678.bug and PR5680.bug with appropriate notes under the /news directory.

**Comment by mattiaverga** [comment]
Rawhide tests are expected to fail ATM because Fedora Rawhide is currently broken due to the Python 3.13 rebuild.
We just have to wait until that is fixed and I'll refresh tests, but everything looks good.

**Review by mattiaverga — APPROVED** [review]
Thanks!

**Pull request merged**
