### PR TITLE
Prepare for the 3.3.0 release.

### PR DESCRIPTION
**Pull request by bowlofeggs**
Signed-off-by: Randy Barlow <randy@electronsweatshop.com>

### CODE REVIEW

**Comment by pypingou** [comment]
The changes made to the script running as cron to pull the CI status are included, right?

**Comment by bowlofeggs** [comment]
@pypingou Those aren't included since they aren't merged yet. Since they are really just performance related, IMO they should not hold up the 3.3.0 release.

**Comment by pypingou** [comment]
I would really include them, they are hotfixed on the server and not including them would mean reverting these fixes

**Comment by pypingou** [comment]
Note that they aren't just performance related, they also just allow the cron to finish, so it's a little more than just "faster" :)

**Comment by bowlofeggs** [comment]
@pypingou I'm not aware of problems with the cron job failing to finish. Can you elaborate?

One of them has an LGTM if you would like to merge it. The other needs tests.

**Comment by pypingou** [comment]
> @pypingou I'm not aware of problems with the cron job failing to finish. Can you elaborate?

When we turned on gating you told me that the cron job rans for hours and eventually crashed. We have not seen this since it was hotfixed with these two PRs.

**Comment by bowlofeggs** [comment]
@pypingou I don't recall it ever crashing. It completed successfully after about 2 hours, and runs every 6 hours. That's why I don't think it's urgent to include the two patches (though I do of course think we should get tests written for the one and merged). I think it'll be fine if they wait until the next release, just a little inefficient.

**Comment by bowlofeggs** [comment]
I added c8942556f5df47df840a29e18ad8af5926d544d1 to the release notes in this PR.

**Review by puiterwijk — APPROVED** [review]

**Pull request merged**
