### PR TITLE
Set the test_gating_status back to waiting when updates are waived.

### LINKED ISSUE #2364: Waiving an update leaves its test_gating_status in a failed state
If a user waives failing tests on an update using the waive button, the update stays in a failed state until the next time the cron job runs. It would be more sensible to put it back into the "waiting on test results" state.

### PR DESCRIPTION
**Pull request by bowlofeggs**
fixes #2364

Signed-off-by: Randy Barlow <randy@electronsweatshop.com>

### CODE REVIEW

**Review by cverna — DISMISSED** [review]
:+1:

**Review by Zlopez — DISMISSED** [review]

**Comment by bowlofeggs** [comment]
jenkies test

**Comment by bowlofeggs** [comment]
jenkies test

**Review by puiterwijk — APPROVED** [review]
pre-acked

**Comment by bowlofeggs** [comment]
jenkies test

**Pull request merged**
