### PR TITLE
Have the Vagrant environment put the code in ~/bodhi.

### PR DESCRIPTION
**Pull request by bowlofeggs**
Signed-off-by: Randy Barlow <randy@electronsweatshop.com>

### CODE REVIEW

**Comment by pypingou** [comment]
Is the vagrant user created automatically? I'm not seeing it in the ansible playbook/role by a quick look

**Review by jeremycline — APPROVED** [review]
Looks good and it works, which is always a nice bonus

:shipit:

**Comment by jeremycline** [comment]
@pypingou The vagrant user is already created in the vagrant image

**Comment by pypingou** [comment]
@jeremycline cool, thanks for the info :)

👍 for me as well :)

**Pull request merged**
