### PR TITLE
Remove_unused_UpdateStatus.processing

### LINKED ISSUE #1999: UpdateStatus.processing seems to be unused
While documenting ```models.py``` I noticed that ```UpdateStatus``` has a [```processing```](https://github.com/fedora-infra/bodhi/blob/3.0.0/bodhi/server/models.py#L377) state, which does not seem to be used. We should remove it.

### PR DESCRIPTION
**Pull request by sebwoj**
Fixes #1999

Signed-off-by: Sebastian Wojciechowski <s.wojciechowski89@gmail.com>

If this patch will be included to bodhi 4.0 rel, I will add note in release notes.

### CODE REVIEW

**Review by bowlofeggs — CHANGES_REQUESTED** [review]
Nice, looks good. Let's add a release note since the CLI change is technically backwards incompatible.

**Review by bowlofeggs — APPROVED** [review]
Thanks so much!

**Comment by bowlofeggs** [comment]
BTW, I used the migration pattern you wrote here when I did #2994 ☺

**Comment by sebwoj** [comment]
Found on the net, tunned a llitle bit, and tested with "psql" command line after apply :D

**Comment by sebwoj** [comment]
It looks like alembic head (down revision) is improper. Is it ok to push changes after approval?

**Comment by bowlofeggs** [comment]
Ah, the failures are very likely due to me having merged other migrations - we just need to fix up the down revision. I'll fix that for you.

**Comment by bowlofeggs** [comment]
Heh, I see that you had the same thought - I'll fix it for you, no worries!

**Comment by bowlofeggs** [comment]
I'm applying this patch to your branch:

```
diff --git a/bodhi/server/migrations/versions/6b3eb9ae2b87_remove_unused_updatestatus_processing.py b/bodhi/server/migrations/versions/6b3eb9ae2b87_remove_unused_updatestatus_processing.py
index f615aeac..df37263f 100644
--- a/bodhi/server/migrations/versions/6b3eb9ae2b87_remove_unused_updatestatus_processing.py
+++ b/bodhi/server/migrations/versions/6b3eb9ae2b87_remove_unused_updatestatus_processing.py
@@ -19,7 +19,7 @@
 Remove unused UpdateStatus.processing.
 
 Revision ID: 6b3eb9ae2b87
-Revises: 5c86a3f9dc03
+Revises: aae0d29d49b7
 Create Date: 2019-02-09 12:17:18.444588
 """
 from alembic import op
@@ -28,7 +28,7 @@ from sqlalchemy import exc
 
 # revision identifiers, used by Alembic.
 revision = '6b3eb9ae2b87'
-down_revision = '5c86a3f9dc03'
+down_revision = 'aae0d29d49b7'
 
 
 def upgrade():
```

**Comment by bowlofeggs** [comment]
This patch is planned for inclusion in the upcoming 4.0.0 release: #3221

**Comment by bowlofeggs** [comment]
Bodhi 4.0.0 beta is built and deployed to staging:

https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release
https://bodhi.stg.fedoraproject.org/

**Pull request merged**
