### PR TITLE
Remove repetition in BugTracker

### PR DESCRIPTION
**Pull request by sebwoj**
Signed-off-by: Sebastian Wojciechowski <s.wojciechowski89@gmail.com>

### CODE REVIEW

**Comment by puiterwijk** [comment]
@centos-ci test this please

**Review by bowlofeggs — DISMISSED** [review]
heh, nice find!

**Comment by bowlofeggs** [comment]
jenkies test

**Comment by bowlofeggs** [comment]
jenkies test

**Review by bowlofeggs — DISMISSED** [review]

**Review by bowlofeggs — APPROVED** [review]

**Pull request merged**
