### PR TITLE
Prepare the 3.5.0 release.

### PR DESCRIPTION
**Pull request by bowlofeggs**
Signed-off-by: Randy Barlow <randy@electronsweatshop.com>

### CODE REVIEW

**Comment by bowlofeggs** [comment]
The CI test failure is due to https://pagure.io/releng/issue/7377.

**Comment by bowlofeggs** [comment]
The new CI test failure is due to https://pagure.io/releng/issue/7379

**Comment by bowlofeggs** [comment]
I was able to run the tests on my laptop and they pass, with the exclusion of rawhide.

**Review by puiterwijk — APPROVED** [review]

**Review by puiterwijk — CHANGES_REQUESTED** [review]
Actually, not yet. Missing #2167

**Comment by bowlofeggs** [comment]
I am adding this patch to this PR:

```
diff --git a/docs/user/release_notes.rst b/docs/user/release_notes.rst                                                
index 3da190de..6ed2b366 100644                            
--- a/docs/user/release_notes.rst                          
+++ b/docs/user/release_notes.rst                          
@@ -36,6 +36,7 @@ Bugs       
 ^^^^                        
                             
 * The location of the release notes was fixed in the developer docs (:issue:`2154`).                                 
+* Use ":"'s instead of "-"'s as the NSV separator for Modules (:issue:`2167`).                                       
 * ``bodhi-push`` no longer authenticates to Koji (:issue:`2190`).                                                    
 * Two tag references were fixed in ``bodhi-untag-branched`` (:commit:`59c83fc7`).                                    
 * Ensure there is a Greenwave summary to display before displaying it (:commit:`c07daf96`).
```

**Review by puiterwijk — APPROVED** [review]

**Comment by bowlofeggs** [comment]
OK after a ton of finagling I finally got this PR to pass CI on my laptop, except for Rawhide due to the current Rawhide issues. I will merge this PR as a result.

**Pull request merged**
