### PR TITLE
update to fedora-bootstrap-1.5.0

### PR DESCRIPTION
**Pull request by ryanlerch**
WIP for updating to the latest fedora-bootstrap release. will update this PR with some more fixes soon. Known issues i will fix next:
* ~~top menu needs to be on the right in the topbar~~
* ~~font colours and sizes don't match (i have this fixed, but the change is in fedora-bootstrap, so i will need to push a new release of that.)~~
* ~~blue halo in the search at the top of the page needs to go bye-bye.~~

If there are any other issues folks spot, please throw them in this ticket.

### CODE REVIEW

**Comment by ryanlerch** [comment]
Okies! this one is ready for review!

**Comment by ryanlerch** [comment]
okies, this one is ready for review. I left all the commits separate for now, just to make it easier to see what is going on here. happy to squash if needed.

**Comment by bowlofeggs** [comment]
Hey @ryanlerch!

I finally got some time to take a look at this - thanks for taking it on for me!

I've noticed a few changes since the last version:

* The text in some of the labels is a different color than before. For example, the old UI looked like this for the testing label:

Screenshot from 2019-03-12 17-42-41

And the new one looks like this:

Screenshot from 2019-03-12 17-40-55

I don't mind this change if you like it, just wanted to note it in case it was not intentional.

* The mouse turns into a pointer when I hover over the create/stats/profile/search icons in the upper right in the old UI, but turn into a text selector in this patch on create/stats, and are just a normal pointer over the profile/search icons.
* Similarly, the mouse turns into a pointer over an update's edit button, but are a text selector on the Revoke and unpush buttons. I don't have an update to test with the push to stable button, but ideally it would look "clickable" too.
* The builds tab on the update is very narrow. Arguably, it's too wide in the previous version too, so I don't think this is bad, just a change I noticed. I don't mind keeping it this way if you prefer it.
* There's a white band across the top of the page that wasn't there before. Before:

Screenshot from 2019-03-12 17-50-02

After:

Screenshot from 2019-03-12 17-49-02

I also don't mind this one, just wanted to make sure it wasn't accidental.

Anyways, I'm happy to merge if we can get the mouse pointers to work like they did before, since they are a good hint about what is clickable and what is not.

**Comment by bowlofeggs** [comment]
Also, can you sign the DCO in your commit messages? That will make DCO bot happy. I'm going to force push to your branch to rebase on the latest develop.

**Comment by bowlofeggs** [comment]
@ryanlerch Do you still want to work on this pull request?

**Comment by mattiaverga** [comment]
Let me know if this PR is stuck, I can rework my old #3001 on top of fedora-bootstrap 1.5

**Comment by bowlofeggs** [comment]
Yeah this does seem a bit stalled - I wrote @ryanlerch to see if he has some time to take another look.

**Comment by ryanlerch** [comment]
Sorry about the slow reply! will get those things fixed ASAP

**Comment by ryanlerch** [comment]
Just pushed a few more commits to address most of these, comments on each one are below, but it is ready for re-review.

> Hey @ryanlerch!
> 
> I finally got some time to take a look at this - thanks for taking it on for me!
> 
> I've noticed a few changes since the last version:
> 
> * The text in some of the labels is a different color than before. For example, the old UI looked like this for the testing label:
> 
> Screenshot from 2019-03-12 17-42-41
> 
> And the new one looks like this:
> 
> Screenshot from 2019-03-12 17-40-55
> 
> I don't mind this change if you like it, just wanted to note it in case it was not intentional.

Intentional, but not by me. Bootstrap changed the text colour of the warning label. I have added some text-white classes to the labels to make sure that the color is white. Additionally, i changed the warning badge's background colour back to what it was before too.

> 
> * The mouse turns into a pointer when I hover over the create/stats/profile/search icons in the upper right in the old UI, but turn into a text selector in this patch on create/stats, and are just a normal pointer over the profile/search icons.
> * Similarly, the mouse turns into a pointer over an update's edit button, but are a text selector on the Revoke and unpush buttons. I don't have an update to test with the push to stable button, but ideally it would look "clickable" too.

These are now fixed. In this new version of bootstrap, any `<a>` elements without a `href` don't render a pointer. Adding a `href="javascript:void(0)"` to these `<a>` elements fixes this.

> * The builds tab on the update is very narrow. Arguably, it's too wide in the previous version too, so I don't think this is bad, just a change I noticed. I don't mind keeping it this way if you prefer it.

Yeah, i agree this one is not bad, so left it as is.

> * There's a white band across the top of the page that wasn't there before. Before:
> 
> Screenshot from 2019-03-12 17-50-02
> 
> After:
> 
> Screenshot from 2019-03-12 17-49-02
> 
> I also don't mind this one, just wanted to make sure it wasn't accidental.

Yup, accidental. Fixed in a commit above.

> 
> Anyways, I'm happy to merge if we can get the mouse pointers to work like they did before, since they are a good hint about what is clickable and what is not.

**Comment by bowlofeggs** [comment]
Cool, this all looks good to me. I'm going to rebase and squash and see if I can get CI to pass.

**Comment by bowlofeggs** [comment]
Heh, looks like we have some tests that are asserting that the styling stuff is just so and that's why the tests fail. I can fix that up for you.

**Comment by bowlofeggs** [comment]
I'm applying this patch to correct the tests:

```
diff --git a/bodhi/tests/server/services/test_overrides.py b/bodhi/tests/server/services/test_overrides.py
index 82d2d467..3fa1b07c 100644
--- a/bodhi/tests/server/services/test_overrides.py
+++ b/bodhi/tests/server/services/test_overrides.py
@@ -749,7 +749,7 @@ class TestOverridesWebViews(base.BaseTestCase):
         """
         resp = self.app.get('/overrides/new',
                             status=200, headers={'Accept': 'text/html'})
-        self.assertIn('<h2 class="pull-left mt-3">New Override</h2>', resp)
+        self.assertIn('<h2 class="float-left mt-3">New Override</h2>', resp)
 
     def test_overrides_list(self):
         """
diff --git a/bodhi/tests/server/services/test_updates.py b/bodhi/tests/server/services/test_updates.py
index a03b93b3..03a6d458 100644
--- a/bodhi/tests/server/services/test_updates.py
+++ b/bodhi/tests/server/services/test_updates.py
@@ -4745,7 +4745,7 @@ class TestUpdatesService(BaseTestCase):
         Assert that the "Update Severity" label appears correctly when the severity is urgent.
         """
         self.assertSeverityHTML(UpdateSeverity.urgent,
-                                '<span class=\'label label-danger\'>urgent</span>')
+                                '<span class=\'badge badge-danger\'>urgent</span>')
 
     @mock.patch(**mock_valid_requirements)
     def test_update_severity_label_present_correctly_when_severity_is_high(self, *args):
@@ -4753,7 +4753,7 @@ class TestUpdatesService(BaseTestCase):
         Assert that the "Update Severity" label appears correctly when the severity is high.
         """
         self.assertSeverityHTML(UpdateSeverity.high,
-                                '<span class=\'label label-warning\'>high</span>')
+                                '<span class=\'badge badge-warning\'>high</span>')
 
     @mock.patch(**mock_valid_requirements)
     def test_update_severity_label_present_correctly_when_severity_is_medium(self, *args):
@@ -4761,7 +4761,7 @@ class TestUpdatesService(BaseTestCase):
         Assert that the "Update Severity" label appears correctly when the severity is medium.
         """
         self.assertSeverityHTML(UpdateSeverity.medium,
-                                '<span class=\'label label-primary\'>medium</span>')
+                                '<span class=\'badge badge-primary\'>medium</span>')
 
     @mock.patch(**mock_valid_requirements)
     def test_update_severity_label_present_correctly_when_severity_is_low(self, *args):
@@ -4769,7 +4769,7 @@ class TestUpdatesService(BaseTestCase):
         Assert that the "Update Severity" label appears correctly when the severity is low.
         """
         self.assertSeverityHTML(UpdateSeverity.low,
-                                '<span class=\'label label-success\'>low</span>')
+                                '<span class=\'badge badge-success\'>low</span>')
 
     @mock.patch(**mock_valid_requirements)
     def test_update_severity_label_present_correctly_when_severity_is_unspecified(self, *args):
@@ -4777,7 +4777,7 @@ class TestUpdatesService(BaseTestCase):
         Assert that the "Update Severity" label appears correctly when the severity is unspecified.
         """
         self.assertSeverityHTML(UpdateSeverity.unspecified,
-                                '<span class=\'label label-default\'>unspecified</span>')
+                                '<span class=\'badge badge-default\'>unspecified</span>')
 
     @mock.patch(**mock_valid_requirements)
     def test_update_severity_label_absent_when_severity_is_None(self, *args):
diff --git a/bodhi/tests/server/test_util.py b/bodhi/tests/server/test_util.py
index 5aa9db5d..7a718377 100644
--- a/bodhi/tests/server/test_util.py
+++ b/bodhi/tests/server/test_util.py
@@ -567,14 +567,14 @@ class TestType2Icon(unittest.TestCase):
         """Test type2icon() with a kind that starts with a consonant."""
         self.assertEqual(
             util.type2icon(None, 'security'),
-            ("<span class='badge badge-danger' data-toggle='tooltip' "
+            ("<span class='badge badge-danger text-white' data-toggle='tooltip' "
              "title='This is a security update'><i class='fa fa-fw fa-shield'></i></span>"))
 
     def test_vowel(self):
         """Test type2icon() with a kind that starts with a vowel."""
         self.assertEqual(
             util.type2icon(None, 'enhancement'),
-            ("<span class='badge badge-success' data-toggle='tooltip' "
+            ("<span class='badge badge-success text-white' data-toggle='tooltip' "
              "title='This is an enhancement update'><i class='fa fa-fw fa-bolt'></i></span>"))
 
 
diff --git a/bodhi/tests/server/views/test_generic.py b/bodhi/tests/server/views/test_generic.py
index 44553e3e..c9b0f6d6 100644
--- a/bodhi/tests/server/views/test_generic.py
+++ b/bodhi/tests/server/views/test_generic.py
@@ -650,7 +650,7 @@ http://localhost/updates/?releases=F18&amp;status=stable&amp;type=newpackage">
         <a class="notblue" href="http://localhost/releases/F18">
   Fedora 18
         </a>
-          <span class="badge badge-default">prerelease</span>
+          <span class="badge badge-secondary">prerelease</span>
       </h3>""", res)
 
 
```

**Comment by ryanlerch** [comment]
Thanks for fixing the tests @bowlofeggs ! 

It seems i forgot the habit of running the tests before pushing! sorry!

**Review by bowlofeggs — APPROVED** [review]
Thanks!

**Pull request merged**
