### PR TITLE
sanity_check_repo() now supports modular repositories.

### LINKED ISSUE #2631: sanity_check_repodata() fails on modular repos
Production has been failing on modular repos with this exception:

```
[2018-10-01 23:26:36][fedmsg.consumers   ERROR]f29-modular-updates-testing ComposerThread failed. Transaction rolled back.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/bodhi/server/consumers/masher.py", line 339, in run 
    self.work()
  File "/usr/lib/python2.7/site-packages/bodhi/server/consumers/masher.py", line 410, in work
    self._compose_updates()
  File "/usr/lib/python2.7/site-packages/bodhi/server/consumers/masher.py", line 950, in _compose_updates
    self._sanity_check_repo()
  File "/usr/lib/python2.7/site-packages/bodhi/server/consumers/masher.py", line 1155, in _sanity_check_repo
    sanity_check_repodata(repodata, source=False)
  File "/usr/lib/python2.7/site-packages/bodhi/server/util.py", line 290, in sanity_check_repodata
    raise RepodataException('Required part not in repomd.xml')
RepodataException: Required part not in repomd.xml
[2018-10-01 23:26:36][fedmsg.consumers    INFO]f29-modular-updates-testing Released semaphore
[2018-10-01 23:26:36][fedmsg.consumers    INFO]PoolThread-twisted.internet.reactor-1 Push complete!  Summary follows:
[2018-10-01 23:26:36][fedmsg.consumers    INFO]PoolThread-twisted.internet.reactor-1   name:  f29-modular-updates-testing  success:  False
```

I don't think this code was intended to be run on modular repos, so we should probably just fix it by making sure it only runs on yum repos.

### PR DESCRIPTION
**Pull request by bowlofeggs**
There was a crash in _sanity_check_repo() as it expected to find
elements that were not present. This commit adjusts it to look for
the appropriate elements for modular repositories.

fixes #2631

Signed-off-by: Randy Barlow <randy@electronsweatshop.com>

### CODE REVIEW

**Review by puiterwijk — CHANGES_REQUESTED** [review]
As commented on the bug, this is wrong, and modular repos *do* need sanity checking. Just with a different set of expected repomd fields.

**Comment by bowlofeggs** [comment]
Here's an example of a module repo's repomd file: https://dl.fedoraproject.org/pub/fedora/linux/development/rawhide/Modular/x86_64/os/repodata/repomd.xml

**Comment by bowlofeggs** [comment]
As noted by Patrick, we should remove the check for prestodelta on modules and add a check for modules.

**Comment by bowlofeggs** [comment]
The Rawhide failure is due to https://bugzilla.redhat.com/show_bug.cgi?id=1636611 and can be ignored.

**Comment by pypingou** [comment]
Looks fine to me, I leave up to you if you want @puiterwijk to look at it again or not

**Review by cverna — DISMISSED** [review]
Rubber stamp

**Review by puiterwijk — DISMISSED** [review]
Looks fine to me. :haircut_man:

**Comment by bowlofeggs** [comment]
I don't know a good way to test this in staging, so I have hotfixed production with this patch so we can make sure it works there. If it does, I will merge this and release 3.10.1.

**Comment by bowlofeggs** [comment]
This patch failed in production because apparently module repos don't have comps, so I'm applying this patch:

```
diff --git a/bodhi/server/util.py b/bodhi/server/util.py
index 0a75c29f..6d73fa53 100644
--- a/bodhi/server/util.py
+++ b/bodhi/server/util.py
@@ -301,8 +301,8 @@ def sanity_check_repodata(myurl, repo_type):
                            load_presto=True,
                            load_updateinfo=True)

-    # Source repos don't have comps.
-    if repo_type != 'source':
+    # Only yum repos have comps
+    if repo_type == 'yum':
         # Test comps
         comps = libcomps.Comps()
         try:
diff --git a/bodhi/tests/server/test_util.py b/bodhi/tests/server/test_util.py
index fdf31aab..35ac1d54 100644
--- a/bodhi/tests/server/test_util.py
+++ b/bodhi/tests/server/test_util.py
@@ -552,8 +552,8 @@ class TestSanityCheckRepodata(unittest.TestCase):
         root = repomd_tree.getroot()
         ElementTree.SubElement(root, 'data', type='modules')
         for data in root.findall('{http://linux.duke.edu/metadata/repo}data'):
-            # module repos don't have drpms.
-            if data.attrib['type'] == 'prestodelta':
+            # module repos don't have drpms or comps.
+            if data.attrib['type'] in ('group', 'prestodelta'):
                 root.remove(data)
         repomd_tree.write(repomd_path, encoding='UTF-8', xml_declaration=True)
```

**Review by puiterwijk — APPROVED** [review]
🥇

**Comment by bowlofeggs** [comment]
This patch is confirmed working on production.

**Pull request merged**
