### PR TITLE
Add IRC freenode link

### PR DESCRIPTION
**Pull request by amanharitsh123**
Signed-off-by: amanharitsh123<amanharitsh123@gmail.com>

### CODE REVIEW

**Comment by amanharitsh123** [comment]
I have attached the DCO..Why is it showing DCO missing

**Comment by amanharitsh123** [comment]
Can anyone please review this PR?

**Comment by amanharitsh123** [comment]
@bowlofeggs Please review

**Comment by bowlofeggs** [comment]
Please don't open new pull requests to make changes, because that causes us to lose the context of the conversation around the code. You can use ```git commit --amend``` and ```git push -f``` to edit your existing branch and pull request, without needing to open new ones.

I had a requested change in the original PR to make only the word Freenode a link. I'll copy that here too.

For reference, this code was originally proposed in https://github.com/fedora-infra/bodhi/pull/1829.

**Review by bowlofeggs — CHANGES_REQUESTED** [review]
Since the link doesn't actually take the person to the #bodhi channel but just to Freenode, can we adjust it so the link is only on the word "Freenode"? Like this:

```
* IRC: #bodhi on `Freenode <https://webchat.freenode.net/>`_
```

**Comment by bowlofeggs** [comment]
jenkies test

**Comment by bowlofeggs** [comment]
This was done as part of https://github.com/fedora-infra/bodhi/pull/1883. Thanks for the patch!

**Pull request closed without merging**
