### PR TITLE
Do not override existing request when editing an update #2

### PR DESCRIPTION
**Pull request by mattiaverga**
#4267 was wrong and caused some tests to fail.
This will hopefully restore the correct behavior.

Signed-off-by: Mattia Verga <mattia.verga@tiscali.it>

### CODE REVIEW

**Comment by AdamSaleh** [comment]
Damn it, when I was running it locally I had the impression it was just the CI runner acting up.
I am reviewing it more thoroughly, an found some issues in tests, where we might be over-riding the test-status in way we didn't before (i.e. before it was Testing, now it is None)

**Comment by mattiaverga** [comment]
Uh, strange, before your rebase the unit tests were passing... I will have another look at this.

**Comment by mattiaverga** [comment]
I've reverted #4267 and chose to try not injecting the request in UpdateSaveSchema.
Reason is that an UpdateRequest is set by set_request (both service and method are named the same), not by the edit update method.

For the same reason I've removed a test which was failing, but it was inherently wrong: in fact, trying to editing a request for a locked update will still fail with the appropriate error message set by set_request. The only change is that now if you try to edit anything other than the buildlist of a locked update you can (changing buglist, description etc.). I suppose that should be permitted, let me know if you think it is better to lock everything.

**Comment by AdamSaleh** [comment]
Nice! Thanks a lot.

**Review by AdamSaleh — APPROVED** [review]

**Pull request merged**
