### PR TITLE
Fix some crashes regarding changelog retrieving

### PR DESCRIPTION
**Pull request by puiterwijk**

### CODE REVIEW

**Comment by bowlofeggs** [comment]
I want to include this in the upcoming 3.1.0 release, so I will write tests for it.

**Comment by bowlofeggs** [comment]
@puiterwijk I've added a new commit with tests I wrote for your two commits. I approve of your commits, so if you approve of mine and Jenkies passes, we are good to merge!

**Review by bowlofeggs — APPROVED** [review]

**Review by puiterwijk — COMMENTED** [review]
The tests look good. :+1:

**Comment by bowlofeggs** [comment]
jenkies test

**Comment by bowlofeggs** [comment]
jenkies test

**Comment by bowlofeggs** [comment]
jenkies test

**Comment by bowlofeggs** [comment]
jenkies test

**Comment by bowlofeggs** [comment]
This is backported to the 3.1 branch in https://github.com/fedora-infra/bodhi/pull/1993.

**Comment by bowlofeggs** [comment]
The patch for this will be included in the upcoming 3.2.0 release:

https://github.com/fedora-infra/bodhi/pull/2092

**Pull request merged**
