### PR TITLE
Revert "Do not check gpg signatures in pip integration."

### PR DESCRIPTION
**Pull request by bowlofeggs**
This reverts commit ca7c891b1333ebfcd7bf63fe976050f68ccafcb8.

### CODE REVIEW

**Review by cverna — APPROVED** [review]

**Comment by bowlofeggs** [comment]
I've filed https://bugzilla.redhat.com/show_bug.cgi?id=1705265 about the rpmdb corruption issue.

**Comment by bowlofeggs** [comment]
I've opened https://github.com/fedora-infra/bodhi/pull/3207 to work around https://bugzilla.redhat.com/show_bug.cgi?id=1705265

**Comment by bowlofeggs** [comment]
That diff-cover failure is strange. It's unable to read the .git folder, but the other releases' diff-cover tests worked just fine. I'll rebase and see if it passes.

**Comment by bowlofeggs** [comment]
Strange, every single build timed out in CI.

**Pull request merged**
