### PR TITLE
bodhi-ci: a Job shouldn't have to know about all other jobs

### PR DESCRIPTION
**Pull request by abompard**
This introduces a `ProgressReporter` class which handles the status printing.

### CODE REVIEW

**Review by bowlofeggs — APPROVED** [review]
Nice!

**Comment by bowlofeggs** [comment]
Actually, slight conflict with the mypy patch I made (and this is an example of two PRs that pass individually but not together ☺). I'm going to apply this patch and force push to your branch:

```
diff --git a/devel/ci/bodhi-ci b/devel/ci/bodhi-ci
index 3ff18651..4b405f60 100755
--- a/devel/ci/bodhi-ci
+++ b/devel/ci/bodhi-ci
@@ -998,10 +998,9 @@ def _build_jobs_list(
             flake8_job = Flake8Job(release, depends_on=build_job, buffer_output=buffer_output)
             jobs.append(flake8_job)
         if command in ('all', 'mypy') and release == 'pip':
-            mypy_build_job = MyPyBuildJob(release, jobs, depends_on=build_job,
+            mypy_build_job = MyPyBuildJob(release, depends_on=build_job,
                                           buffer_output=buffer_output)
-            mypy_job = MyPyJob(release, jobs, depends_on=mypy_build_job,
-                               buffer_output=buffer_output)
+            mypy_job = MyPyJob(release, depends_on=mypy_build_job, buffer_output=buffer_output)
             jobs.extend([mypy_build_job, mypy_job])
         if command in ('all', 'pydocstyle'):
             pydocstyle_job = PydocstyleJob(release, depends_on=build_job, buffer_output=buffer_output)
```

**Comment by bowlofeggs** [comment]
Actually, it turns out one more patch is needed:

```
diff --git a/devel/ci/bodhi-ci b/devel/ci/bodhi-ci
index 4b405f60..c4ce4e7b 100755
--- a/devel/ci/bodhi-ci
+++ b/devel/ci/bodhi-ci
@@ -304,7 +304,7 @@ class ProgressReporter(object):
         Args:
             jobs: A list of the Jobs to report on.
         """
-        self._jobs = []
+        self._jobs = []  # type: typing.List[Job]
         for job in jobs:
             self.register_job(job)
```

I will also force push this to your branch, then it should be good to merge!

**Comment by abompard** [comment]
Go aheah, you're the mypy expert here :-)
(For now. I plan on catching up one day)

**Comment by bowlofeggs** [comment]
I'm adding this patch to make mypy happy:

```
diff --git a/devel/ci/bodhi-ci b/devel/ci/bodhi-ci
index 33100864..14613fe3 100755
--- a/devel/ci/bodhi-ci
+++ b/devel/ci/bodhi-ci
@@ -304,7 +304,7 @@ class ProgressReporter(object):
         Args:
             jobs: A list of the Jobs to report on.
         """
-        self._jobs = []
+        self._jobs = []  # type: typing.List[Job]
         for job in jobs:
             self.register_job(job)
```

**Comment by bowlofeggs** [comment]
Not sure why Mergify isn't seeing all the passed tests, but I will merge this manually.

**Pull request merged**
