### PR TITLE
convert test_mail.py to BaseTestCase

### LINKED ISSUE #3601: Convert bodhi/tests/server/test_mail.py to BaseTestCase
[bodhi/tests/server/test_mail.py](https://github.com/fedora-infra/bodhi/blob/develop/bodhi/tests/server/test_mail.py) still contain classes that derive from unittest.TestCase. We use pytest, so they could be migrated to derive from bodhi.tests.server.base.BaseTestCase.

This also allows the use of the simpler assert constructs instead of the self.assert*() methods.

The following PR is an example of the changes that might need to be done to this file:
#3574

### PR DESCRIPTION
**Pull request by ryanlerch**
Fixes: #3601

Signed-off-by: Ryan Lerch <rlerch@redhat.com>

### CODE REVIEW

**Comment by nphilipp** [comment]
See my comments [here](https://github.com/fedora-infra/bodhi/issues/3357#issuecomment-543682662) and [here](https://github.com/fedora-infra/bodhi/issues/3357#issuecomment-543685981).

Deriving from `BaseTestCase` instead of `unittest.TestCase` will add unnecessary overhead not needed in these tests, and still ultimately derive from `unittest.TestCase`. Instead, just don't derive from `unittest.TestCase`. Classes already derived from `BaseTestCase` should derive from `BasePyTestCase` instead. I.e.:

````
diff --git a/bodhi/tests/server/test_mail.py b/bodhi/tests/server/test_mail.py
index 7036d488..904d4d67 100644
--- a/bodhi/tests/server/test_mail.py
+++ b/bodhi/tests/server/test_mail.py
@@ -26,7 +26,7 @@ from bodhi.server.util import get_absolute_path
 from bodhi.tests.server import base
 
 
-class TestGetTemplate(base.BaseTestCase):
+class TestGetTemplate(base.BasePyTestCase):
     """Test the get_template() function."""
 
     def test_changelog(self):
@@ -204,7 +204,7 @@ class TestGetTemplate(base.BaseTestCase):
         assert "IO Error[None]: None" == error.mock_calls[1][1][0]
 
 
-class TestSend(base.BaseTestCase):
+class TestSend(base.BasePyTestCase):
     """Test the send() function."""
 
     @mock.patch.dict('bodhi.server.mail.config', {'smtp_server': 'smtp.fp.o'})
@@ -257,7 +257,7 @@ class TestSend(base.BaseTestCase):
         assert sendmail.call_count == 0
 
 
-class TestSendMail(base.BaseTestCase):
+class TestSendMail:
     """Test the send_mail() function."""
 
     @mock.patch.dict('bodhi.server.mail.config',
@@ -312,7 +312,7 @@ class TestSendMail(base.BaseTestCase):
              b'X-Bodhi: fedoraproject.org\r\nSubject: R013X\r\n\r\nWant a c00l w@tch?'))
 
 
-class TestSendReleng(base.BaseTestCase):
+class TestSendReleng:
     """Test the send_releng() function."""
 
     @mock.patch.dict('bodhi.server.mail.config', {'smtp_server': 'smtp.fp.o'})
@@ -333,7 +333,7 @@ class TestSendReleng(base.BaseTestCase):
                     'utf-8'))
 
 
-class Test_SendMail(base.BaseTestCase):
+class Test_SendMail:
     """Test the _send_mail() function."""
 
     @mock.patch.dict('bodhi.server.mail.config', {'smtp_server': 'smtp.fp.o'})
````

**Review by nphilipp — CHANGES_REQUESTED** [review]
See my comment above.

**Comment by ryanlerch** [comment]
Sorry about at the noise! It seems i mis-interpreted the initial issue here :)

updated this commit with the requested changes

**Review by Zlopez — APPROVED** [review]

**Review by nphilipp — APPROVED** [review]
Thanks Ryan!

**Pull request merged**
