### PR TITLE
3.5.0 cherry picks

### PR DESCRIPTION
**Pull request by bowlofeggs**

### CODE REVIEW

**Review by puiterwijk — APPROVED** [review]

**Comment by bowlofeggs** [comment]
I'm adding one patch in these cherry picks to the first commit:

```
diff --git a/docs/user/release_notes.rst b/docs/user/release_notes.rst                                                
index 68dbf2b2..17f9dd94 100644                            
--- a/docs/user/release_notes.rst                          
+++ b/docs/user/release_notes.rst                          
@@ -37,6 +37,7 @@ Contributors                             
 The following developers contributed to Bodhi 3.5.0:      
                             
 * Patrick Uiterwijk         
+* Jan Kaluza                
 * Pierre-Yves Chibon        
 * Anatoli Babenia           
 * Randy Barlow 
```

I'll file a new PR to do the same on develop.

**Comment by puiterwijk** [comment]
+1

**Comment by bowlofeggs** [comment]
Here's a PR on the develop branch for that contributor doc change: https://github.com/fedora-infra/bodhi/pull/2203

**Comment by puiterwijk** [comment]
Looks good to me.

**Comment by bowlofeggs** [comment]
Tests pass on my laptop for f26, f27, and pip so I am merging. Thanks!

**Pull request merged**
