### PR TITLE
Use Python 3 when provisioning Vagrant with Ansible.

### PR DESCRIPTION
**Pull request by bowlofeggs**
Signed-off-by: Randy Barlow <randy@electronsweatshop.com>

### CODE REVIEW

**Comment by bowlofeggs** [comment]
This currently won't work on my Fedora 29 host due to https://github.com/ansible/ansible/issues/49120. I'm not sure how long it will be until the fix for that issue will be available for Fedora hosts, so I'm marking this as no-mergify and we can just hold the PR open until it works.

**Review by pypingou — APPROVED** [review]

**Review by Zlopez — APPROVED** [review]
:+1:

**Comment by bowlofeggs** [comment]
Three months later, and this error still happens. I guess I'll just try again later. I'll keep this open for a while longer.

**Comment by cverna** [comment]
> Three months later, and this error still happens. I guess I'll just try again later. I'll keep this open for a while longer.

I think you ran into https://github.com/ansible/ansible/pull/50381 with newer version of RabbitMQ is breaking the module.

**Comment by bowlofeggs** [comment]
I tested this again today and it seems to work with ```ansible-2.8.2-1.fc30.noarch```.

**Pull request merged**
