### PR TITLE
Fix a typo in the update template JavaScript.

### LINKED ISSUE #2569: ReferenceError: req is not defined
There is a regression introduced by #2394, where ```req``` is used instead of ```requirement``` [here](https://github.com/fedora-infra/bodhi/blob/4d1c284df55cc74fdc3d1ee4ff7ba6eabe9ea5a8/bodhi/server/templates/update.html#L69).

### PR DESCRIPTION
**Pull request by bowlofeggs**
fixes #2569

### CODE REVIEW

**Review by cverna — DISMISSED** [review]

**Comment by bowlofeggs** [comment]
I am amending my commit to add the Signed-Off-By line, but am not altering the contents.

**Comment by bowlofeggs** [comment]
Looks like the CI job is not getting run because it was deleted:

https://lists.centos.org/pipermail/ci-users/2018-September/000860.html

**Comment by mattiaverga** [comment]
I suppose this will fix #2571 also (?)

**Comment by bowlofeggs** [comment]
@mattiaverga I don't believe so - I think that bug happened in staging when this patch was applied.

**Pull request merged**
