### PR TITLE
Drop support for Python 2.

### LINKED ISSUE #2856: Drop Python 2 support for bodhi.client
We need to wait until no packages depend on it, but when we are able to we should drop Python 2 support from ```bodhi.client```.

### PR DESCRIPTION
**Pull request by bowlofeggs**
fixes #2856

Signed-off-by: Randy Barlow <randy@electronsweatshop.com>

### CODE REVIEW

**Comment by bowlofeggs** [comment]
There's still more to do here, like remove the usage of six and get the tests passing. But it's Friday and I'm going afk for the weekend ☺

**Review by Zlopez — APPROVED** [review]
It's nice that the Bodhi get rid of the Python 2

**Comment by bowlofeggs** [comment]
This patch is planned for inclusion in the upcoming 4.0.0 release: #3221

**Comment by bowlofeggs** [comment]
Bodhi 4.0.0 beta is built and deployed to staging:

https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release
https://bodhi.stg.fedoraproject.org/

**Pull request merged**
