### PR TITLE
Separated update type option for creating and editing update.

### LINKED ISSUE #2528: Editing an update using CLI sets type to 'bugfix' if not provided
While editing an update using CLI, if we don't provide the update type, it will modify it to ```bugfix```

So if we edit a ```security``` update, 

```bodhi updates edit --severity low moin-1.9.9-1.el6```

update's type will be changed to ```bugfix```. I think [this](https://github.com/fedora-infra/bodhi/blob/develop/bodhi/client/__init__.py#L96) might be the reason, as the default is shared between create and edit update.

### PR DESCRIPTION
**Pull request by ghost**
fixes #2528

Signed-off-by: Vismay Golwala <vgolwala@redhat.com>

### CODE REVIEW

**Review by bowlofeggs — DISMISSED** [review]

**Comment by bowlofeggs** [comment]
jenkies test

**Comment by bowlofeggs** [comment]
jenkies test

**Comment by bowlofeggs** [comment]
jenkies test

**Comment by bowlofeggs** [comment]
jenkies test

**Review by bowlofeggs — APPROVED** [review]

**Review by Zlopez — APPROVED** [review]

**Comment by bowlofeggs** [comment]
I'm applying this patch to fix a couple new tests that have been added since this was written:

```
diff --git a/bodhi/tests/client/test___init__.py b/bodhi/tests/client/test___init__.py
index 18aa047a..86fe6199 100644
--- a/bodhi/tests/client/test___init__.py
+++ b/bodhi/tests/client/test___init__.py
@@ -1357,7 +1357,7 @@ class TestEdit(unittest.TestCase):
                     'autokarma': False, 'edited': 'nodejs-grunt-wrap-0.3.0-2.fc25',
                     'suggest': 'unspecified', 'notes': 'New package.',
                     'notes_file': None, 'request': None, 'unstable_karma': -3,
-                    'bugs': '1234,5678', 'requirements': '', 'type': 'bugfix',
+                    'bugs': '1234,5678', 'requirements': '', 'type': 'newpackage',
                     'severity': 'low'}),
             mock.call(
                 bindings_client,
@@ -1697,7 +1697,7 @@ class TestEdit(unittest.TestCase):
                     'autokarma': False, 'edited': u'nodejs-grunt-wrap-0.3.0-2.fc25',
                     'suggest': u'unspecified', 'notes': u'New package.',
                     'notes_file': None, 'request': None, 'severity': u'low',
-                    'bugs': '', 'requirements': u'', 'unstable_karma': -3, 'type': 'bugfix'
+                    'bugs': '', 'requirements': u'', 'unstable_karma': -3, 'type': 'newpackage'
                 }
             ),
             mock.call(
```

**Comment by bowlofeggs** [comment]
This fix is planned for inclusion in Bodhi 3.13: #2917.

**Comment by bowlofeggs** [comment]
This fix is now deployed to staging: https://bodhi.stg.fedoraproject.org/docs/user/release_notes.html

It is also available via Copr: https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release/

**Pull request merged**
