### PR TITLE
Display timezone in timestamps

### LINKED ISSUE #789: show timezone in timestamps
When I look at some update ([example](https://bodhi.fedoraproject.org/updates/FEDORA-2016-5ba698daad)), I sometimes really need to know which timezone all the timestamps are in. When Bodhi says this update was pushed stable today at 22:24, is that UTC, or my local time, or the Bodhi server local time?

Please add a timezone notifier behind the timestamp to make it clear, thank you.

### PR DESCRIPTION
**Pull request by trishnaguha**
Fixes #789

### CODE REVIEW

**Comment by ralphbean** [comment]
@trishnaguha, since this is a UI change, can you attach a screenshot of the affected page in a comment here?  It just makes it easier to review.  :)

**Comment by trishnaguha** [comment]
@ralphbean Here are the screenshots :)

screenshot from 2016-03-09 20-33-46

screenshot from 2016-03-09 20-34-03

**Comment by ralphbean** [comment]
Good stuff!  :+1: here!

**Comment by kparal** [comment]
When I saw those screenshots, I wonder - is the microsecond precision intentional? It seems a bit too precise for human consumption :)

**Comment by trishnaguha** [comment]
@kparal 
So @ralphbean or @lmacken can answer that :)

**Comment by ralphbean** [comment]
> is the microsecond precision intentional?

Nope!  We should get rid of it.  ;)

**Pull request merged**
