### PR TITLE
Add httpie to the Vagrant environment.

### PR DESCRIPTION
**Pull request by bowlofeggs**
Signed-off-by: Randy Barlow <randy@electronsweatshop.com>

### CODE REVIEW

**Review by ryanlerch — APPROVED** [review]
Looks good to me!

Just out of interest, is there a tool in the dev environment that uses httpie, or is this just for convenience?

**Comment by pypingou** [comment]
👍 as well

**Review by ralphbean — APPROVED** [review]
:1st_place_medal:

**Comment by bowlofeggs** [comment]
On Thu, 2017-06-01 at 13:57 -0700, Ryan Lerch wrote:
> Just out of interest, is there a tool in the dev environment that
> uses httpie, or is this just for convenience?

Just for convenience. It's a really nice tool for messing with REST
APIs, much friendlier than curl.

**Pull request merged**
