### PR TITLE
Make sure to close the bugs associated to a rawhide update.

### LINKED ISSUE #4067: Rawhide automatically close bugs when the update reach stable
We now can associate bugs to a rawhide update but the bugs are not closed when the update reach stable. This is normally done during the daily compose which does not happen in rawhide so we need to probably add that steps to the approve_testing script.

### PR DESCRIPTION
**Pull request by cverna**
Fixes #4067

Signed-off-by: Clement Verna <cverna@tutanota.com>

### CODE REVIEW

**Comment by mattiaverga** [comment]
What do you think of https://github.com/fedora-infra/bodhi/issues/4067#issuecomment-648929588 ?

**Comment by cverna** [comment]
> What do you think of [#4067 (comment)](https://github.com/fedora-infra/bodhi/issues/4067#issuecomment-648929588) ?

+1

**Comment by mattiaverga** [comment]
> > What do you think of [#4067 (comment)](https://github.com/fedora-infra/bodhi/issues/4067#issuecomment-648929588) ?
> 
> +1

Do you want to add the code here, or should I approve this PR and then post another PR?

**Comment by cverna** [comment]
> > > What do you think of [#4067 (comment)](https://github.com/fedora-infra/bodhi/issues/4067#issuecomment-648929588) ?
> > 
> > 
> > +1
> 
> Do you want to add the code here, or should I approve this PR and then post another PR?

If you want to do it I think you can push an extra commit to this PR, so that we can merge everything together :-). Otherwise just approve this one and feel free to open a new PR.

**Review by mattiaverga — APPROVED** [review]
I'll post another PR, meanwhile this one is approved!

**Pull request merged**
