### PR TITLE
Updates for 5.7.2 release

### PR DESCRIPTION
**Pull request by AdamSaleh**

### CODE REVIEW

**Comment by AdamSaleh** [comment]
@mattiaverga review? One thing I am wondering if I should run towncrier to make release notes on develop branch, or on 5.7

**Comment by mattiaverga** [comment]
I think it's better to bump the release and build release notes in `devel`, then merge everything in `5.7`.

Can you please also add #4300 to the backport? (if tests pass, I made a quick fix in a hurry)

**Comment by AdamSaleh** [comment]
Yep, will look into  #4300

**Comment by mattiaverga** [comment]
I took the liberty of fixing the order of the last two commits and regenerate the release notes, removing the news fragments from the news directory.

**Review by mattiaverga — APPROVED** [review]

**Pull request merged**
