### PR TITLE
Add a script to run a docker test for a single release

### PR DESCRIPTION
**Pull request by puiterwijk**
Signed-off-by: Patrick Uiterwijk <puiterwijk@redhat.com>

### CODE REVIEW

**Comment by puiterwijk** [comment]
The major advantage of this over running the standard test script with a single release in RELEASES is that this doesn't use parallel, thus it prints out stdout/stderr as they happen, so you get quick test results.

**Comment by bowlofeggs** [comment]
This duplicates some code with the other script. I wonder if we could instead make the other script not use parallel when len(RELEASES) is 1. Perhaps we could substitute the call to parallel with "" or something clever? That way we don't have to maintain two scripts.

**Comment by bowlofeggs** [comment]
I just remembered that parallel has a flag that can make it output its text right away rather than buffering it until the end. We could use that flag when the length of RELEASES is 1 and that might be a real easy way to do it.

**Comment by bowlofeggs** [comment]
See https://github.com/fedora-infra/bodhi/pull/2219 for an implementation of what I mean.

**Comment by bowlofeggs** [comment]
I think we can close this since we have #2219 merged.

**Pull request closed without merging**
