### PR TITLE
Use warning() instead of warn() for logging.

### PR DESCRIPTION
**Pull request by bowlofeggs**
The warn() logging method is deprecated and has been replaced with
warning().

Signed-off-by: Randy Barlow <randy@electronsweatshop.com>

### CODE REVIEW

**Review by cverna — DISMISSED** [review]

**Comment by bowlofeggs** [comment]
This PR edits some code that lacks test coverage. I have a task on my backlog to finish out the last 1% of test coverage, so I think I will just do that in a separate PR in about a month and then rebase this on that once it is merged.

**Comment by bowlofeggs** [comment]
This should pass CI once it is rebased on https://github.com/fedora-infra/bodhi/pull/2493

**Comment by bowlofeggs** [comment]
jenkies test

**Comment by bowlofeggs** [comment]
Ah, looks like maybe some new assertions about the changed calls were made since I wrote this patch. I'll rebase and fix.

**Comment by bowlofeggs** [comment]
@cverna, I am applying this patch to account for recent new tests to get CI to pass:

```
diff --git a/bodhi/tests/server/test_models.py b/bodhi/tests/server/test_models.py
index a9470eb8..bd846029 100644
--- a/bodhi/tests/server/test_models.py
+++ b/bodhi/tests/server/test_models.py
@@ -274,11 +274,11 @@ class TestBugDefaultMessage(BaseTestCase):
         self.assertTrue(update.status.description in message)
         self.assertTrue(update.get_url() in message)

-    @mock.patch('bodhi.server.models.log.warn')
+    @mock.patch('bodhi.server.models.log.warning')
     @mock.patch.dict(
         config,
         {'stable_bug_msg': '%s%s', 'testing_bug_msg': '%s', 'base_address': 'b'}, clear=True)
-    def test_epel_without_testing_bug_epel_msg(self, warn):
+    def test_epel_without_testing_bug_epel_msg(self, warning):
         """Test with testing_bug_epel_msg undefined."""
         bug = model.Bug()
         update = model.Update.query.first()
@@ -287,7 +287,7 @@ class TestBugDefaultMessage(BaseTestCase):

         message = bug.default_message(update)

-        warn.assert_called_once_with("No 'testing_bug_epel_msg' found in the config.")
+        warning.assert_called_once_with("No 'testing_bug_epel_msg' found in the config.")
         self.assertTrue(update.builds[0].nvr in message)
         self.assertTrue(update.release.long_name in message)
         self.assertTrue(update.status.description in message)
@@ -2655,12 +2655,12 @@ class TestUpdate(ModelTest):

         self.assertEqual(self.obj.status, UpdateStatus.obsolete)

-    @mock.patch('bodhi.server.models.log.warn')
-    def test_remove_tag_emptystring(self, warn):
+    @mock.patch('bodhi.server.models.log.warning')
+    def test_remove_tag_emptystring(self, warning):
         """Test remove_tag() with a tag of ''."""
         self.assertEqual(self.obj.remove_tag(''), [])

-        warn.assert_called_once_with(
+        warning.assert_called_once_with(
             'Not removing builds of {} from empty tag'.format(self.obj.title))

     def test_revoke_no_request(self):
```

**Comment by bowlofeggs** [comment]
@cverna This is ready for re-review now.

**Review by pypingou — APPROVED** [review]
Looks like you're also in for the badge fixing hundreds of deprecation warning when running the tests :)

**Pull request merged**
