### PR TITLE
Produce useful wheels for pypi

### LINKED ISSUE #2401: Error in setup.py in bodhi-client-3.3.0
Got this error by pip install.

```
pip install "bodhi-client>=2.0,<4"
Collecting bodhi-client<4,>=2.0
  Downloading https://files.pythonhosted.org/packages/d3/8e/ce082026aca1e337a317c44c44c4834c7d6f7de05948c18f427ea1411026/bodhi-client-3.3.0.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/bodhi.egg-info
    writing pip-egg-info/bodhi.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/bodhi.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/bodhi.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/bodhi.egg-info/SOURCES.txt'
    package init file 'bodhi/__init__.py' not found (or not a regular file)
    reading manifest file 'pip-egg-info/bodhi.egg-info/SOURCES.txt'
    writing manifest file 'pip-egg-info/bodhi.egg-info/SOURCES.txt'
    running egg_info
    creating pip-egg-info/bodhi_client.egg-info
    writing requirements to pip-egg-info/bodhi_client.egg-info/requires.txt
    writing pip-egg-info/bodhi_client.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/bodhi_client.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/bodhi_client.egg-info/dependency_links.txt
    writing entry points to pip-egg-info/bodhi_client.egg-info/entry_points.txt
    writing manifest file 'pip-egg-info/bodhi_client.egg-info/SOURCES.txt'
    reading manifest file 'pip-egg-info/bodhi_client.egg-info/SOURCES.txt'
    reading manifest template 'CLIENT_MANIFEST.in'
    writing manifest file 'pip-egg-info/bodhi_client.egg-info/SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-quDnNB/bodhi-client/setup.py", line 127, in <module>
        server_packages.remove('bodhi')
    ValueError: list.remove(x): x not in list
```

### LINKED ISSUE #3919: bodhi can't be installed from pypi
This is a big problem now that python-fedora obsoleted internal bodhi client and had a new release, because bodhi can't now be installed from pypi in any way.

```bash
$ pip search bodhi
bodhi (5.1.0)           - bodhi common package
bodhi-server (5.1.0)    - bodhi server
bodhi-client (5.1.0)    - bodhi client
bodhi-messages (5.1.0)  - JSON schema for messages sent by Bodhi

$ pip install bodhi-client
Collecting bodhi-client
  Using cached bodhi-client-5.1.0.tar.gz (33 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/kparal/devel/venv/bodhi-test/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-l1xmx9dq/bodhi-client/setup.py'"'"'; __file__='"'"'/tmp/pip-install-l1xmx9dq/bodhi-client/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-l1xmx9dq/bodhi-client/pip-egg-info
         cwd: /tmp/pip-install-l1xmx9dq/bodhi-client/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-l1xmx9dq/bodhi-client/setup.py", line 42, in <module>
        with open(os.path.join(here, "bodhi", "__init__.py")) as fd:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-l1xmx9dq/bodhi-client/bodhi/__init__.py'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

$ pip install bodhi
Collecting bodhi
  Using cached bodhi-5.1.0.tar.gz (192 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/kparal/devel/venv/bodhi-test/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-v4ddb48p/bodhi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-v4ddb48p/bodhi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-v4ddb48p/bodhi/pip-egg-info
         cwd: /tmp/pip-install-v4ddb48p/bodhi/
    Complete output (18 lines):
    running egg_info
    creating /tmp/pip-install-v4ddb48p/bodhi/pip-egg-info/bodhi.egg-info
    writing /tmp/pip-install-v4ddb48p/bodhi/pip-egg-info/bodhi.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-install-v4ddb48p/bodhi/pip-egg-info/bodhi.egg-info/dependency_links.txt
    writing top-level names to /tmp/pip-install-v4ddb48p/bodhi/pip-egg-info/bodhi.egg-info/top_level.txt
    writing manifest file '/tmp/pip-install-v4ddb48p/bodhi/pip-egg-info/bodhi.egg-info/SOURCES.txt'
    reading manifest file '/tmp/pip-install-v4ddb48p/bodhi/pip-egg-info/bodhi.egg-info/SOURCES.txt'
    reading manifest template 'BODHI_MANIFEST.in'
    writing manifest file '/tmp/pip-install-v4ddb48p/bodhi/pip-egg-info/bodhi.egg-info/SOURCES.txt'
    running egg_info
    creating /tmp/pip-install-v4ddb48p/bodhi/pip-egg-info/bodhi_client.egg-info
    writing /tmp/pip-install-v4ddb48p/bodhi/pip-egg-info/bodhi_client.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-install-v4ddb48p/bodhi/pip-egg-info/bodhi_client.egg-info/dependency_links.txt
    writing entry points to /tmp/pip-install-v4ddb48p/bodhi/pip-egg-info/bodhi_client.egg-info/entry_points.txt
    writing requirements to /tmp/pip-install-v4ddb48p/bodhi/pip-egg-info/bodhi_client.egg-info/requires.txt
    writing top-level names to /tmp/pip-install-v4ddb48p/bodhi/pip-egg-info/bodhi_client.egg-info/top_level.txt
    writing manifest file '/tmp/pip-install-v4ddb48p/bodhi/pip-egg-info/bodhi_client.egg-info/SOURCES.txt'
    error: package directory 'bodhi/client' does not exist
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

### PR DESCRIPTION
**Pull request by mattiaverga**
This PR should allow producing useful wheels for pip installation.

p.s. Bodhi in PyPI is still at 5.2.0

fix #3919 
fix #2401

Signed-off-by: Mattia Verga <mattia.verga@tiscali.it>

### CODE REVIEW

**Review by cverna — APPROVED** [review]
LGTM, I pushed 5.4.0 to pypi and it works :fireworks:

**Comment by mattiaverga** [comment]
I think this is now causing integration test failures, unfortunately I had no time to investigate the problem before the merge...

**Comment by cverna** [comment]
> I think this is now causing integration test failures, unfortunately I had no time to investigate the problem before the merge...

Ha yeah the integration tests were broken but seemed unrelated :(. Going to look at it today

**Comment by cverna** [comment]
Ok so one thing is koji installed as an rpm does put all the info for pip install to find it, so we have to pip install koji manually (https://pagure.io/koji/issue/912). And then I am not sure why the static files are not included any more so for now I reverted that change in (https://github.com/fedora-infra/bodhi/commit/9994dcaf09e24e1b49b1c39b62eb18a92156ca10)

I tests the static file thing using 
```
FROM fedora:32
LABEL \
  name="bodhi-base" \
  vendor="Fedora Infrastructure" \
  license="MIT"

RUN dnf install -y \
    git                         \
    python3-pip                 \
    fedora-messaging            \
    httpd                       \
    intltool                    \
    origin-clients              \
    python3-alembic             \
    python3-arrow               \
    python3-backoff             \
    python3-bleach              \
    python3-celery              \
    python3-click               \
    python3-colander            \
    python3-cornice             \
    python3-dogpile-cache       \
    python3-fedora-messaging    \
    python3-feedgen             \
    python3-jinja2              \
    python3-markdown            \
    python3-psycopg2            \
    python3-py3dns              \
    python3-pyasn1-modules      \
    python3-pylibravatar        \
    python3-pyramid             \
    python3-pyramid-fas-openid  \
    python3-pyramid-mako        \
    python3-pyramid_sawing      \
    python3-bugzilla            \
    python3-fedora              \
    python3-pyyaml              \
    python3-simplemediawiki     \
    python3-sqlalchemy          \
    python3-waitress            \
    python3-dnf                 \
    python3-koji                \
    python3-librepo             \
    python3-mod_wsgi            \
    python3-gunicorn            \
    koji && \
    dnf clean all

RUN git clone -b 5.4.1 https://github.com/fedora-infra/bodhi.git /srv/bodhi
```
then
```
podman build -t bodhi-test .
podman run -it --rm bodhi-test
$ cd /srv/bodhi
$ python3 -m pip install . --no-use-pep517
$ ll /usr/local/lib/python3.8/site-packages/bodhi/server/email
```

**Comment by cverna** [comment]
I think we might want to look at https://github.com/fedora-infra/bodhi/issues/3824 so we get ride of the weird setup.py thing :)

**Comment by pypingou** [comment]
you can also test using something like:
````
mkdir /tmp/base
python setup.py install --prefix=/tmp/base
tree /tmp/base
````

**Pull request merged**
