### PR TITLE
Adam Will - resultsdb consumer pullrequest rebase

### PR DESCRIPTION
**Pull request by AdamSaleh**
New attempt at rebasing https://github.com/fedora-infra/bodhi/pull/4230 so that it is mergeable.

### CODE REVIEW

**Comment by Zlopez** [comment]
Does this mean that Greenwave will no longer be used?

**Comment by AdamSaleh** [comment]
@Zlopez based on the discussion in the original PR #4230 it is about a specific decision update messages we have used, that required Greenwave to duplicate lot of knowledge Bodhi already knew. I am not sure what else do we use Greenwave for.

**Comment by mattiaverga** [comment]
I have rebased #4230 so that it's mergeable and added a couple of comments there.

**Comment by AdamSaleh** [comment]
@mattiaverga great, closing this one then!

**Pull request closed without merging**
