### PR TITLE
README.rst  Directly link release notes

### PR DESCRIPTION
**Pull request by abitrolly**
Directly link release notes

### CODE REVIEW

**Comment by bowlofeggs** [comment]
jenkies test

**Review by bowlofeggs — APPROVED** [review]

**Comment by bowlofeggs** [comment]
The CI failure is due to https://bugzilla.redhat.com/show_bug.cgi?id=1607916 so don't worry about it. I'll check it again in a while.

**Comment by bowlofeggs** [comment]
jenkies test

**Comment by bowlofeggs** [comment]
jenkies test

**Comment by abitrolly** [comment]
Does CI work?

**Comment by bowlofeggs** [comment]
jenkies test

**Review by bowlofeggs — APPROVED** [review]

**Comment by abitrolly** [comment]
@bowlofeggs so what does that mean?

image

**Comment by abitrolly** [comment]
Mergify bot should merge this issue, but it is offline, right?

**Comment by bowlofeggs** [comment]
@abitrolly Hmmm. Not sure what happened, but it looks like CI just didn't run. I'll try re-kicking it.

**Comment by bowlofeggs** [comment]
jenkies test

**Comment by bowlofeggs** [comment]
Ah, looks like it's a known problem and the CentOS admins are working on it:

https://lists.centos.org/pipermail/ci-users/2018-August/000842.html

So theoretically it should run eventually.

**Comment by abitrolly** [comment]
Mergify was waiting for CI to complete? The `default` is the CentOS CI?

**Comment by bowlofeggs** [comment]
@abitrolly Correct, and I think there was an outage on CentOS CI at the time. Sorry it took so long!

**Comment by abitrolly** [comment]
There is nothing to say sorry about. Unless you want to keep me as an external contributor. :D

Is there a source code for CentOS CI integration with GitHub to fix the `default`? I'd like to see the template it was generated from. The **default** thing must be from there.

**Comment by bowlofeggs** [comment]
On 08/17/2018 10:54 AM, Anatoli Babenia wrote:
> There is nothing to say sorry about. Unless you want to keep me as an
> external contributor. :D

I most certainly do want to keep you as a contributor, and thanks for
all your patches!

> Is there a source code for CentOS CI integration with GitHub to fix the
> |default|? I'd like to see the template it was generated from. The
> *default* thing must be from there.

I actually don't know why it's called default. The JJB template we use
is here, but I don't see "default" in it:

https://github.com/fedora-infra/bodhi/blob/develop/devel/ci/githubprb-project.yml

There is a mailing list for the CentOS CI system, perhaps they would know?

https://lists.centos.org/mailman/listinfo/ci-users

**Comment by abitrolly** [comment]
Asked. Should appear here if everything is ok. https://lists.centos.org/pipermail/ci-users/2018-August/thread.html

**Pull request merged**
