### PR TITLE
Correctly handle IncompleteRead in the Composer.

### LINKED ISSUE #2758: IncompleteRead while Composer polls for repomd files
It seems that Python's http library can raise a new Exception in Python 3 that we don't catch:

```
[2018-11-20 14:42:34][fedmsg.consumers    INFO]epel7-testing Polling http://download01.phx2.fedoraproject.org/pub/epel/testing/7/aarch64/repodata/repomd.xml
[2018-11-20 14:42:34][fedmsg.consumers   ERROR]epel7-testing Exception in ComposerThread(epel7-testing)
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/bodhi/server/consumers/masher.py", line 410, in work
    self._compose_updates()
  File "/usr/lib/python3.7/site-packages/bodhi/server/consumers/masher.py", line 959, in _compose_updates
    self._wait_for_sync()
  File "/usr/lib/python3.7/site-packages/bodhi/server/consumers/masher.py", line 1327, in _wait_for_sync
    newsum = hashlib.sha1(masterrepomd.read()).hexdigest()
  File "/usr/lib64/python3.7/http/client.py", line 460, in read
    s = self._safe_read(self.length)
  File "/usr/lib64/python3.7/http/client.py", line 612, in _safe_read
    raise IncompleteRead(b''.join(s), amt)
http.client.IncompleteRead: IncompleteRead(3295 bytes read, 1 more expected)
```

This one should be pretty easy to fix - we just need to catch this new Exception and retry, similar to what we do if a URLError is raised.

### PR DESCRIPTION
**Pull request by bowlofeggs**
fixes #2758

Signed-off-by: Randy Barlow <randy@electronsweatshop.com>

### CODE REVIEW

**Comment by bowlofeggs** [comment]
I don't know why the Fedora 27 builds are failing, but Fedora 27 is EOL so let's ignore it. I've filed https://github.com/fedora-infra/bodhi/pull/2797 to stop testing it.

The rawhide diff-cover failure is fixed by https://src.fedoraproject.org/rpms/python-diff-cover/c/354c48310713d859431e7733ac1a37a609b664b4?branch=master but that build hasn't propagated to all the mirrors yet. We can safely ignore it here.

**Review by puiterwijk — APPROVED** [review]

**Comment by bowlofeggs** [comment]
I'm going to rebase so it picks up the changes from #2797.

**Comment by bowlofeggs** [comment]
The ```pip-build``` failure is due to some problem pip installing ```twisted```, so we can ignore it.

**Comment by bowlofeggs** [comment]
Also, CentOS CI seems to be having some trouble putting GitHub statuses on this pull request, so I manually verified that the other builds did pass.

**Pull request merged**
