### PR TITLE
Test bodhi.client.bindings

### PR DESCRIPTION
**Pull request by bowlofeggs**
This pull request has 5 atomic commits that focus on adding test coverage to ```bodhi.client.bindings```. They also remove some unusable code, and fix two issues. The commit messages give more detail.

### CODE REVIEW

**Comment by bowlofeggs** [comment]
Ah, I seem to have forgotten that dnf is only installed on Fedora systems. It's bed time now, but I'll make dnf an optional dependency and fix this PR up soon.

Or, we could make dnf a dependency as it is available on EL 7…

**Review by ryanlerch — COMMENTED** [review]
closed #1713 which did the same thing as this commit, but are you able to add Fixed #784 to this commit?

**Comment by bowlofeggs** [comment]
@ryanlerch Haha yeah I noticed after submitting this PR that we had made tests and fix for the same code, but it was midnight and I figured I'd inspect the two to see what to do later. It seems like an unlikely coincidence! Whenever I go on test writing rampages, I use the random module to pick some code that isn't tested and it just happened to pick testing that code. I noticed pretty quickly that it didn't work (with the 403) and that it just needed a GET.

Sure, I'll amend the commit message to reference #784.

On the topic of the CI failure - I've slept on it and I think I lean towards making dnf a requirement. Technically, it was a requirement for that function before anyway and was just undeclared. So if EPEL 7 users tried to use that function, they'd get a traceback. Since dnf is available in EPEL 7 I think it's better to just make it a requirement and call it a day. I'm going to make that change too, but feel free to counterpoint if you disagree ☺

**Comment by bowlofeggs** [comment]
This most recent failure was due to https://bugzilla.redhat.com/show_bug.cgi?id=1476364. I will adjust the commit so that dnf isn't listed as a dependency in ```setup.py``` (even though it really is a dependency).

**Comment by bowlofeggs** [comment]
Ugh, and now a mock that works on F25 doesn't work on EL 7:

```
AssertionError: Expected call: listTagged('f26-updates-testing', latest=True) Actual call: listTagged("f<MagicMock name='open().readlines().__getitem__().split().__getitem__()' id='83276240'>-updates-testing", latest=True)
```

**Comment by bowlofeggs** [comment]
Ah, this is actually a mock bug that's been fixed upstream but not in EPEL 7 ☹ I started thinking that it felt familiar and then I remembered that I've been down this exact road before. ```mock_open()```'s ```readlines()``` implementation was not correct and hasn't been fixed. I'll have to write my own mock instead of using ```mock_open()```.

**Comment by bowlofeggs** [comment]
I have now resolved the CI issues with this pull request and it is ready for review.

**Review by ryanlerch — APPROVED** [review]
This looks good to me, @bowlofeggs! +1 for adding dnf as a formal dep.

also +100 for another percentage point in testing coverage!!! 🌮 🌮 🌮

**Pull request merged**
