### PR TITLE
Remove misplaced variable in the update template

### PR DESCRIPTION
**Pull request by abompard**
Fixes: #3025
Signed-off-by: Aurélien Bompard <aurelien@bompard.org>

### CODE REVIEW

**Comment by bowlofeggs** [comment]
The CI failure is due to https://bugs.centos.org/view.php?id=15791 - the test did pass.

**Comment by abompard** [comment]
The Jenkins error is just a gigantic Java traceback about not being able to reach `api.github.com`, I think we can ignore it.

**Review by bowlofeggs — APPROVED** [review]
Thanks for the fix - I confirmed that "rpm" goes away. I'll rebase and merge.

**Comment by bowlofeggs** [comment]
I'm going to manually run CI on this since CentOS CI seems to be out of GitHub API requests.

**Pull request merged**
