### PR TITLE
Only logged in users can add karma to updates.

### LINKED ISSUE #2474: karma voting section for anonymous users should indicate their karma will be ignored
https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2018-88c0c447a4
has what appears to be three karma: 👍items.
But, afaict, the third, from anonymous is ignored by the calculator.
We believe that's to protect against bots. That's fine, but I'm fairly confident a human wrote that message.

It would be nice if the interface told the human that they should use an account if they want their vote to be tallied.

### PR DESCRIPTION
**Pull request by mattiaverga**
Anonymous users will no more be able to post main karma to updates. This change will also remind users to log in if they want they're votes to be taken into account by the "autopush to stable" feature.

Users not logged in will see a lock icon and the description greyed out, plus the radio buttons will be disabled:
immagine

Fixes #2474 
Signed-off-by: Mattia Verga <mattia.verga@tiscali.it>

### CODE REVIEW

**Review by bowlofeggs — COMMENTED** [review]
I personally like this change because I think it makes it more obvious that you need to be logged in for your vote to count, but since it's a bit of a departure from what we've been doing I'd like to see if someone from QA would like to chime in too.

@AdamWill @kparal Do either of you have an opinion on this?

**Comment by kparal** [comment]
I think requiring login to submit karma is fine, better than allowing it but not counting it which might be confusing for maintainers. Any issues should be written out in comment anyway, so we're not missing out.

I don't like the UI, though. The mockup in #2474 looks clearer to me. The red lock doesn't tell me anything. I assume a popup is implemented with more description on mouse over? Anyway, popups are fine for non-important stuff, but important stuff should be written out clearly, as in the mockup. It's more visible and more understandable.

I'd also make the karma vote appear as the first one in the list, and the critpath vote the second one (then bugs and test cases). It always confused me why the most important option is listed last.

Those are just my nitpicks, nothing serious.

**Comment by mattiaverga** [comment]
> I assume a popup is implemented with more description on mouse over?

Yes, I forgot to say that.
Anyway, I can easily revert to the mockup if you prefer, or make a combo of the two, with or without strikethrough text:
immagine
We can choose the preferred one!


> I'd also make the karma vote appear as the first one in the list, and the critpath vote the second one (then bugs and test cases).

+1

**Comment by bowlofeggs** [comment]
Cool I like the new mockup too. I don't have a strong feeling, but I have a slight preference to the one without strikethrough. Either one is cool with me though if others feel strongly.

**Comment by kparal** [comment]
> Cool I like the new mockup too. I don't have a strong feeling, but I have a slight preference to the one without strikethrough.

That's the second one or the third one? :-) I'd personally pick the third one and remove the lock icon (to avoid visual clutter with too many icons, bodhi page is colorful enough already). So IOW the first one without the strikethrough. But I do not have strong feelings about it, I just prefer important messages to be immediately visible instead of hidden behind popup, that's all.

**Comment by bowlofeggs** [comment]
@kparal I don't feel strongly about the lock icon, but I agree that the presence of the red text is helpful and is clearer than a hoverover.

@ryanlerch do you have an opinion here?

**Comment by mattiaverga** [comment]
I've changed the style as in the original mockup and I also moved karma and critpath votes on top of the list:
immagine

**Review by bowlofeggs — APPROVED** [review]
Looks great, thanks for adjusting to the feedback!

**Comment by bowlofeggs** [comment]
These patches are planned to be included in the upcoming 3.10.0 release: #2556.

**Comment by bowlofeggs** [comment]
These patches have been deployed to Fedora's staging Bodhi instance:

https://bodhi.stg.fedoraproject.org/

**Pull request merged**
