### PR TITLE
Drop the batching feature.

### LINKED ISSUE #2977: Drop the batching feature
Unfortunately, the batching feature was pretty controversial among the Fedora community and we were unable to garner enough support to keep it. FESCo has [voted](https://pagure.io/fesco/issue/1820) to remove it.

I would personally like to keep the feature, but I would also prefer not to have to maintain it if Fedora is not going to use it.

### PR DESCRIPTION
**Pull request by bowlofeggs**
The batching feature was controversial in the Fedora community.
FESCo opted to disable it several months ago, and more recently
voted to remove the feature.

fixes #2977

Signed-off-by: Randy Barlow <randy@electronsweatshop.com>

### CODE REVIEW

**Comment by bowlofeggs** [comment]
Credit to @sebwoj in #2954 for coming up with the migration code to modify an enum.

**Review by Zlopez — APPROVED** [review]
LGTM

**Comment by bowlofeggs** [comment]
This patch is planned for inclusion in the upcoming 4.0.0 release: #3221

**Comment by bowlofeggs** [comment]
Bodhi 4.0.0 beta is built and deployed to staging:

https://copr.fedorainfracloud.org/coprs/bowlofeggs/bodhi-pre-release
https://bodhi.stg.fedoraproject.org/

**Pull request merged**
