### PR TITLE
bodhi-check-policies now also operates on pushed updates.

### LINKED ISSUE #2085: bodhi-check-policies only operates on unpushed updates
I noticed today when working on #1514 that the update query that ```bodhi-check-policies``` performs only selects [unpushed updates](https://github.com/fedora-infra/bodhi/blob/3.1.0/bodhi/server/scripts/check_policies.py#L40-L42):

```
updates = models.Update.query.filter(models.Update.pushed == false())\
        .filter(models.Update.status.in_(
                [models.UpdateStatus.pending, models.UpdateStatus.testing]))
```

I think this is probably not what we want, as [testing updates are marked pushed](https://github.com/fedora-infra/bodhi/blob/3b655f2/bodhi/server/consumers/masher.py#L845-L857). This means we will only consult Greenwave about pending updates.

### PR DESCRIPTION
**Pull request by bowlofeggs**
fixes #2085

Signed-off-by: Randy Barlow <randy@electronsweatshop.com>

### CODE REVIEW

**Comment by bowlofeggs** [comment]
jenkies test

**Comment by bowlofeggs** [comment]
jenkies test

**Review by puiterwijk — APPROVED** [review]

**Comment by bowlofeggs** [comment]
jenkies test

**Comment by pypingou** [comment]
👍 for me as well

**Pull request merged**
