### PR TITLE
Do not re-compose if the repo is already staged

### PR DESCRIPTION
**Pull request by puiterwijk**
Signed-off-by: Patrick Uiterwijk <puiterwijk@redhat.com>

### CODE REVIEW

**Comment by puiterwijk** [comment]
This needs tests, and I'll work on those at some point.
It's purely for speeding resumptions up that crashed after syncing.

**Review by bowlofeggs — CHANGES_REQUESTED** [review]
LGTM, we just need some tests.

**Comment by bowlofeggs** [comment]
jenkies test

**Comment by bowlofeggs** [comment]
The CI system is just mad about coverage, but we knew we needed some tests so no worries there :)

**Comment by bowlofeggs** [comment]
We will probably want to refactor this in light of #2052.

**Comment by bowlofeggs** [comment]
I'm going to close this due to inactivity. Feel free to reopen when you want to pick it back up.

**Comment by bowlofeggs** [comment]
I hadn't realized that this patch actually fixes a bug and isn't just a performance enhancement when I closed it. We do need to get this finished up and merged.

**Comment by puiterwijk** [comment]
(The reworked code does not yet pass tests because of the new checkpoint, and I want to add new tests, but just figured I'd rewrite the patch itself)

**Review by bowlofeggs — APPROVED** [review]

**Review by bowlofeggs — CHANGES_REQUESTED** [review]
We should add a test to ensure that the compose really is skipped if compose_done is true in the checkpoints dictionary.

**Comment by puiterwijk** [comment]
You almost fell for it :). Test pushed.

**Review by bowlofeggs — APPROVED** [review]

**Comment by bowlofeggs** [comment]
jenkies test

**Comment by bowlofeggs** [comment]
This patch is planned to be included in the upcoming 3.9.0 release: #2477.

**Comment by bowlofeggs** [comment]
This patch was deployed to Fedora's production Bodhi instance yesterday.

**Pull request merged**
